### ISSUE TITLE
Output Quantitty Adiabatic Surface Temperature

### ISSUE THREAD

**Issue by ChristianKraft** [firemodels/cfast#1094]
Hello,

is it possible to add the quantity "Adiabatic Surface Temperature" to the output of a target?

Best regards,
Christian.

**Comment by andytamhk168** [comment]
Dear Christian,

Would you mind to explain to me the reasons why you would like to have "adiabatic surface temperature" to target?

I need more information to put the thoughts together.

Thanks,
Andy

**Comment by mcgratta** [comment]
See the FDS User's Guide for an explanation of AST.

**Comment by andytamhk168** [comment]
@mcgratta Thank you very much for the information.

**Comment by ChristianKraft** [comment]
@andytamhk168 we use the AST as input for other programs (for example SAFIR), that are able to calculate the heat transfer into other compnents. For this reason it is import to have the raditive and the convective heat flux. These are included in the AST.

**Comment by andytamhk168** [comment]
@ChristianKraft Implementation of an additional output quantity (adiabatic surface temperature) to a target is in process.

**Comment by andytamhk168** [comment]
@ChristianKraft Just for my curiosity, are you running CFAST with the source code or through CEdit? Also, do you have a simple input file you would like me to run for you?

**Comment by rpeacoc** [comment]
This is implemented in 6b9b32b .  Required inputs are on the &DEVC for targets (ADIABATIC_TARGET and CONVECTION_COEFFICENTS) and only available with manual editing of the input file (GUI recognizes and preserves the existence of adiabatic targets, but does not include the ability to add or edit them since it's a very specialized input).
