### ISSUE TITLE
Tidying up cfast top level

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/cfast#1095]
Rick,
Can you add CONTRIBUTING.md and CODE_OF_CONDUCT.md files to the top level of CFAST repo (see [firemodels/fds](https://github.com/firemodels/fds)).  Also, do we need ReadMe.htm at top level?  I'd like FDS and CFAST to be identical if possible.  Thanks.

**Comment by rpeacoc** [comment]
Done.  

Randy, where is the code of conduct linked from in FDS?

**Comment by rmcdermo** [comment]
Well, that CODE_OF_CONDUCT.md was simply a wiki page called FDS SMV Group Policies.  It was changed on firemodels/fds.wiki/commit/ce0a7911b3d44b0015eea2e3cbc3582731a5334e
