### ISSUE TITLE
cedit saving new fire to protected area

### ISSUE THREAD

**Issue by GoogleCodeExporter** [firemodels/cfast#112]
```
What steps will reproduce the problem?
1. create a new room
2. create a custom fire by clicking on the edit button in the "Fire object area"
3. save case

saving case results in a crash - see attached message

If I run cedit as administrator it works


```

Original issue reported on code.google.com by `gfor...@gmail.com` on 5 Apr 2014 at 1:39

Attachments:
- [cfast_error.png](https://storage.googleapis.com/google-code-attachments/cfast/issue-112/comment-0/cfast_error.png)

**Comment by rpeacoc** [comment]
This should not be a problem with the latest version and would only be a problem in the older versions the first time you try to save something without opening an existing file.  Workaround for older versions should be to use Save As rather than save.
