### ISSUE TITLE
Spurious heat flux values with a test case

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#1176]
The following text case shows spikes in target heat flux > 1MW/m^2.  Likely fire heat flux is too large due to extremely close fire. Check with -v option 

&HEAD VERSION = 7300, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 3600 PRINT = 600 SMOKEVIEW = 10 SPREADSHEET = 10 / 
&INIT PRESSURE = 101300 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  MAX_TIME_STEP = 2 LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Material Properties 
&MATL ID = 'SwMCCConcrete' MATERIAL = 'Switchgear MCC Concrete (user''s guide)' 
      CONDUCTIVITY = 1.6 DENSITY = 2400 SPECIFIC_HEAT = 0.75, THICKNESS = 0.6 EMISSIVITY = 0.9 /
&MATL ID = 'SwMCCSteel' MATERIAL = 'Switchgear MCC Steel (user''s guide)' 
      CONDUCTIVITY = 54 DENSITY = 7850 SPECIFIC_HEAT = 0.465, THICKNESS = 0.0015 EMISSIVITY = 0.9 /
&MATL ID = 'THIEF' MATERIAL = 'Thief Cable (per NUREG CR 6931)', 
      CONDUCTIVITY = 0.2 DENSITY = 2264 SPECIFIC_HEAT = 1.5, THICKNESS = 0.015 EMISSIVITY = 0.8 /
 
!! Compartments 
&COMP ID = 'Low Ceiling Area'
      DEPTH = 8.5 HEIGHT = 9.1 WIDTH = 17.1 CEILING_MATL_ID = 'SwMCCConcrete' WALL_MATL_ID = 'SwMCCConcrete' FLOOR_MATL_ID = 'SwMCCConcrete'
      CROSS_SECT_AREAS = 145.35, 145.35, 73.1, 73.1
      CROSS_SECT_HEIGHTS = 0, 2.99, 3.01, 9.1
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 /
 
!! Wall Vents
&VENT TYPE = 'WALL' ID = 'WallVent_2' COMP_IDS = 'Low Ceiling Area' 'OUTSIDE'  TOP = 0.013, BOTTOM = 0, WIDTH = 1
      FACE = 'FRONT' OFFSET = 8.05 /
&VENT TYPE = 'WALL' ID = 'WallVent_3' COMP_IDS = 'Low Ceiling Area' 'OUTSIDE'  TOP = 0.013, BOTTOM = 0, WIDTH = 1
      FACE = 'REAR' OFFSET = 2.5 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_1' COMP_IDS = 'OUTSIDE', 'Low Ceiling Area'
      AREAS = 0.2, 0.2 HEIGHTS = 2.45, 2.45 FLOW = 0.735 CUTOFFS = 200, 300 OFFSETS = 0, 4.25 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_2' COMP_IDS = 'Low Ceiling Area', 'OUTSIDE'
      AREAS = 0.2, 0.2 HEIGHTS = 6.05, 6.05 FLOW = 0.735 CUTOFFS = 200, 300 OFFSETS = 17.1, 4.25 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
 
!! Fires 
&FIRE ID = 'MCC 702 kW'  COMP_ID = 'Low Ceiling Area', FIRE_ID = 'MCC 702 kW_Fire'  LOCATION = 2.8, 4.15 / 
&CHEM ID = 'MCC 702 kW_Fire' CARBON = 3 CHLORINE = 0.5 HYDROGEN = 4.5 NITROGEN = 0 OXYGEN = 0 HEAT_OF_COMBUSTION = 10300 RADIATIVE_FRACTION = 0.53 / 
&TABL ID = 'MCC 702 kW_Fire' LABELS = 'TIME', 'HRR' , 'HEIGHT' , 'AREA' , 'CO_YIELD' , 'SOOT_YIELD' , 'HCN_YIELD' , 'HCL_YIELD' , 'TRACE_YIELD'  /
&TABL ID = 'MCC 702 kW_Fire', DATA = 0, 0, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 72, 7.02, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 144, 28.08, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 216, 63.18, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 288, 112.32, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 360, 175.5, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 432, 252.72, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 504, 343.98, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 576, 449.28, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 648, 568.62, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 720, 702, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 1200, 702, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 2340, 0, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
&TABL ID = 'MCC 702 kW_Fire', DATA = 2350, 0, 2.4, 0.12, 0.082, 0.175, 0, 0.3127314, 0 /
 
!! Devices
&DEVC ID = 'Targ 1' COMP_ID = 'Low Ceiling Area' LOCATION = 2.8, 4.15, 2.6 TYPE = 'CYLINDER' MATL_ID = 'THIEF'  NORMAL = 0, 0, -1 TEMPERATURE_DEPTH = 0.27 /
&DEVC ID = 'Targ 2' COMP_ID = 'Low Ceiling Area' LOCATION = 3, 5.5, 2.6 TYPE = 'CYLINDER' MATL_ID = 'THIEF'  NORMAL = -0.1449999, -0.9787492, -0.1449998 TEMPERATURE_DEPTH = 0.27 /
&DEVC ID = 'Targ 3' COMP_ID = 'Low Ceiling Area' LOCATION = 8.6, 4.25, 9 TYPE = 'CYLINDER' MATL_ID = 'THIEF'  NORMAL = 0, 0, -1 TEMPERATURE_DEPTH = 0.27 /
&DEVC ID = 'Targ 4' COMP_ID = 'Low Ceiling Area' LOCATION = 3.5, 5, 2.4 TYPE = 'CYLINDER' MATL_ID = 'SwMCCSteel'  NORMAL = -0.6357073, -0.7719302, 0 TEMPERATURE_DEPTH = 0.5 /

**Comment by andytamhk168** [comment]
In this current version of CFAST, the radiative heat flux from a fire to a target is proportional to 1/R^2 (assumption of point-to-point view factor calculation). In this case, the normal distance between the fire and the target (R) is ~ 0.02 m and R^2 is ~ 4.0E-4 m. For this reason, the radiative heat flux would become extremely large when R is approaching 0 m.  I have an idea to this problem. Let me test it out first.

**Comment by rpeacoc** [comment]
Three used to be a check to make sure it wasn't too close.  Lines 232-236 of target.f90 determine the fire flux.  It can go clear to a divide by (almost) zero.  

```
                if (s/=0.0_eb) then
                    qft = qfire*abs(cosang)*tauu*taul/(4.0_eb*pi*s**2)
                else
                    qft = 0.0_eb
                end if
```

That's where a check should be.  Clearly the point source approximation is no longer valid at such a small distance from the fire. You might check with Kevin on an appropriate minimum distance for the point source to be valid (probably based on fire diameter). I'd be very interested in your thoughts on how to fix.  Thanks

**Comment by andytamhk168** [comment]
Yes, you are right. I think since we know that when two surfaces (regardless of their size) are getting closer and closer together, the approximated view factor will become closer and closer to 1. 

For that, I have:
qft = min(qfire*abs(cosang)*tauu*taul/(4.0_eb*pi*s**2), &
                qfire*abs(cosang)*tauu*taul/(4.0_eb*pi)*(2.0_eb*pi))

This statement suggests that the target will receive half of the heat flux from fire (at maximum). The orientation effect will be accounted for by the cosang. The absorption effect will be accounted from by (1-tau). Also, this statement should help to avoid the qft to be out of bound. So, I think this should work, but let me double check first.

**Comment by rpeacoc** [comment]
Can you add something to the technical guide describing this limit?

**Comment by andytamhk168** [comment]
Definitely. Also, please kindly let me know if this change makes sense and is reasonable.

**Comment by rpeacoc** [comment]
Issue has been resolved.  Example case now gives expected results.
