### ISSUE TITLE
Lack of mass balance with mechnical ventilation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [firemodels/cfast#121]
```
What steps will reproduce the problem?
1.Completed a fresh install of CFAST
2.Ran attached input file
3.Opened output file to observe mass imbalance. 

What is the expected output? What do you see instead?
The mass balance for Array1 should sum to zero. There is a flow imbalance of 
about 0.5 kg/s.

What version of the product are you using? On what operating system?
CFAST 6.2.0.291, Windows 7 Enterprise

Please provide any additional information below.


```

Original issue reported on code.google.com by `cout...@asme.org` on 2 Oct 2014 at 6:20

Attachments:
* [Room100.in](https://storage.googleapis.com/google-code-attachments/cfast/issue-121/comment-0/Room100.in)
* [Room100.out](https://storage.googleapis.com/google-code-attachments/cfast/issue-121/comment-0/Room100.out)

**Comment by rpeacoc** [comment]
The original case balances fine in Gitv7 version. All flows through compartments (1 --> 2 --> 3 --> 4 --> outside) match at 1.1954 kg/s.  We'll close this one for now.
