### ISSUE TITLE
Tenability Calculation

### ISSUE THREAD

**Issue by ahmedsalem70** [firemodels/cfast#1253]
Does the current version of CFAST support tenability calculation?

**Comment by rpeacoc** [comment]
Yes. At every target location, the spreadsheet output includes tenability for toxic gases and converted heat per ISO 13571.

**Comment by ahmedsalem70** [comment]
I tried to estimate the FED using CFAST by applying a target at a certain location of concern, but the results were confusing as the FED gas were of the order of 10,000.

**Comment by rpeacoc** [comment]
I'll need your input file to diagnose it further

**Comment by ahmedsalem70** [comment]
Plz find attached herewith a copy of the input file.


[Case A.zip](https://github.com/firemodels/cfast/files/3162610/Case.A.zip)
