### ISSUE TITLE
Slab Temperature Higher than Gas Layer Temperature

### ISSUE THREAD

**Issue by johodges** [firemodels/cfast#1259]
Hello,

I was working with the zone (csv) output and noticed the temperature of some of the slabs through a horizontal ventilation exceed the upper layer temperature. I reviewed the documentation and the discussion group and did not see a previous discussion mentioning this. My expectation would be the max temperature in the slab should not be able to exceed the max temperature in either of the adjacent compartments. If this is the expected behavior I would appreciate if someone could explain why this occurs.

The attached input file generates the issue for the ventilation from compartment 1->3 (HSLAB_2) in the output files using CFAST 7.3.1.

[smallTest.zip](https://github.com/firemodels/cfast/files/3194548/smallTest.zip)

Thank you for your time,

Jonathan

**Comment by rpeacoc** [comment]
I see the confusion.  The slab temperatures are actually in Kelvin.  I'll fix the header information that indicates C. We don't actually use the header information.  This file is just a way for us to transfer information from CFAST to Smokeview and is not intended for general use.

**Comment by rpeacoc** [comment]
Corrected in 3eed18a
