### ISSUE TITLE
CFAST 7 - There is no results after "Run"

### ISSUE THREAD

**Issue by Aloren2** [firemodels/cfast#1263]
Hi!
I have just installed the last version of CFAST and tried it with Users_Guide_example.in file. After pressing Run button new window opens (Run Model...) but there is no any results...there is a mesage "No Errors" in the lower part of window and only active button is "Close". My computer is Lenovo V520-15IKL with Win 10 Pro. I suspect that maybe 64Bit version of software may be a problem or there is something else?
Thank you in advance...

**Comment by rpeacoc** [comment]
I can think of two possible problems

1. CFAST typically installs the software in the standard Windows install location which is not writeable by the user.  Did you copy the example file to a folder somewhere else or try to run it directly from the installed location?

2. We have seen cases where the first time a case is run in a newly installed version that the output is written to a different directory (that was being last used in the older version).  Try opening the file, pressing Ctrl-N, and opening the file again (from the file menu).

**Comment by Aloren2** [comment]
Thank you very much for the prompt answer. The problem was indeed solved by moving example file into another folder on another partition.
