### ISSUE TITLE
Show all colors in Smokeview rendering of CFAST layers

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#1288]
Could we show all layer temperatures in the Smokeview rendering of layers, not just upper.

**Comment by gforney** [comment]
Yes. I'll take a look

**Comment by mcgratta** [comment]
This feature already exists as an option. I'd like it to be the default.

**Comment by gforney** [comment]
I'll make the change

**Comment by gforney** [comment]
should be changed in smokeview posted here.  note the change won't show up if you earlier saved an .ini file with an older smokeview.  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rpeacoc** [comment]
Works with SMV release 6.7.8
