### ISSUE TITLE
 When rendering in Smokeview, door and window openings are not displayed, although they are taken into account when modeling.

### ISSUE THREAD

**Issue by YagmorD** [firemodels/cfast#1324]
When rendering in Smokeview, door and window openings are not displayed, although they are taken into account when modeling.

**Comment by gforney** [comment]
can you upload a test case that demonstrates the issue

**Comment by gforney** [comment]
can you upload a test case and indicate what you did to produce the problem.  It is difficult to debug without one.  thanks

**Comment by gforney** [comment]
also install the lastest cfast and smokeview and see if you can reproduce the problem
