### ISSUE TITLE
Add descriptions for base area of fire 

### ISSUE THREAD

**Issue by wnt2** [firemodels/cfast#1361]

**Comment by mcgratta** [comment]
Is this issue meant for Rick?

**Comment by preneke** [comment]
Yes

**Comment by rpeacoc** [comment]
I’ll take the dimensionless parameters description from FDS and add it to the CFAST V&V guide. Then I can add a short description of the default fire area calculation with a reference to the Q-star discussion in the CFAST V&V guide

**Comment by rpeacoc** [comment]
Turns out this is already included in section 6.2 on page 28 of the User's Guide
