### ISSUE TITLE
Validity of ceiling jet/devices with two or more plumes

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1370]
Is the ceiling jet model in CFAST valid when there are two or more fires in the same compartment, and in particular if the plumes are located near each other and/or offset vertically? The tech guide does not provide any description of the CJ model when there are multiple plumes. Some sensitivity test cases I created using targets were inconclusive, but the most adverse results were achieved when the fire HRRs were consolidated and the one fire re-centered.

**Comment by rpeacoc** [comment]
The correlations for ceiling jet temperature and velocity certainly come from studies of single fires.  What we do in CFAST is to take the maximum temperature from any of the fires and add the velocity vectors for fires.   All the comparisons in the CFAST V&V guide are for experiments with a single fire.
