### ISSUE TITLE
CEdit does not allow = in text strings in Namelist input files

### ISSUE THREAD

**Issue by pimzzff1** [firemodels/cfast#1385]
CFast 7.4.3 does not open a file I created using that same version. It gives the error as shown below. Can someone please help?

![Knipsel](https://user-images.githubusercontent.com/60132385/72790807-8bd34200-3c36-11ea-9394-bcdcab05e316.PNG)

**Comment by rmcdermo** [comment]
Please post the input file and we will have a look.  Thanks

**Comment by rpeacoc** [comment]
Is your numeric format set to "US American"? CFAST expects the numeric separator to be a decimal point , "." rather than a comma, ",". See this thread in the User's Group:

https://groups.google.com/forum/#!searchin/cfast/comma%7Csort:date/cfast/DN8QTTdKAAQ/-exls2BMDQAJ

**Comment by pimzzff1** [comment]
My numeric format is set to US American. 

The simulation ran just fine. After saving I tried re-opening the file and the shown error popped up.

Please find attached the in- and output files.

Thanks in advance!

[v1.zip](https://github.com/firemodels/cfast/files/4092045/v1.zip)

**Comment by rpeacoc** [comment]
CEdit doesn't like the first vent input

`&VENT TYPE = 'CEILING' ID = 'VVent 1 C=0.6' COMP_IDS = 'OUTSIDE', 'Comp 1' AREA = 3.426, SHAPE = 'SQUARE'  OFFSETS = 3.4, 17.7 /`

If you Eliminate the C=06 in the ID, it works fine.  We'll flag this as a bug and get it fixed. For now just avoid the "=" in text strings in CFAST input files.

**Comment by rpeacoc** [comment]
This drops an error in the input routine that interprets namelist input files. See fail at line 237 of NameListFile.vb. Check for fail on write as well.

**Comment by pimzzff1** [comment]
Thanks!
