### ISSUE TITLE
CFAST V6.1.1

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1399]
Have need for version 6.1.1 to update some work on an old project. I could only find version 6.0.10 and 6.2 available in the NIST CFAST archive. Can the install package for 6.1.1, including manuals, be made available?

**Comment by rpeacoc** [comment]
We should have it. I’ll search and post it ASAP

**Comment by rpeacoc** [comment]
6.1.1 should be available  at https://github.com/firemodels/cfast/releases
