### ISSUE TITLE
Trouble with simple leak test

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#1428]
I generated a simple leak test case using the new GUI 
```
&HEAD VERSION = 7300, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 3600 PRINT = 60 SMOKEVIEW = 15 SPREADSHEET = 15 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Material Properties 
&MATL ID = 'NM 1' MATERIAL = 'New Material 1', 
      CONDUCTIVITY = 0.16 DENSITY = 790 SPECIFIC_HEAT = 0.9, THICKNESS = 0.016 EMISSIVITY = 0.9 /
 
!! Compartments 
&COMP ID = 'Comp 1'
      DEPTH = 2.4 HEIGHT = 2.4 WIDTH = 3.6 CEILING_MATL_ID = 'NM 1' WALL_MATL_ID = 'NM 1' FLOOR_MATL_ID = 'NM 1'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 LEAK_AREA = 0, 1E-05 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_1' COMP_IDS = 'Comp 1', 'OUTSIDE'
      AREAS = 1, 1 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 0, 1.2 FILTER_TIME = 0 FILTER_EFFICIENCY = 0
```
The case did not run because the / was left off the `VENT` line. I suggest you fix this, plus put some kind of end line in the file like we do in FDS to force the GUI to read and write past the last actual input line.

Also, in this case, Smokeview draws the vents vertically, not horizontally.

Also, should the version be 7500?

**Comment by rpeacoc** [comment]
Version should be 7500.  I'll fix. Will add &TAIL / and fix vents.

I don't get vent showing vertical. Here's a smokeview grab

![Test_0051](https://user-images.githubusercontent.com/12814856/78596825-6fe54280-781a-11ea-86ab-87758ac91bcb.png)

**Comment by rpeacoc** [comment]
Here's newly generated and hopefully similar test case with a compartment, some leakage, and a mechanical vent.  CFAST runs with it. 

```
&HEAD VERSION = 7300, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 3600 PRINT = 60 SMOKEVIEW = 15 SPREADSHEET = 15 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Compartments 
&COMP ID = 'Comp 1'
      DEPTH = 2.4 HEIGHT = 2.4 WIDTH = 3.6 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 LEAK_AREA = 0, 0.0005 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_1' COMP_IDS = 'OUTSIDE', 'Comp 1'
      AREAS = 0.1, 0.1 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.02 CUTOFFS = 200, 300 OFFSETS = 1.2, 1.2 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 /
 
&TAIL /
```

**Comment by mcgratta** [comment]
Could be that my FDS Smokeview is older. Has Glenn fixed the vents recently?

**Comment by mcgratta** [comment]
I ran this case with the latest test release (7.5.0 626a368d)
```
&HEAD VERSION = 7500, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 3600 PRINT = 60 SMOKEVIEW = 15 SPREADSHEET = 15 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Material Properties 
&MATL ID = 'NM 1' MATERIAL = 'New Material 1', 
      CONDUCTIVITY = 0.16 DENSITY = 790 SPECIFIC_HEAT = 0.9, THICKNESS = 0.016 EMISSIVITY = 0.9 /
 
!! Compartments 
&COMP ID = 'Comp 1'
      DEPTH = 2.4 HEIGHT = 2.4 WIDTH = 3.6 CEILING_MATL_ID = 'NM 1' WALL_MATL_ID = 'NM 1' FLOOR_MATL_ID = 'NM 1'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 LEAK_AREA = 0, 0.01 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'Ceiling Vent' COMP_IDS = 'Comp 1', 'OUTSIDE'
      AREAS = 1, 1 HEIGHTS = 2.4, 2.4 ORIENTATIONS = 'HORIZONTAL', 'HORIZONTAL'  FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 1, 1.2 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 /
 
&TAIL /
```
The case runs, and the resulting pressure in the compartment is reported to be -1.63 Pa. But I would have expected the pressure to be -0.8 Pa. I specified a floor leak ratio of 0.01 m2/m2 (I think the input file should indicate `LEAK_AREA_RATIO`, not `LEAK_AREA`) and mechanical exhaust of 0.1 m3/s. I could not find the leak equation CFAST is using, but in FDS, we would have

.1 m3/s = 0.01*2.4*3.6 * sqrt(2 delta p / 1.2) 

p = -0.8 Pa

So...

1. Check my math
2. Add leak formula to CFAST Tech Ref and/or User's Guide
3. Edit leak section in Verification Guide. Put plots side by side to make it easier to read, and indicate in the narrative all inputs one needs to replicate results by hand.
4. LEAK_AREA_RATIO in the input file

**Comment by rpeacoc** [comment]
In CFAST, leaks are treated just as a "normal" wall vent placed at the floor (floor leaks) or on the wall (wall leaks). Size is calculated from specified leak area ratio with a height of 0.9 compartment height or 0.9 sqrt(floor area). I'll look at V&V section and inputs.

**Comment by mcgratta** [comment]
Does this mean that there is an orifice coefficient? If so, we should state this explicitly what the formula is. Even with an orifice coefficient, how is my calc 1/2 of the CFAST result? Shouldn't a "normal" CFAST vent act like an orifice?

**Comment by rpeacoc** [comment]
It uses the normal orifice coefficient of 0.68, not quite what Kline recommends from his data in the Smoke Control Handbook.

**Comment by rpeacoc** [comment]
I’ll add things to the manuals

**Comment by rpeacoc** [comment]
The flow is calculated from eq. 4.3 in the Tech Ref.  Looks like it's simple enough that we can just directly calculate what the pressure should be.  If the temperature goes up in the case, we'd have to also include the Ideal Gas Law effect too.  I'll work on it for the V&V Guide.

**Comment by mcgratta** [comment]
Leakage areas are calculated based on a particular form of the basic
Bernoulli equation. If one were to use one of the textbook leak area
ratios, one would assume it corresponds to a standard test using a standard
leakage formula. In the reference that you've cited, is there a formula we
can apply in CFAST?

>

**Comment by rpeacoc** [comment]
The difference between your FDS calculation and CFAST is the flow coefficient.  With FDS, it's vdot=A sqrt(2 DeltaP/rho). In CFAST, it's vdot = C A sqrt(2 DeltaP/rho).  When you solve for P, you get an extra 1/c^2 so that DeltaP becomes 0.9/0.7^2) = 1.63.

Thoughts on the use of the flow coefficient in this instance?

**Comment by mcgratta** [comment]
I think we need to find an authoritative reference with a formula used to
determine leak area.

**Comment by mcgratta** [comment]
I can't find any specific value that people use. I suggest you just be
explicit about the formula and coefficient.

**Comment by rpeacoc** [comment]
[Tech_Ref (Leakage).pdf](https://github.com/firemodels/cfast/files/4462967/Tech_Ref.Leakage.pdf)
[Validation_Guide (Leakage).pdf](https://github.com/firemodels/cfast/files/4462968/Validation_Guide.Leakage.pdf)

Klote's Smoke Control Handbook uses Bernoulli flow with a flow coefficient. Though he spends time worrying about details of the open areas around doors and windows, it's the same basic equation as we use in FDS and CFAST. All leakage areas assume a flow coefficient of 0.68.  Here's a couple updated pages from the CFAST manuals on leakage.  At the moment, they assume C = 0.7, but I can update that for leakage with a bit of code changes.

**Comment by mcgratta** [comment]
The Tech Ref paragraph needs a few commas here and there, plus there's a
unneeded capital L in FLow. Otherwise, looks good.

>
