### ISSUE TITLE
Smokeview not working

### ISSUE THREAD

**Issue by Jimenez1982** [firemodels/cfast#1437]
I have an issue with Smkeview, CFAST is calculating everything, I can see the spreadsheet results but the smokeview visualization does not show anything. 
I tried to resize the smokeview windows and it shows a black background, but the white area did not change. See the screenshots below . 

I also have tried to install other CFAST and Smokeview versions on my computer and I have the same problem. The strange thing is that it was working fine two weeks ago when I decided to install the new version, I believed that I had CFAST 7.3 and tried to install version 7.4.3 when this issue started. I tried to go back to version 7.3 but the result did not change. 

please could you help me solve this issue? 

I also tried to create a new file with just a simple compartment and I cannot even see the geometry in Smokeview. 

![image (1)](https://user-images.githubusercontent.com/63663366/79252256-edc2d280-7e46-11ea-81f6-f0c6a88aac2c.png)
![image](https://user-images.githubusercontent.com/63663366/79252257-ee5b6900-7e46-11ea-9618-ca7a38366458.png)

**Comment by rpeacoc** [comment]
Try installing the latest Smokeview here:

https://github.com/firemodels/smv/releases

If that doesn't work, can you upload your input file and let us know exactly what version of CFAST your are using.  You can find this in the .log file for the case you're running.

**Comment by Jimenez1982** [comment]
Thanks for your quick response. I already have SMV6.7.14. The first thing I did is installed the latest one. 
see below:
[CFAST file.zip](https://github.com/firemodels/cfast/files/4476975/CFAST.file.zip)

Release Version  : CFAST 7.3.0
Revision         : CFAST7.3.0-16-g31c2b8f5

**Comment by rpeacoc** [comment]
Smokeview doesn't work when compartments are not in the correct order in an input file.  Vents 2 and 3 in your input file need to have the compartments reversed (and you may need to adjust the Face and Vent Offset to get the visualization correct.  CFAST and smokeview expect the first compartment for a vent to be a "lower numbered" compartment in your list of compartments. You can see the order of the compartments in your input file or on the Compartments tab of CEdit
