### ISSUE TITLE
Mass/Energy Balance Issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [firemodels/cfast#145]
```
The attached test case gives different answers if compartment is run as a shaft 
versus run as a normal two zone model.  Since it is a closed, single 
compartment, shouldn't the answers be the same?

Answers change significantly if fire area is changed from 1.m^2 to 0.1 m^2.  
Again, there shouldn't be any change in mass/energy.
```

Original issue reported on code.google.com by `rpea...@gmail.com` on 9 Jun 2015 at 2:38

Attachments:
* [Little_Fire.in](https://storage.googleapis.com/google-code-attachments/cfast/issue-145/comment-0/Little_Fire.in)

**Comment by rpeacoc** [comment]
This case works correctly in version 7.  We'll close this issue.
