### ISSUE TITLE
V&V Files for older CFAST versions

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1467]
Can the verification and validation files for CFAST version 7.1.1 (or a pre-NAMELIST format version 7.x.x) be made available? We are trying to upgrade this CFAST version in our QA program, and it is preferred to obtain the files directly rather than back-convert the input to the older style.

**Comment by mcgratta** [comment]
It would be far better for all if you work with the latest version of everything. The whole point of re-running the V&V cases is to assure AHJs that the latest version of CFAST is the same or better than the older version. I would be more than happy to make this case to any of your regulatory authorities.

**Comment by drjfloyd** [comment]
Go to the release page and find the version you want. 

On the left side of the screen for that version will be a little tag symbol and a git hash. You can either 
-use git on your computer and pull that hash
-click on the tag and open a view of the repository for that specific tag. You can then click the clone or download button and select zip file.

**Comment by SPHunt** [comment]
Kevin, I agree newest version is the best. In our case we were constrained by a contract to work with the most current DOE toolbox version. It was not in our scope to update the CFAST version in the DOE toolbox and we did not budget for the holdups using a non-toolbox version. This scope was a safety related application, which is an upgrade in our QA program. It should be fairly easy to go with the newest version in our QA program at the going forward once we get the process ironed out for a back version.

Thanks, Sean

Sean Hunt
Jensen Hughes
207-399-9420

**Comment by rpeacoc** [comment]
Sean. Were you able to get the older V&V files per Jason's post above?
