### ISSUE TITLE
Problems with Smokeview & CFAST output

### ISSUE THREAD

**Issue by zetarock12** [firemodels/cfast#1520]
Hi everyone! I having problems using CFAST. First of all I can't open the Smokeview, eventhough I have the document in my desktop. The other problem is that in the output of the simulation appears the following message:

Log: ***Error exit from CFAST, error 1 from routine read_matl
Log: ***Error in &MATL: Invalid specification for inputs. Check &MATL input, 1

I attached the document. Can anybody help me?

[TFM2.zip](https://github.com/firemodels/cfast/files/4886855/TFM2.zip)

**Comment by rpeacoc** [comment]
The problem is that your computer is not set up correctly to run CFAST. CFAST requires the numeric format be set to US English (Where a period rather than a comma is used as the decimal separator in numbers. See this thread: https://groups.google.com/forum/#!topic/cfast/DN8QTTdKAAQ
