### ISSUE TITLE
Paralell cfast execution

### ISSUE THREAD

**Issue by tbmale** [firemodels/cfast#1527]
Hello,

  I have a strange problem, I'm using paralell.foreach with ProcessInfo for launching multiple cfast calculations (>100).
After the 10th thread I receive an AggregateException, each time.
If I use MaxDegreeOfParallelism  = 2 , in order to limit the concurrent threads, it works .
Is there some system wide locking done by cfast?

It is true, I haven't read all the source code before asking the question :)

**Comment by rpeacoc** [comment]
There’s no parallel processing in the CFAST code and there shouldn’t be any common files between runs. I don’t know of any system calls in CFAST that would prevent numerous jobs running at the same time. We’ve had 100s running at the same time on our cluster.

**Comment by tbmale** [comment]
Thank you!

It was me in fact... and my cfast.StandardError.ReadToEnd();/cfast.StandardOutput.ReadToEnd(); inside the thread.
Sorry.

**Comment by rpeacoc** [comment]
I'll close this one now.  We do have the source for a utility program in the repository now that will generated a Windows (and Linux) batch file to run all the CFAST files in the current directory in parallel.  It does depend on a couple utility programs from the FDS installation, but works quite easily once those are available. We've used it internally to run more than 100 000 runs on our Linux cluster.
