### ISSUE TITLE
Incorrect target heat flux

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/cfast#1533]
The attached file is a 15x10x5 compartment with a t^2 fire growing to 6 MW in 5 min with a 35 % radiative fraction.  The fire is at 2,5,0 and there is a target at 3,5,0 with a normal of -1,0,0 (pointed to the fire).  At 125 s the fire is 1 MW, the lower layer OD is zero, the upper layer is 54 C, and the walls are still near ambient. This means layer and wall radiative fluxes are near zero and the target is just seeing the radiative flux from the fire which according to Eq 5.31 should be 0.9 x 1000 kW x 0.35 / (4 x pi x 1 m x 1m) = 25.1 kW/m2. The value in the devices file at this time is 10.5 kW/m2

[cfast2.in.txt](https://github.com/firemodels/cfast/files/5024051/cfast2.in.txt)

**Comment by rpeacoc** [comment]
It looks like your calculation assumes the target is located directly horizontally from the fire. For the fire radiation calculation, CFAST assumes the point source is located at a height of 1/3 the fire height calculated by Heskestad's flame height calculation which will change with time. Thus, there's a cosine involved in the calculation. In addition, there is likely some absorption of the radiation by the layer which has both CO2 and water (assuming it's all going through the lower layer, there isn't soot as well). If you want to get in the weeds, the source code is in target.f90 somewhere near line 200.

**Comment by rpeacoc** [comment]
Also, if you use the -V option running the case, CFAST outputs more details of the target heat flux.

**Comment by drjfloyd** [comment]
Section 5.1.5 of the Tech Ref doesn't state that the radial distance is computed based on 1/3 of the flame height, and if I search the Tech Ref and the User's Guide for flame height or flux I don't find anyplace where this is mentioned. I think this is something that should be in the Tech Ref. If this applies to Eq 5.6, it should also be made clear there.

If I account for the COS based on flame height, then it appears to be working.

It also appears that runtime options have to be put after the file name and this is not mentioned explicitly in App D of the User Guide.

**Comment by rpeacoc** [comment]
We’ll add details to the User’s Guide. Didn’t realize that the file name had to be first(and I wrote the code a long time ago). I’ll fix and/or add to User’s Guide. Glad it agrees now.
