### ISSUE TITLE
Installation of CFAST v7.5.2 notes v7.5.0?

### ISSUE THREAD

**Issue by jeffro109** [firemodels/cfast#1571]
Hello,

When I install the "cfast_7.5.2_SMV_6.7.14.exe" file, the CEdit screen notes v7.5.0 as well as the 'about' screen notes v7.5.0 is installed.  Does the v7.5.2 file contain v7.5.2 or v7.5.0?

Thanks
Jeff

**Comment by rmcdermo** [comment]
Thanks, we will take a look.

**Comment by rpeacoc** [comment]
CEdit is version 7.5.0. The model itself, CFAST, is version 7.5.2. CEdit didn’t change with the bug fixes to CFAST in 7.5.1 and 7.5.2. You can verify this by running a case and looking at the .log file or viewing the output summary on the Simulation Environment page in CEdit.
