### ISSUE TITLE
Error in &COMP when run the example Multi.in

### ISSUE THREAD

**Issue by ffkz** [firemodels/cfast#1617]
Users_Guide_Example.in works well while examples in Validation such as Multi.in can not.  The errors are as follows. 
I appreciate your help. 

Log: ***Error exit from CFAST, error 1 from routine read_comp
Log: ***Error in &COMP: Invalid specification for inputs. Check &COMP input,   0
Log: 
Log: Compilation Date : Tue 06/09/2020  04:49 PM
Log: Revision Date    : Tue Jun 9 14:36:23 2020 -0400
Log: Revision         : CFAST7.5.0-151-ge3f5b88c
Log: Release Version  : CFAST 7.5.2
Log: 
Log: CFAST
Log:

**Comment by preneke** [comment]
The V & V files with the 7.5.2 release are for the next version of CFAST that we are working on which includes a few new entries in the namelists that won’t work. We have added a zip file to the installation that is just the *.in files from the V & V files. These should work with CFAST 7.5.2. You can get the zip here
https://github.com/firemodels/cfast/releases/download/CFAST7.5.2/CFAST_7.5_V.V_Files.zip

Thanks
Paul

**Comment by gforney** [comment]
To the original poster, can you tell me where you got the Multi.in test case.  If from the cfast repo, can you tell me what revision (type git describe --dirty --long in a command line)
thanks
glenn

**Comment by ffkz** [comment]
I got the Multi.in test from https://github.com/firemodels/cfast/tree/master/Validation/Multi.
The problem has been solved using *.in from https://github.com/firemodels/cfast/releases/download/CFAST7.5.2/CFAST_7.5_V.V_Files.zip

Thank you.

**Comment by rmcdermo** [comment]
I'm still confused as to what happened here.  If you got the input files from the repo, was the source for that commit consistent?  Where the bundled test cases inconsistent with the released source code?

**Comment by ffkz** [comment]
I got the latest input files from firemodels/cfast, and I downloaded the latest version of CFAST from https://pages.nist.gov/cfast/index.html. They were inconsistent. 
I didn't compile the source code.

**Comment by rpeacoc** [comment]
You are correct that they would be inconsistent. The current repository files are newer than the release version of CFAST. We’ve added new features for an upcoming release so the older release cannot read the newer input files. The ones we posted earlier for 7.5.1 at

https://github.com/firemodels/cfast/releases/download/CFAST7.5.2/CFAST_7.5_V.V_Files.zip

are the correct files for 7.5.2 as well.
