### ISSUE TITLE
Vent flows changed in VVent_Test.in verification case

### ISSUE THREAD

**Issue by SPHunt** [firemodels/cfast#1618]
The vent flow character changed completely for "Comp 2 Both" in the verification test case VVent_Test.in. This compartment has forced ventilation in middle compartment (0.12 kg/s), with expected flows to atmosphere split between the bottom and top compartments. Previously, this flow was about 0.074 kg/s out the top compartment ceiling opening, and 0.045 kg/s out the bottom compartment floor opening. This result was confirmed for CFAST V. 7.4.3. 

The flows for this compartment with CFAST V7.5.2 changed so that 0.27 kg/s flows into the bottom compartment from the floor vent, and 0.39 kg/s flows out of the top compartment ceiling vent, with 0.12 kg/s injected into the middle compartment via forced supply. 

Attaching VVent_Test.in case below. This file came from the CFAST 7.5.1 build as the 7.5.2 build seemed to have new parameters applicable to pending Version 7.6. 

&HEAD VERSION = 7300, TITLE = 'CFAST Simulation' /
 
!! Scenario Configuration 
&TIME SIMULATION = 900 PRINT = 50 SMOKEVIEW = 10 SPREADSHEET = 10 / 
&INIT PRESSURE = 101325 RELATIVE_HUMIDITY = 50 INTERIOR_TEMPERATURE = 20 EXTERIOR_TEMPERATURE = 20 /
&MISC  LOWER_OXYGEN_LIMIT = 0.15 / 
 
!! Compartments 
&COMP ID = 'Comp 1 Up'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 0, 0, 0 GRID = 50, 50, 50 /
&COMP ID = 'Comp 2 Up'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 0, 0, 5 GRID = 50, 50, 50 /
&COMP ID = 'Comp 3 Up'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 0, 0, 10 GRID = 50, 50, 50 /
&COMP ID = 'Comp 1 Down'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 7, 0, 0 GRID = 50, 50, 50 /
&COMP ID = 'Comp 2 Down'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 7, 0, 5 GRID = 50, 50, 50 /
&COMP ID = 'Comp 3 Down'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 7, 0, 10 GRID = 50, 50, 50 /
&COMP ID = 'Comp 1 Both'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 14, 0, 0 GRID = 50, 50, 50 /
&COMP ID = 'Comp 2 Both'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 14, 0, 5 GRID = 50, 50, 50 /
&COMP ID = 'Comp 3 Both'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 14, 0, 10 GRID = 50, 50, 50 /
&COMP ID = 'Comp 1 All Vents'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 21, 0, 0 GRID = 50, 50, 50 /
&COMP ID = 'Comp 2 All Vents'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 21, 0, 5 GRID = 50, 50, 50 /
&COMP ID = 'Comp 3 All Vents'
      DEPTH = 5 HEIGHT = 5 WIDTH = 5 CEILING_MATL_ID = 'OFF' WALL_MATL_ID = 'OFF' FLOOR_MATL_ID = 'OFF'
      ORIGIN = 21, 0, 10 GRID = 50, 50, 50 /
 
!! Wall Vents
&VENT TYPE = 'WALL' ID = 'WallVent_1' COMP_IDS = 'Comp 3 All Vents' 'OUTSIDE'  TOP = 2.75, BOTTOM = 2.25, WIDTH = 0.5
  CRITERION = 'TIME' T = 0, 0 F = 1, 1 FACE = 'FRONT' OFFSET = 2.25 /
 
!! Ceiling and Floor Vents 
&VENT TYPE = 'CEILING' ID = 'CeilFloorVent_1' COMP_IDS = 'OUTSIDE', 'Comp 3 Up' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_2' COMP_IDS = 'Comp 3 Up', 'Comp 2 Up' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_3' COMP_IDS = 'Comp 2 Up', 'Comp 1 Up' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_4' COMP_IDS = 'Comp 3 Down', 'Comp 2 Down' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_5' COMP_IDS = 'Comp 2 Down', 'Comp 1 Down' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_6' COMP_IDS = 'Comp 1 Down', 'OUTSIDE' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'CEILING' ID = 'CeilFloorVent_7' COMP_IDS = 'OUTSIDE', 'Comp 3 Both' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_8' COMP_IDS = 'Comp 3 Both', 'Comp 2 Both' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_9' COMP_IDS = 'Comp 2 Both', 'Comp 1 Both' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_10' COMP_IDS = 'Comp 1 Both', 'OUTSIDE' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_11' COMP_IDS = 'Comp 3 All Vents', 'Comp 2 All Vents' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
&VENT TYPE = 'FLOOR' ID = 'CeilFloorVent_12' COMP_IDS = 'Comp 2 All Vents', 'Comp 1 All Vents' AREA = 2, SHAPE = 'ROUND'  OFFSETS = 2.5, 2.5 /
 
!! Mechanical Vents
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_1' COMP_IDS = 'OUTSIDE', 'Comp 1 Up'
      AREAS = 0.25, 0.25 HEIGHTS = 2.5, 2.5 FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 0, 2.5 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_2' COMP_IDS = 'OUTSIDE', 'Comp 3 Down'
      AREAS = 0.25, 0.25 HEIGHTS = 12.5, 2.5 FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 2.5, 0 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_3' COMP_IDS = 'OUTSIDE', 'Comp 2 Both'
      AREAS = 0.25, 0.25 HEIGHTS = 7.5, 2.5 FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 2.5, 0 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 / 
&VENT TYPE = 'MECHANICAL' ID = 'MechanicalVent_4' COMP_IDS = 'OUTSIDE', 'Comp 1 All Vents'
      AREAS = 0.25, 0.25 HEIGHTS = 2.5, 2.5 FLOW = 0.1 CUTOFFS = 200, 300 OFFSETS = 2.5, 0 FILTER_TIME = 0 FILTER_EFFICIENCY = 0 /

**Comment by rpeacoc** [comment]
I'll take a look

**Comment by rpeacoc** [comment]
I'm a bit confused here. I've run the test case with all versions from 7.4.2 through 7.5.2 (with the 7.4.2 input file) and get the same results with all.  Here's the results from 7.4.3 followed by the results from 7.5.2. I agree that the results are strange and will continue to look, but I do get the same answers with any version.

From 7.4.3:


```
CFAST

Release Version  : CFAST 7.4.3
Revision         : CFAST7.4.3-8-g52b52db9
Revision Date    : Fri Nov 8 11:04:20 2019 -0500
Compilation Date : Fri 11/08/2019  12:48 PM

FLOW THROUGH VENTS (kg/s)

                                                    Flow relative to 'From'Flow Relative to 'To'
                                       Opening      Upper Layer               Lower Layer               Upper Layer               Lower Layer
Vent   From/Bottom    To/Top           Fraction     Inflow       Outflow      Inflow       Outflow      Inflow       Outflow      Inflow       Outflow
---------------------------------------------------------------------------------------------------------------------------------------------------------
H  1   Comp 3 All V   Outside          1.000                                                0.120        5.980E-02                 5.974E-02                                         
V  1   Comp 3 Up      Outside          1.000                                                0.120                                  0.120                                             
V  2   Comp 2 Up      Comp 3 Up        1.000                                                0.120                                  0.120                                             
V  3   Comp 1 Up      Comp 2 Up        1.000                                                0.120                                  0.120                                             
V  4   Comp 2 Down    Comp 3 Down      1.000                                   0.120                                                            0.120                                
V  5   Comp 1 Down    Comp 2 Down      1.000                                   0.120                                                            0.120                                
V  6   Outside        Comp 1 Down      1.000                                   0.120                                                            0.120                                
V  7   Comp 3 Both    Outside          1.000                                                0.390                                  0.390                                             
V  8   Comp 2 Both    Comp 3 Both      1.000                                                0.390                                  0.390                                             
V  9   Comp 1 Both    Comp 2 Both      1.000                                                0.270                                  0.270                                             
V 10   Outside        Comp 1 Both      1.000                                                0.270                                  0.270                                             
V 11   Comp 2 All V   Comp 3 All V     1.000                                                0.120                                  0.120                                             
V 12   Comp 1 All V   Comp 2 All V     1.000                                                0.120                                  0.120                                             
M  1   Outside        Comp 1 Up        1.000                                                0.120                                  0.120                                             
M  2   Outside        Comp 3 Down      1.000                                                0.120                                  0.120                                             
M  3   Outside        Comp 2 Both      1.000                                                0.120                                  0.120                                             
M  4   Outside        Comp 1 All V     1.000                                                0.120                                  0.120                                             


TOTAL MASS FLOW THROUGH MECHANICAL VENTS (kg)

To             Through              Upper Layer               Lower Layer              Trace Species
Compartment    Vent             Inflow       Outflow      Inflow       Outflow       Vented    Filtered
--------------------------------------------------------------------------------------------------------
  Outside      Comp 1 Up                                             108.                                                                                       
  Outside      Comp 3 Down                                           108.                                                                                       
  Outside      Comp 2 Both                                           108.                                                                                       
  Outside      Comp 1 All V                                          108.                                                                                       

```

From 7.5.2:

```
CFAST

Release Version  : CFAST 7.5.2
Revision         : CFAST7.5.0-151-ge3f5b88c
Revision Date    : Tue Jun 9 14:36:23 2020 -0400
Compilation Date : Tue 06/09/2020  04:49 PM


FLOW THROUGH VENTS (kg/s)

                                                    Flow relative to 'From'                             Flow Relative to 'To'
                                       Opening      Upper Layer               Lower Layer               Upper Layer               Lower Layer
Vent   From/Bottom    To/Top           Fraction     Inflow       Outflow      Inflow       Outflow      Inflow       Outflow      Inflow       Outflow
---------------------------------------------------------------------------------------------------------------------------------------------------------
H  1   Comp 3 All V   Outside          1.000                                                0.120        5.980E-02                 5.974E-02                                         
V  1   Comp 3 Up      Outside          1.000                                                0.120                                  0.120                                             
V  2   Comp 2 Up      Comp 3 Up        1.000                                                0.120                                  0.120                                             
V  3   Comp 1 Up      Comp 2 Up        1.000                                                0.120                                  0.120                                             
V  4   Comp 2 Down    Comp 3 Down      1.000                                   0.120                                                            0.120                                
V  5   Comp 1 Down    Comp 2 Down      1.000                                   0.120                                                            0.120                                
V  6   Outside        Comp 1 Down      1.000                                   0.120                                                            0.120                                
V  7   Comp 3 Both    Outside          1.000                                                0.390                                  0.390                                             
V  8   Comp 2 Both    Comp 3 Both      1.000                                                0.390                                  0.390                                             
V  9   Comp 1 Both    Comp 2 Both      1.000                                                0.270                                  0.270                                             
V 10   Outside        Comp 1 Both      1.000                                                0.270                                  0.270                                             
V 11   Comp 2 All V   Comp 3 All V     1.000                                                0.120                                  0.120                                             
V 12   Comp 1 All V   Comp 2 All V     1.000                                                0.120                                  0.120                                             
M  1   Outside        Comp 1 Up        1.000                                                0.120                                  0.120                                             
M  2   Outside        Comp 3 Down      1.000                                                0.120                                  0.120                                             
M  3   Outside        Comp 2 Both      1.000                                                0.120                                  0.120                                             
M  4   Outside        Comp 1 All V     1.000                                                0.120                                  0.120                                             


TOTAL MASS FLOW THROUGH MECHANICAL VENTS (kg)

To             Through              Upper Layer               Lower Layer              Trace Species
Compartment    Vent             Inflow       Outflow      Inflow       Outflow       Vented    Filtered
--------------------------------------------------------------------------------------------------------
  Outside      Comp 1 Up                                             108.                                                                                       
  Outside      Comp 3 Down                                           108.                                                                                       
  Outside      Comp 2 Both                                           108.                                                                                       
  Outside      Comp 1 All V                                          108.                                                                                       

```

**Comment by SPHunt** [comment]
I think that helps narrow the issue down. I was running the older syntax input file with Version 7.4.3 and the newer syntax file with 7.5.2. The issue might have something to do with the NAMELIST reader. Both input decks appear to define the same scenario. I did not try the older syntax with CFAST 7.5.2 as the format no longer seemed to be supported for that case.

CFAST

Release Version  : CFAST 7.4.3
Revision         : CFAST7.4.3-8-g52b52db9
Revision Date    : Fri Nov 8 11:04:20 2019 -0500
Compilation Date : Fri 11/08/2019  12:48 PM

Data file: C:\Working\Projects\OPG_QA\CFAST_SR\SVVP\SVVP_Runs\Verification\VerificationCase7\OLD\VVent_tests.in
Title: CFAST Simulation


FLOW THROUGH VENTS (kg/s)

                                                    Flow relative to 'From'Flow Relative to 'To'
                                       Opening      Upper Layer               Lower Layer               Upper Layer               Lower Layer
Vent   From/Bottom    To/Top           Fraction     Inflow       Outflow      Inflow       Outflow      Inflow       Outflow      Inflow       Outflow
---------------------------------------------------------------------------------------------------------------------------------------------------------
H  1   Comp 3 All V   Outside          1.000                                                0.120        5.981E-02                 5.973E-02                                         
V  1   Comp 3 Up      Outside          1.000                                                0.120                                  0.120                                             
V  2   Comp 2 Up      Comp 3 Up        1.000                                                0.120                                  0.120                                             
V  3   Comp 1 Up      Comp 2 Up        1.000                                                0.120                                  0.120                                             
V  4   Comp 2 Down    Comp 3 Down      1.000                                   0.120                                                            0.120                                
V  5   Comp 1 Down    Comp 2 Down      1.000                                   0.120                                                            0.120                                
V  6   Outside        Comp 1 Down      1.000                                   0.120                                                            0.120                                
V  7   Comp 3 Both    Outside          1.000                                                7.445E-02                              7.445E-02                                         
V  8   Comp 2 Both    Comp 3 Both      1.000                                                7.445E-02                              7.445E-02                                         
V  9   Comp 1 Both    Comp 2 Both      1.000                                   4.510E-02                                                        4.510E-02                            
V 10   Outside        Comp 1 Both      1.000                                   4.510E-02                                                        4.510E-02                            
V 11   Comp 2 All V   Comp 3 All V     1.000                                                0.120                                  0.120                                             
V 12   Comp 1 All V   Comp 2 All V     1.000                                                0.120                                  0.120                                             
M  1   Outside        Comp 1 Up        1.000                                                0.120                                  0.120                                             
M  2   Outside        Comp 3 Down      1.000                                                0.120                                  0.120                                             
M  3   Outside        Comp 2 Both      1.000                                                0.120                                  0.120                                             
M  4   Outside        Comp 1 All V     1.000                                                0.120                                  0.120

**Comment by SPHunt** [comment]
The .out lost its format in above. Second try:


[VVent_tests_TRIMMED.txt](https://github.com/firemodels/cfast/files/5418519/VVent_tests_TRIMMED.txt)

**Comment by SPHunt** [comment]
Rick, I think that helps narrow the issue down. I was running the older syntax input file with Version 7.4.3 and the newer syntax file with 7.5.2. The issue might have something to do with the NAMELIST reader. Both input decks appear to define the same scenario. I attached the older style input file. I did not try it with CFAST 7.5.2 as the old format no longer is working for this case.


[cid:image005.jpg@01D6A7C4.F4FFC600]

[cid:image006.jpg@01D6A7C4.F4FFC600]

**Comment by rpeacoc** [comment]
Yeah. It looks like something's not getting initialized correctly for the namelist input.  It even happens with no forcing ventilation if you have more than one compartment on top of another.. I'll take a look

**Comment by rpeacoc** [comment]
Can you post your spreadsheet input file for this case.  The one I have gives the same answer as the namelist input file using CFAST 7.4.3, so there's still something I'm not seeing.

**Comment by SPHunt** [comment]
VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Compartment keywords
!!
COMPA,Comp 1 Up,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
COMPA,Comp 2 Up,5,5,5,0,0,5,OFF,OFF,OFF,50,50,50
COMPA,Comp 3 Up,5,5,5,0,0,10,OFF,OFF,OFF,50,50,50
COMPA,Comp 1 Down,5,5,5,7,0,0,OFF,OFF,OFF,50,50,50
COMPA,Comp 2 Down,5,5,5,7,0,5,OFF,OFF,OFF,50,50,50
COMPA,Comp 3 Down,5,5,5,7,0,10,OFF,OFF,OFF,50,50,50
COMPA,Comp 1 Both,5,5,5,14,0,0,OFF,OFF,OFF,50,50,50
COMPA,Comp 2 Both,5,5,5,14,0,5,OFF,OFF,OFF,50,50,50
COMPA,Comp 3 Both,5,5,5,14,0,10,OFF,OFF,OFF,50,50,50
COMPA,Comp 1 All Vents,5,5,5,21,0,0,OFF,OFF,OFF,50,50,50
COMPA,Comp 2 All Vents,5,5,5,21,0,5,OFF,OFF,OFF,50,50,50
COMPA,Comp 3 All Vents,5,5,5,21,0,10,OFF,OFF,OFF,50,50,50
!!
!!Vent keywords
!!
HVENT,12,13,1,0.5,2.75,2.25,2.25,2,1
VVENT,13,3,0.25,2,1
VVENT,3,2,0.25,2,1
VVENT,2,1,0.25,2,1
VVENT,6,5,0.25,2,1
VVENT,5,4,0.25,2,1
VVENT,4,13,0.25,2,1
VVENT,13,9,0.25,2,1
VVENT,9,8,0.25,2,1
VVENT,8,7,0.25,2,1
VVENT,7,13,0.25,2,1
VVENT,12,11,0.25,2,1
VVENT,11,10,0.25,2,1
MVENT,13,1,1,V,2.5,0.25,V,2.5,0.25,0.1,200,300,1
MVENT,13,6,2,V,12.5,0.25,V,2.5,0.25,0.1,200,300,1
MVENT,13,8,3,V,7.5,0.25,V,2.5,0.25,0.1,200,300,1
MVENT,13,10,4,V,2.5,0.25,V,2.5,0.25,0.1,200,300,1

**Comment by SPHunt** [comment]
Here is the zip package with the executable used, and all of the outputs. Hopefully this drag-paste works. 

[VVent_Tests_V743_Results.zip](https://github.com/firemodels/cfast/files/5425516/VVent_Tests_V743_Results.zip)

**Comment by rpeacoc** [comment]
I found what's wrong.  At some point, the size of the vertical vents throughout the simulation changed from 0.25 m^2 in your original version to 2 m^2 in the namelist version. Changing the vent sizes back corrects the issue.  I've corrected the input file for the upcoming release of CFAST and will look to see how it got changed and why that change would effect the results so much. Thanks for finding this

**Comment by rpeacoc** [comment]
Here's the correct input file (with a .txt extension added to make GitHub happy.
[VVent_Tests.in.txt](https://github.com/firemodels/cfast/files/5429776/VVent_Tests.in.txt)

**Comment by SPHunt** [comment]
Thanks, that is interesting. The change in flow directions with the larger vent, and the resulting overall flow pattern is not intuitive. There might be an issue with large floor vents. I will try to pull together a simple FDS model of this geometry and see which directions FDS predicts for the flows

**Comment by rpeacoc** [comment]
It was changed to the incorrect version on 9/21/2016 in revision 59dd0763. No indication why the change was made. I suspect that it was an unintended change since the commit was fixing an issue with smokeview. In the interest of full disclosure, it was my fault.

**Comment by rpeacoc** [comment]
Thanks. I'd love to see the FDS result.

**Comment by rpeacoc** [comment]
The vent area does effect the possibility of bidirectional flow in vertical vents in the CFAST algorithm. Len Cooper's original experiments had vent sizes up to only 1 m^2 so we may be out of the range of viability with this one, but it seems an odd way to fail.

**Comment by rpeacoc** [comment]
We'll do a range of vent sizes in CFAST and see what it looks like. You don't even need the mechanical vent to see the effect, just multiple rooms stacked on one another.

**Comment by preneke** [comment]
You still haven’t told me what outputs you need.
