### ISSUE TITLE
Validation source files

### ISSUE THREAD

**Issue by mgalvan** [firemodels/cfast#1716]
Is there a way to find  the source cfast files used to simulate the  validation cases cited in the "validation guide", those sources should be very important to undestand the right use of cfast in custom cases.
Thanks for helping.
Mauro

**Comment by mcgratta** [comment]
[Here](https://github.com/firemodels/cfast/tree/master/Validation)

**Comment by mgalvan** [comment]
Dear Sir Mc.Grattan,
I thank you for your reply and help.
Best Regards

Mauro Galvan

Il giorno mar 12 gen 2021 alle ore 17:42 Kevin McGrattan <
notifications@github.com> ha scritto:
