### ISSUE TITLE
GUI says shaft is a double-zone model

### ISSUE THREAD

**Issue by Ruud82** [firemodels/cfast#1828]
![image](https://user-images.githubusercontent.com/80822932/111453901-58922300-8714-11eb-954f-5c9869a10916.png)

according to the user guide it is still a single zone

**Comment by rpeacoc** [comment]
The shaft is a small one-zone model. GUI text is wrong. We’ll fix it for the next release.

**Comment by rpeacoc** [comment]
Fixed in repo revision 7a1abc7.  Several months ago, we changed the GUI to use double precision rather than single precision for number storage internally.  A global change in the code from "single" to "double" caused the odd text. Thanks for finding this.
