### ISSUE TITLE
HRR and Temperature FDS versus CFAST

### ISSUE THREAD

**Issue by tcrato** [firemodels/cfast#1931]
Hello,

I am doing academic work to check the temperature differences in a room without sprinklers and with sprinklers.

The compartment is very simple (24,5m x 7,7m x 6,75m)  with 2 vents (3m square).
 I defined the average fire load (warehouse) and determined the HRR and the HRRPUA

![image](https://user-images.githubusercontent.com/89968133/131815628-18f93484-2088-4b7b-9814-05cfa54ac9aa.png)

When I run FDS the HRR is nothing like what was calculated theoretically.
![image](https://user-images.githubusercontent.com/89968133/131815813-99831fa3-222d-43d7-b56b-f62600b87223.png)

As well as the evolution of temperatures in the compartment, it has nothing to do with the evolution of temperatures when I do this simulation but using CFAST.

Would it be possible to indicate/clarify what I'm doing wrong
[SemSprinklers.txt](https://github.com/firemodels/cfast/files/7097591/SemSprinklers.txt)

Thank you for your help
Best Regards, 
Tiago

**Comment by drjfloyd** [comment]
In FDS:

You have specified an HRRPUA of 100,000 kW/m2 on 5 of the 6 sides of a 1 m x 1 m x 1m OBST. When the RAMP is 1, this will be a 500 MW fire.

You have no OPEN boundaries. 

Your domain is ~3000 m3. This is enough oxygen to release ~4 to 6 GJ before extinction occurs (exact value will depend on temperature). Over 400 s this is an average 10 to 15 MW which for a linear ramp would mean the fire going out once it reaches 20 to 30 MW which matches the results you saw.
