### ISSUE TITLE
Invalid specification for inputs

### ISSUE THREAD

**Issue by alsnjr** [firemodels/cfast#1958]
Hello, 
I'm using CEdit 7.7.1 and keep getting this Error: 

CFAST: CFAST exited with a non-zero exit code: 1 CFAST: 1 CFAST: ***Error in &MATL: Invalid specification for inputs. Check &MATL input, 1 Error on line 9 of the input file: &MATL ID = 'CONCRETE' MATERIAL = 'Concrete Normal Weight (6 in)', ***Error exit from CFAST, error 1 from routine read_matl ***Error in &MATL: Invalid specification for inputs. Check &MATL input, 1 Log: ***Error exit from CFAST, error 1 from routine read_matl Log: Error on line 9 of the input file: &MATL ID = 'CONCRETE' MATERIAL = 'Concrete Normal Weight (6 in)', Log: Log: Compilation Date : Wed 08/18/2021 04:50 PM Log: Revision Date : Wed Aug 18 15:06:53 2021 -0400 Log: Revision : CFAST7.7.1-2-g0b43aa83 Log: Release Version : CFAST 7.7.1 Log: Log: CFAST Log: 

Could you please help me to get rid of this? It's really urgent! Thank you!

**Comment by rpeacoc** [comment]
To see what's wrong, you'll need to post your input file for the simulation.

**Comment by alsnjr** [comment]
[C1Document.pdf](https://github.com/firemodels/cfast/files/8611821/C1Document.pdf)

**Comment by alsnjr** [comment]
@rpeacoc hope that's what you needed to solve my problem :)
