### ISSUE TITLE
Invalid specification for inputs 

### ISSUE THREAD

**Issue by alsnjr** [firemodels/cfast#1972]
Hello,
I'm using CEdit 7.7.1 and keep getting this Error:

CFAST: CFAST exited with a non-zero exit code: 1 CFAST: 1 CFAST: ***Error in &MATL: Invalid specification for inputs. Check &MATL input, 1 Error on line 9 of the input file: &MATL ID = 'CONCRETE' MATERIAL = 'Concrete Normal Weight (6 in)', ***Error exit from CFAST, error 1 from routine read_matl ***Error in &MATL: Invalid specification for inputs. Check &MATL input, 1 Log: ***Error exit from CFAST, error 1 from routine read_matl Log: Error on line 9 of the input file: &MATL ID = 'CONCRETE' MATERIAL = 'Concrete Normal Weight (6 in)', Log: Log: Compilation Date : Wed 08/18/2021 04:50 PM Log: Revision Date : Wed Aug 18 15:06:53 2021 -0400 Log: Revision : CFAST7.7.1-2-g0b43aa83 Log: Release Version : CFAST 7.7.1 Log: Log: CFAST Log:

Could you please help me to get rid of this? It's really urgent! Thank you

[C1Document.pdf](https://github.com/firemodels/cfast/files/8728577/C1Document.pdf)
!

**Comment by preneke** [comment]
The pdf you attached doesn't have any material defined. Can you attach a file with the material included? You can just add a txt file.

**Comment by alsnjr** [comment]
[Inout.txt](https://github.com/firemodels/cfast/files/8732457/Inout.txt)

**Comment by alsnjr** [comment]
What do you mean by "use CEdit to define my cas and material"?

**Comment by preneke** [comment]
CFAST only does the US version of numbers like this.

&MATL ID = 'HARDWOOD' MATERIAL = 'Wood, Hardwoods (oak, maple) (3/4 in)',
      CONDUCTIVITY = 0.16 DENSITY = 720 SPECIFIC_HEAT = 1.255, THICKNESS = 0.019 EMISSIVITY = 0.9 /

I mean if you use CEdit to create your case the output should be correct to fork with CFAST. You can compare the results with CEdit with your input file and maybe identify the issues.

**Comment by preneke** [comment]
Most likely, the error is related to your selection of an international numeric format. CFAST is designed to use the U.S. English numeric format that uses a period as the separator between the integer and fractional part of a number. Unfortunately, the software does not recognize the comma separator and treats the input 2,9 as two separate numbers. To solve the problem, users have simply set up a new user on the machine and set the regional options to "English (United States)" for that user in the "Regional and Language Options" Control Panel applet.

**Comment by preneke** [comment]
😊 Actually I am in the top two or three but I am not the actual best but thanks. Happy to help.

Good luck,
Paul
