### ISSUE TITLE
Unable to build documentation, template.sty is not in repository

### ISSUE THREAD

**Issue by jlconlin** [firemodels/cfast#1993]
I'm trying to build the documentation, specifically the Users Guide, but I think all documentation suffers from the same problem. I get an error (see below) that the `template.sty` file is missing. I've tried looking in older versions in the repository, but to no avail. 

```console
$ ./make_guide.sh
LaTeX errors detected:
! LaTeX Error: File `template.sty' not found.
!  ==> Fatal error occurred, no output PDF file produced!
Users_Guide build failed
```

**Comment by mcgratta** [comment]
I just compiled the CFAST User's Guide in our linux cluster, using that same `make_guide.sh` script. I'm using
```
[mcgratta@blaze Users_Guide]$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
```

**Comment by gforney** [comment]
we are using the texlive distribution

if you want to use the same distribution we use, google texlive install linux .

**Comment by jlconlin** [comment]
Hmmm. I use texlive on my Mac, which should be the same as on Linux. I'll try again and see what I come up with.
