### ISSUE TITLE
Compilation using make_cfast.bat and revision numbers

### ISSUE THREAD

**Issue by bralph-edin** [firemodels/cfast#200]
Hello

A minor comment. When compiling CFAST using the makefile, if `<git>\cmd` is not added to your environment variables, the Revision and Revision Date of cfast7_win_64.exe is not correctly populated, being left blank without an error or notification.

Maybe an error message could be printed for those not familiar with `make` syntax.

**Comment by gforney** [comment]
Start an issue repeating details below ( using git cfast issue tracker).
I'm out this week but will look at this when I get back

**Comment by gforney** [comment]
Never mind my comment . ( saw your comment as an email- didn't notice it was already an issue!)

**Comment by rpeacoc** [comment]
In order to populate the Revision and Revision date, you have to use the batch files for the appropriate hardware/compiler.  We've tested this to work for Intel Fortran, GNU Fortran on OS X and Linux.  If you still have problems, create a new issue with additional details.
