### ISSUE TITLE
compiling source with gfortran on OSX

### ISSUE THREAD

**Issue by mcb1** [firemodels/cfast#201]
When I run make_cfast.sh in gnu_osx/, I get the following:

Building gnu_osx
gfortran -c -O2 -fpp -DGITHASH_PP=\"GitV0-115-g50c11ef\" -DGITDATE_PP=\""Tue Aug 18 11:21:24 2015 -0400\"" -DBUILDDATE_PP=\""Aug 18, 2015  14:17:18\"" ../Source/prec.f90
gfortran: error: unrecognized command line option ‘-fpp’
make: *** [prec.o] Error 1

**Comment by mcb1** [comment]
I fixed this by changing the makefile variable on the FFLAGS line under gnu osx to $(GITINFOGNU)$.

**Comment by rpeacoc** [comment]
This should work in 9ea15c4
