### ISSUE TITLE
CFAST simulation of smoke movement in a high rise

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#2016]
[updating shaft 3 - 01B propene.zip](https://github.com/firemodels/cfast/files/10076638/updating.shaft.3.-.01B.propene.zip)

There are a couple of issues related to the attached case. It is a scale model representation of a 19 floor high rise. A fire starts on the second floor and the smoke travels down a hallway and up a stair shaft. The actual stairs are "scissored"; that is, there are two separate stairwells in the same vertical shaft. 

1. The pink vents appear as boxes rather than planes. Glenn has addressed this issue in the latest Smokeview.
2. The run time is fairly long, like 10 min. Can you suggest a reason for this.
3. Is there a way to show the zone "slice" planes in the x rather than y plane?
4. The warnings about compartment size seem unnecessary. Is there a reason to believe that Smokeview will not work for this model? It is based on a scale model of a real building. This scale model is about 5 m (15 ft) tall.

**Comment by mcgratta** [comment]
One other question --- I ran the above case and looked at the results in Smokeview. When I reopen the case later and hit "View", the Smokeview "zone" file is empty. Is this a feature or a bug?

**Comment by mcgratta** [comment]
Only if it is easy. Otherwise I would just suggest the user to change coords.

**Comment by rpeacoc** [comment]
Odd … I know I’ve done slice file displays in all three directionsSent from my iPhoneOn Nov 23, 2022, at 12:09 PM, Kevin McGrattan ***@***.***> wrote:﻿
Only if it is easy. Otherwise I would just suggest the user to change coords.

**Comment by gforney** [comment]
think this is the default data from .plt file

**Comment by gforney** [comment]
easier than a lot of other things I am doing.  I pushed up changes to let you select all 3 planes. 

note, rick can elaborate but we implemented slice files in cfast a while ago that lets you specify all 3 plane orientations.  and at least for temperature it incorporates values from the zone layers and the ceiling jet.  maybe the same for velocity, I don't remember

**Comment by mcgratta** [comment]
Paul or Rick -- do you know why this case is taking so long to run? The time step is down to 0.001 s.

**Comment by mcgratta** [comment]
I removed the fire and the case still crawls. There are no fans, fires, hvac, etc. Just 44 compartments. How long would expect a 600 s simulation to take?

**Comment by preneke** [comment]
Make compartments that are more three or more connections away as single zone. The two zone model is not great for rooms that aren't experiencing significant temperature differences. The distance away, i.e., the number of connections between the fire room and the room in consideration changes depending on the fire and geometry of the rooms but I have found that three connections is a good starting point. If you have rooms that have single zone rooms with significant temperature elevation change it to two zones and run again.

**Comment by mcgratta** [comment]
Thanks, Paul. That helps. To make the image below, here's what I did:
1. Follow this [link](https://pages.nist.gov/fds-smv/downloads.html) and go to the very bottom of the page. Get the latest FDS-SMV nightly bundle. Install it. What you want is the latest Smokeview that fixes the vent drawing for CFAST. The pink vents in Smokeview should be flat.
2. Change all compartments that make up the stairwell to "shaft" (one zone).
3. Change all hallways to "Corridor" under the Compartment tab. 
4. Cut a hole in the floor of the fire room to allow make up air. This would be like leakage and openings to other parts of the building. 
5. Allow gases in Stairwell B to escape out the roof, or somewhere. Currently, Stairwell B is clogged with absolutely no leakage or escape. This causes pressure issues.
6. When viewing the scene in Smokeview, load "Zone fire", and then under the "Show/Hide" tab, Zone, choose Vertical X rather than Vertical Y. 
7. Same tab, hide the velocity visualization in Smokeview. It is distracting.
8. Dialogs --> Data coloring --> reset temperature bounds from, say 20 to 50 C.
9. Show/Hide --> Color --> undo transparency.
10. Alt-v to display scene with isometric projection.

![image](https://user-images.githubusercontent.com/11333911/204366855-abd829e9-fb4d-42ba-92fa-2615fe613ef7.png)

**Comment by maattyygg** [comment]
[updating shaft 3 - 01B propene 12-6.zip](https://github.com/firemodels/cfast/files/10168024/updating.shaft.3.-.01B.propene.12-6.zip)

Hello. Thank you for your help and guidance in this model. 

This is the most updated file with the issue tracker changes applied. There is still an issue with running the file as it still won't run. The smoke view shows the model perfectly. 

I don't know if this has anything to do with the geometry of the building or the program not being set up correctly on my personal computer.

**Comment by mcgratta** [comment]
Paul, Glenn -- if I remove Compartment 2, I cannot look at the Geometry or run the case. Smokeview and CFAST both fail with an error I do not understand.
```
CFAST: CFAST exited with a non-zero exit code: 66
CFAST: forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source             
CFAST.exe          00007FF73F08441A  Unknown               Unknown  Unknown
CFAST.exe          00007FF73F03337D  Unknown               Unknown  Unknown
CFAST.exe          00007FF73F017C2A  NAMELIST_INPUT_RO         901  input_namelist.f90
CFAST.exe          00007FF73F010C7A  NAMELIST_INPUT_RO          66  input_namelist.f90
CFAST.exe          00007FF73F0275AD  INPUT_ROUTINES_mp          75  input.f90
CFAST.exe          00007FF73F02D7E4  MAIN__                     64  cfast.f90
CFAST.exe          00007FF73F0F07CE  Unknown               Unknown  Unknown
```

**Comment by mcgratta** [comment]
Is this a bug with CEdit or CFAST? That is, is the text input file that is created by the compartment removal corrupted?

**Comment by mcgratta** [comment]
When Compartment 2 is removed, many other things in the file are corrupted besides the DEVC coordinates. Vents are changed, for example.

**Comment by mcgratta** [comment]
[high_rise_model_01.zip](https://github.com/firemodels/cfast/files/10170145/high_rise_model_01.zip)
Try this case. You should adjust vent and compartment sizes. I just used 0.01 m2 for all. Make sure that there are flow paths through the hallways and vertical shafts. Nothing in the building is perfectly sealed. If this case runs for you, create an image similar to the one above.

**Comment by mcgratta** [comment]
BTW, if you want to remove a compartment, do not use the CFAST graphical interface. Rather, open the .in file using Notepad or Wordpad and remove the compartment and any associated vents by hand.
