### ISSUE TITLE
Problem with vent flow graphic in Smokeview

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#2026]
[high_rise_model_01_grace_1.04_most accurate.in.txt](https://github.com/firemodels/cfast/files/10736258/high_rise_model_01_grace_1.04_most.accurate.in.txt)
Run this case and open in Smokview. Load the "Zone" file and look at the direction of the flow entering the lowest compartment and exiting the uppermost compartment. It appears that the flow into the lower compartment is the wrong direction, possibly because of confusion in the labelling of flow direction in the vent output file. Also, the initial value of the vent flows top and bottom appear to be larger than the values in the vent file.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
vertical vent elevations were output in reverse order in some cases (zmax zmin when it should have been zmin zmax).  probabably didn't fix all the problems but update your repo rerun the case and let me know where we're at

**Comment by gforney** [comment]
update cfast repo (where the fix was)

**Comment by gforney** [comment]
update your cfast repo, build cfast and rerun the case.  paul made a fix, the wrong pressures were being output.

**Comment by mcgratta** [comment]
OK, it works properly now. Thanks.
