### ISSUE TITLE
CFAST PROBLEM IN Fine input

### ISSUE THREAD

**Issue by marcoaldeg** [firemodels/cfast#2038]
Goodmorning,

I'm a new user of CFAST. I have some problems in inputing the file in the compartment Sheet.
I'm creating a non adiabatic thermal problem.
In the lower part of the window, where i have to enter cieling wall and floor thickness linking to the materia defined in in previous sheet "Thermal properties", the software does not recognize the input. For example, if I insert 0.20m for the wall thickness, the software defines it as 0m.
I tryed also to write 0,20 insteand 0.20 (with comma "," instead of dot ".") but I'm having the same problem. 
Than if i save the project, i can't open again because the sw gives the error in attachment,

I'm a european user, so i'm using the EU keybord setting on the PC.
Are there any special setting to check for EU users?
Does anyone have suggestion?
![1](https://user-images.githubusercontent.com/126070055/220602256-520e3cce-5dcf-41ba-8648-629e2b5067ff.JPG)
![2](https://user-images.githubusercontent.com/126070055/220602262-3bda3bd4-2590-4244-8ebc-fd042a745941.JPG)

Attacking some screen of the software.  
Thanks for any suggestion,

Marco

**Comment by preneke** [comment]
Step one) you have to use the American settings for the keyboard. CFAST doesn't recognize the EU settings. Numbers must have a . and not a , and so forth. Sorry about that.

**Comment by marcoaldeg** [comment]
Thanks
