### ISSUE TITLE
Validation output in CFAST

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#2046]
I have some questions about the validation output in CFAST.  My group is currently running CFAST 7.6.0 as or V&V’d version, but I have also noted these same behaviors in the current release of CFAST 7.7.4.

Per the User Guide (pg. 44, in either version), if validation output is checked, the program is directed to output abbreviated headings for the spreadsheet outputs.  So far, I have not noticed any of the spreadsheet column headings changing when the validation output it turned on or off.  Is that still a feature of the program?

There was a discussion in the CFAST users group back on Jul 12, 2019 about the validation output option, it mentioned that the net heat flux output was modified to be consistent with water cooled gauges.  Checking the “Target Net Flux” column with validation output on and off, I notice no difference between the 2 net fluxes (other than the additional 6 digits added to the number in validation mode).  This is the same for both 7.6.0 and 7.7.4.  It looks like that older discussion was for CFAST 7.3.1.  Since then to versions 7.6.0 – 7.7.4, was there a change made to what the validation output box effectively does to the results?  I do note that there is the separate “Target Total Gauge Flux” column included with the validation outputs, is that was being referred to in the discussion?

Ultimately, we are trying to answer the question of whether or not validation output should be left on when running analyses beyond just V&V cases.  Are there any other changes that turning on validation output makes to the program and its outputs that could affect results or cause them to differ from cases where validation output is off?  Similar to what was discussed in the older users group question, the User Guide doesn’t say much.  Our current stance is that it should be left off when performing calculations.  But having the additional information it adds to the devices output sheet (particularly for the breakdown of fluxes contributing to the incident and net flux) has been helpful information for some cases we are looking at.

I also had a strange issue show up as I was doing a few tests this morning with and without validation output, where checking or unchecking the box in the cEdit GUI made no effect on the spreadsheet output at all.  I tried restarting and using new input files several times, both with CFAST 7.6.0 and 7.7.4, and it always had the validation output on.  This was a new occurrence, as I was able to change this and see the expected outputs a few days ago but using only the GUI.  Is there something known that could cause the program to hang up like this and not take changes made in the GUI and apply them to the run?  I had to run using the command prompt to get around this issue and get the program to show results without validation output.

Any help or info is appreciated, thanks!

Joel Lederfind

**Comment by mcgratta** [comment]
Could you post the input file that you are referring to so that we can be on the same page.

**Comment by mcgratta** [comment]
I also do not see how checking the `Validation Output` box changes the input file. I looked through the CFAST User's Guide, and  the last line of the last page reads
```
-v - validation output (outputs a modified set of spreadsheet files with different column headers
designed to facilitate automated analysis of the output)
```
I then looked at some of the scripts that run the validation cases when the guides are compiled. I see something like  this
```
cfast.exe Test_02 -V
```
I don't know if the capital V and the small v do the same thing. I'll look into this more. For now, could you try running a case from the command line and add the -v or -V option, whichever one seems to work.

**Comment by jlederfind** [comment]
Here are the input files I was using.  There are 2 each for version 7.6.0 and 7.7.4.  I was truing to see if checking the box changed the input file, but like you mentioned it didn’t appear to.  Had to do that in the command line.

When running the 7.6.0 case with the command line, using both -v and -V seemed to do the same thing, turning on validation output for the case.  The same for the 7.7.4 case. 

 
[VAL_test_760.txt](https://github.com/firemodels/cfast/files/11396742/VAL_test_760.txt)
[VAL_test_774.txt](https://github.com/firemodels/cfast/files/11396743/VAL_test_774.txt)
[NO-VAL_test_760.txt](https://github.com/firemodels/cfast/files/11396744/NO-VAL_test_760.txt)
[NO-VAL_test_774.txt](https://github.com/firemodels/cfast/files/11396745/NO-VAL_test_774.txt)

(Had to do .txt files, github wouldnt let me upload a .in,  I could do a zipped folder if needed.

**Comment by preneke** [comment]
There have been a few changes that will be included in the users guide and I will address them here. One change is that the top row used to just be included in the validation output but now is always included. The names are unique and intended for computer programs to read more easily, instead of having to combine three other rows of information. The two things that still happen are that rows are added to the output, one example is the "Gage flux" columns that are meant to better represent what is measured in actual experiments in the device.csv. Second is a much higher precision in the numerical output to avoid rounding errors and better match experimental data. The validation check box does work, but only certain files have additional columns. 

This was checked with the latest distribution of CFAST. There are some changes from earlier versions.
