### ISSUE TITLE
Implicit cylindrical targets cause CFAST to crash

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#205]
At the moment, cylindrical targets must be specified as EXPLICIT rather than the default IMPLICIT.  Short term fix is to just set this in the input routine (see line 689 of input.f90). In the longer term, we should fix the problem which occurs because in the initial solution, dt for cylindrical targets is set to zero.  We then divide by dt as part of the cylindrical calculation (see lines 64-65 of cyl_conduct.f90). Glenn can decide the correct fix for this issue.

Test input:

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,100,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
!!
!!Compartment keywords
!!
COMPA,Room_1,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
ONEZ,1
!!
!!Vent keywords
!!
HVENT,1,2,1,1,2,0,5,1,1
!!
!!Target and detector keywords
!!
TARGET,1,3,3,3,-0.1622214,-0.1622214,-0.9733285,GYPSUM,IMPLICIT,CYL,0.5,Targ 1

**Comment by gforney** [comment]
when dt=0, the routine should just return the temperature profile that was passed in ie no heat conduction occurs.  The routine cylindrical_conductive_flux now checks if dt==0.0 and if so returns without updating the inputted temperature profile.

rick - you should be able to remove the XPLICIT override in input.f90

**Comment by rpeacoc** [comment]
I removed the forced EXPLICIT for cylindrical targets in 6614e6eb745d407c6e276cc3f28814a7e58e76f2 . Now, an implicit cylindrical target yields a DASSL error.  Simple case with only a target that fails with IMPLICIT and runs fine with EXPLICIT:

VERSN,7,CFAST Simulation
TIMES,80000,40000,1000,1000
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
COMPA,Room_1,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
TARGET,1,3,3,3,-0.1622214,-0.1622214,-0.9733285,GYPSUM,IMPLICIT,CYL,0.5,Targ 2

**Comment by rpeacoc** [comment]
We've made all targets explicit so this is no longer an issue
