### ISSUE TITLE
Visualisation of smoke in smokeview

### ISSUE THREAD

**Issue by azr3475** [firemodels/cfast#2054]
dear all, 
I want to visualise smoke from cfast simulations in smokeview. The cfast user guide shows pictures with smoke in SMV (figure 9.2), but I cannot find how to do this. I have lastest cfast and smv installed and visualisation of smoke from fds does work okay.

**Comment by gforney** [comment]
Select the menu item
Show/Hide>Zone>Smoke
after loading the 'Zone fire' data

**Comment by gforney** [comment]
I'm going to close the issue.  let me know if this did not solve the problem
