### ISSUE TITLE
Mechanical Flow Vents

### ISSUE THREAD

**Issue by dmmcmahon-lanl** [firemodels/cfast#2057]
Hi,
I am attempting to add mechanical ventilation to a compartment that is 3.9 m wide (X) by 10.5 m deep (Y) by 4 m high (z). 

For this project I am required to use CFAST 7.1.1 because of a government requirement.

I added a horizontal vent from outside into the compartment at compartment height, but it appears outside the compartment when I click View. Any idea why? I haven't had this problems with other models I've built. 

I also added a vertical vent from the compartment to the outside with center height at 3 m and area 1 m and its fine. Thanks, David

![Mechanical Vents](https://github.com/firemodels/cfast/assets/135063016/b8fbf70b-74e3-47de-a08e-987b2377b919)

**Comment by rmcdermo** [comment]
Thanks for the report.  Is it possible to send the input files?

**Comment by dmmcmahon-lanl** [comment]
[Room 124 Fire.zip](https://github.com/firemodels/cfast/files/12044542/Room.124.Fire.zip)

Here it is, thanks

**Comment by preneke** [comment]
I will take a look but this could take a while. I have not done anything with 7.1.1 especially the input files for a while.  

I don't see anything obvious. Do you have any reason to believe the simulation is wrong? The placement of the vents in SmokeView does not impact the calculations CFAST makes.

**Comment by mcgratta** [comment]
Just a note -- we cannot maintain older versions of CFAST. If we find a bug related to your case in the old version, we would not "fix" the old version. We would ask you to run the latest. If you get push back from "the government", please have them contact us. The latest version of CFAST passed the same build tests as your version, but your version has known bugs which is why there are later versions. So your version is by definition less reliable than the latest version.

**Comment by dmmcmahon-lanl** [comment]
Thanks -  I understand you can't maintain older versions. We are forced to use 7.1.1 by Department of Energy order. Of course I would much prefer to use the most recent version of CFAST but getting the Department of Energy to change their policy will literally take years. 

https://www.energy.gov/ehss/cfast

**Comment by rmcdermo** [comment]
@dmmcmahon-lanl @preneke

Is this issue resolved?  OK, we cannot fix a bug, but are we all on the same page with what v7.1.1 is doing?  Are inputs correct, etc.?  Could this be a smokeview or CEdit issue?  Now that we have separated the input namelist and CEdit, could DOE accept a fix to CEdit that worked with CFAST 7.1.1?
