### ISSUE TITLE
Elevated Fire in CFAST Quickly Chokes

### ISSUE THREAD

**Issue by dmmcmahon-lanl** [firemodels/cfast#2058]
I am working on a room with t-squared fires taking place at different elevations. 

When the fire is elevated at approximately half the height of the room or higher, the fires quickly choke off. Lower elevation fires last for the entire simulation. Since the fires quickly choke I am able to run pretty large fires with the ULT peaking at around the same value of 250 degrees C. 

Is this to be expected? 

One thing I noticed was at the elevations where choking starts to occur, the upper layer descends below the elevation of the fire. So my hypothesis was there isn't enough oxygen where the fire is for it to continue.

Any input or comments appreciated.

**Comment by mcgratta** [comment]
This is the result of the assumptions built into CFAST. When the smoke layer descends to the base of the fire, oxygen-depleted exhaust products are entrained. At some point, the fire drops below the lower oxygen limit and dies.

In reality, it is more difficult to say. A relatively small fire will just choke itself off, like a candle in a bottle. However a large fire may be partially suppressed but it will still vaporize fuel gases whose concentration may grow to a point where you have a burning upper layer. Depends on room size and layer temperature. 

You could try running FDS for these scenarios, but even then, it is a challenge. But you may get more insight. If you are doing a hazard analysis, you may not be able to rely completely on either model. You would want to see if there are experiments to confirm the model conclusions.

**Comment by dmmcmahon-lanl** [comment]
Thanks. The room is about 4 m x 6.1 m with a ceiling height of 4.4 m.

**Comment by mcgratta** [comment]
If the fire is ventilated and fuel gases continue to be generated even after the layer descends, you could create a hot, well-mixed layer. If it falls within flammability limits, you could have something akin to a flashover. CFAST is probably not going to tell you this, so use with caution.
