### ISSUE TITLE
CFAST 7.7.4 fails on Slice File Write

### ISSUE THREAD

**Issue by firemist** [firemodels/cfast#2102]
Running an input file with slice files caused an error and crash, see below. Smokeview was not running and no other program had these files open. It appears as though somewhere these files may have been closed and reopened as readonly?

I originally thought this was happening because the file had been previously run and the slice files already existed in the directory. I then deleted all previous files other than the input (.in) file and reran the model. It still crashed.

This crash came at the end of the run. In other words, the simulation time had been met, so it's not clear why it crashed at this point. Is there a close and re-open operation at the end of the run? In a previous run, I thought this occurred during the run and not at the end of the simulation time.

Version information (cfast run w/no arguments):
CFAST

Release Version  : CFAST 7.7.3
Revision         : CFAST7.7.4-0-g6b52d0c3
Revision Date    : Fri Jan 13 15:42:10 2023 -0500
Compilation Date : Thu 01/19/2023  11:24 AM

Normal exit from CFAST

Error:
CFAST: CFAST exited with a non-zero exit code: 47
CFAST: forrtl: severe (47): write to READONLY file, unit 7245, file Y:\[...excerpted...]\mod_11\mod_11_0020.sf
Image              PC                Routine            Line        Source             
CFAST.exe          00007FF63286C827  Unknown               Unknown  Unknown
CFAST.exe          00007FF6328486FA  Unknown               Unknown  Unknown
CFAST.exe          00007FF63279F986  SMOKEVIEW_ROUTINE         527  outputsmv.f90
CFAST.exe          00007FF6327DE39F  SOLVE_ROUTINES_mp         453  solve.f90
CFAST.exe          00007FF63280EA00  MAIN__                     78  cfast.f90
CFAST.exe          00007FF6328DC90E  Unknown               Unknown  Unknown
CFAST.exe          00007FF6328DCCF0  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFCBCFE7344  Unknown               Unknown  Unknown
ntdll.dll          00007FFCBDE826B1  Unknown               Unknown  Unknown

Thanks for working on this code.

**Comment by firemist** [comment]
Upon further testing in order to prepare this upload:
This happens ONLY on my networked drive and not on my local drive. I ran this exact file locally, to check that everything was OK, and it ran correctly without difficulty and without error. I re-ran it to see if it would error and it did not.

So, then I thought maybe this only occurs on the network drive. So, I copied it up there and re-ran it. I'm running in a Windows environment and the networked drive is mapped to a logical drive letter (Y), as shown above.

I don't understand what the difference would be given the same drive access structure. I have full permissions on the drive and other programs read and write to this drive all the time. Also, smokeview reads from and writes to this drive without any problems or errors.

I've attached the file for your review. I have changed the .in extension to .txt for upload purposes.

Thank you for looking at this.

[test_01.txt](https://github.com/firemodels/cfast/files/14623709/test_01.txt)

**Comment by drjfloyd** [comment]
Would recommend not running on a network drive. Network latency, how files are bufferred, how Windows locks files, etc. can cause unexpected behavior when it comes time for a file write.

**Comment by preneke** [comment]
I ran the file an it does work on a PC as you said. I don't really know that much about network file protocols but I can say that CFAST doesn't know about them or do anything different because of network drives, which may be the problem. All I can suggest is running the file locally and if you need the space copy the results to the network file. It is not ideal but it is a workable solution.

**Comment by firemist** [comment]
That's certainly a workable solution. Thanks for your work.
