### ISSUE TITLE
CEDIT 7.7.4 error adding default output with US Customary length units

### ISSUE THREAD

**Issue by firemist** [firemodels/cfast#2103]
Error steps description:
1. I have a model setup with no explicit outputs (so just the automatic zone outputs)
2. Switch engineering length unit to feet
3. Go to Output tab
4. Click on Add Defaults (empty table now propagated with values)
5. Save file
6. Click Run button
7. Get below error

Analysis:
I checked the input file. CEDIT wrote out the input file directly without performing units conversion. The displayed feet values for where the slices appear, were written into the .in file without having been converted to SI units. Therefore, since the default button puts all of the slices into the middle of the compartments, all of the requested slice locations ended up outside the respective compartments. 

So, I have an 8' wide room, so the slice (by default) went at 4'. However, that was actually written into the input file with POSITION = 4. However, 4 m is outside the 8' room, so CFAST generated an error and a STOP.

Please ask for clarification, if this doesn't make sense. 

Version info:
![image](https://github.com/firemodels/cfast/assets/25644607/32677061-03c8-4d34-96f1-316fab7c3a3b)

Error info:
CFAST: CFAST exited with a non-zero exit code: 1
CFAST: 1

CFAST: ***Error, Bad SLCF input. Invalid SLCF specification in visualization input 31                                                  
Error on line 176 of the input file: &SLCF COMP_ID = 'turtle_room' DOMAIN = '2-D'  POSITION = 4, PLANE = 'X' /
***Error exit from CFAST, error 4 from routine read_slcf
***Error, Bad SLCF input. Invalid SLCF specification in visualization input 31                                                  

Log: ***Error exit from CFAST, error 4 from routine read_slcf
Log: Error on line 176 of the input file: &SLCF COMP_ID = 'turtle_room' DOMAIN = '2-D'  POSITION = 4, PLANE = 'X' /
Log: 
Log: Compilation Date : Thu 01/19/2023  11:24 AM
Log: Revision Date    : Fri Jan 13 15:42:10 2023 -0500
Log: Revision         : CFAST7.7.4-0-g6b52d0c3
Log: Release Version  : CFAST 7.7.3
Log: 
Log: CFAST

Thank you for checking into this issue.

**Comment by firemist** [comment]
I believe there may be other conversion errors as well. In particular, in the area of thermal materials entry. I think there's an issue with k, rho, C. It seemed like the values may have been changing in the file. I had not posted that yet, because I had not yet had time to isolate the issue and confirm it. However, since you may be looking at unit conversions based on the above, I thought it best to add this note about it. Thanks.

**Comment by preneke** [comment]
Can you include the input file you were using?

**Comment by rpeacoc** [comment]
Fixed the missing length conversion for the Add Defaults visualizations in [46fdb50](https://github.com/firemodels/cfast/commit/46fdb50578bac5d22d483721093b04f85e60ad97). Thermal properties not addressed yet.

**Comment by rpeacoc** [comment]
> I believe there may be other conversion errors as well. In particular, in the area of thermal materials entry.

I'm not able to replicate an issue with the thermal properties.  It seems to switch back and forth between English and S.I. units. I'll leave this one open in case you find a specific test case or set of actions that demonstrate the failure.

**Comment by firemist** [comment]
I will try to recreate what I thought happened this weekend. If I can't do it, I'll close it. Thanks for working on it.

On Mar 20, 2024 2:32 PM, Richard Peacock ***@***.***> wrote:

I believe there may be other conversion errors as well. In particular, in the area of thermal materials entry.

I'm not able to replicate an issue with the thermal properties. It seems to switch back and forth between English and S.I. units. I'll leave this one open in case you find a specific test case or set of actions that demonstrate the failure.

**Comment by preneke** [comment]
firemist,

Have you had a chance to see if you can recreate the units issue with thermal properties? Just checking in.

**Comment by preneke** [comment]
firemist,

Have you had a chance to see if you can recreate the units issue with thermal properties in CEdit? We will assume that there isn't a problem if we don't hear from you by May 6th. Obviously, you can open a new issue if you find the problem after May 6th. Thanks for reporting this issue, it is very helpful.
