### ISSUE TITLE
System.InvalidCastException: Conversion from string "  76.     " to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by rynovanwyk** [firemodels/cfast#2112]
Hi, I've tried to run the example files, but I am continuously prompted with this error:

![Screenshot 2024-06-02 182511](https://github.com/firemodels/cfast/assets/91536100/95e95f91-7175-4283-9e36-76b25d95693f)

I've tried different computers, I've checked that the input data uses dots (".") as decimals and not commas (",").

Can someone please advise to fix this issue.

Regards

**Comment by preneke** [comment]
Sorry for the delay. I didn't see this till today even though it says it is 4 days old. Can you give me more information. You are trying to run Users_Guide_Example.in. What version of windows are you running.

**Comment by preneke** [comment]
Can you include the input file you are running? I understand you have checked about formats but it seems clear something is wrong. Also where in the world are you, seeing as you checked about formats.

**Comment by preneke** [comment]
rynovanwyk are you still interested in this issue or can I just close it.

**Comment by rynovanwyk** [comment]
You can close it.
