### ISSUE TITLE
Beginner's question

### ISSUE THREAD

**Issue by Ronnie-Henry** [firemodels/cfast#2123]
Hello everyone,
I would like to ask you a basic question.
How do I put a table (that will start the fire) in the program? Could you recommend some literature?

**Comment by mcgratta** [comment]
You do not add a table explicitly, but rather the heat release rate time history of the table.

**Comment by tGagnonCorvid** [comment]
If you want to specify fires outside of the CEdit interface you could manually or with the help of a script generate each data point for the HRR curve and import that as a cfast.in file. 

For example, the following text within a *.in file was generated by a python script of mine to approximate a fuel pool fire

!! Fires 
&FIRE ID = 'FIRE_COMP1005_FVC16'  COMP_ID = '1005', FIRE_ID = 'FIRE_FVC16_8MW_Oil_L'  LOCATION = 0.5, 0.5 IGNITION_CRITERION = 'TIME', SETPOINT = 0 / 
&CHEM ID = 'FIRE_FVC16_8MW_Oil_L' CARBON = 1 CHLORINE = 0 HYDROGEN = 1 NITROGEN = 0 OXYGEN = 0 HEAT_OF_COMBUSTION = 46000 RADIATIVE_FRACTION = 0.2051 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L' LABELS = 'TIME', 'HRR', 'HEIGHT', 'AREA', 'CO_YIELD', 'SOOT_YIELD', 'HCN_YIELD', 'HCL_YIELD', 'TRACE_YIELD'  /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 0.0, 0, 0, 0.0, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 25.0, 8286, 0, 6.3, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 50.0, 6290, 0, 5.0, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 75.0, 4532, 0, 3.8, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 100.0, 3302, 0, 2.9, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 125.0, 2435, 0, 2.3, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 150.0, 1820, 0, 1.8, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 175.0, 1378, 0, 1.5, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 200.0, 1058, 0, 1.2, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 225.0, 822, 0, 1.0, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 250.0, 647, 0, 0.8, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 275.0, 516, 0, 0.7, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 300.0, 415, 0, 0.6, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 325.0, 338, 0, 0.5, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 350.0, 278, 0, 0.4, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 375.0, 230, 0, 0.4, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 400.0, 193, 0, 0.3, 0, 0, 0, 0, 0 /
&TABL ID = 'FIRE_FVC16_8MW_Oil_L',  DATA = 800.0, 193, 0, 0.3, 0, 0, 0, 0, 0 /

It is a pretty simple exercise to format the output of time history data for CFAST with something such as a python script.
