### ISSUE TITLE
CFAST will not save new material data

### ISSUE THREAD

**Issue by jeffro109** [firemodels/cfast#2129]
Using CFAST 7.7.4, I suddenly cannot add a new material in the Thermal Properties screen. I can edit an existing material from my prior evaluation/model. When I attempt to add a new material the information is on the screen, I then save the file, close/open the file and the new material is gone from the screen.

Any ideas?

**Comment by rpeacoc** [comment]
CEdit only saves materials that are actually used in a test case so the material needs to be assigned to a compartment surface, target, and such before the file is saved.

**Comment by preneke** [comment]
No interaction
