### ISSUE TITLE
CFAST does not run

### ISSUE THREAD

**Issue by ozrahse** [firemodels/cfast#2130]
Hello
I have a problem using the software.
After defining the third detector, in normal run I get an error message that says:
"index and length parameter should be in the string. parameter name: length"
i have no idea what is the problem.

**Comment by preneke** [comment]
Are you using CEdit? If not and it is possible I would suggest using CEdit and looking at the *.in file to see the correct format. If you are not using CEdit, which seems likely, can you upload the file so we can take a look at it.

**Comment by ozrahse** [comment]
No, I don't use it
This can be a good option.
I even used the one-zone model for compartments that are away from the fire source, but the problem still persisted.
This file contains the modeling of one floor of a high-rise hospital.
thanks
[hospital.zip](https://github.com/user-attachments/files/16501280/hospital.zip)
![error](https://github.com/user-attachments/assets/b9bfedcb-2dfe-411e-ad3a-f934f7aa18d6)

**Comment by preneke** [comment]
I have confirmed your error. I can confirm that CEdit doesn't find any errors. Unfortunately, I will likely be away the end of this week and I have computer problems that have yet to be solved, unrelated to running CFAST. I will get to this as quickly as I can but it might be next week.

**Comment by ozrahse** [comment]
very well thank you
Due to the time constraints of the project, I will try some options to maybe fix the problem.
Maybe uninstall and reinstall the software?
Or, for example, adding a window and adjusting the pressure of other compartments or maybe adjusting ventilation?😬

**Comment by drjfloyd** [comment]
If you are getting that error message after adding a third smoke detector, what happens if you run with only that smoke detector (i.e. not have the first two)?  Does it run successfully then? If it does, since CFAST runs fairly quickly, a somewhat painful work around would be to run CFAST multiple times each with a different detector in the input file.

**Comment by preneke** [comment]
You meant the third sprinkler. I am not sure that CFAST is the right tool for looking a sprinkler fire interactions such as multiple sprinklers at different distances impacting a single fire. CFAST just uses a simple exp decay model of reducing the fire. I don't know how it handles multiple sprinklers and multiple fires. However, you don't even have the sprinklers in the same compartment as the fires. If you are looking at the cooling effect of sprinklers in a non-fire compartment you have to use FDS. CFAST doesn't calculate the impact of sprinklers on layer temps or anything else.

**Comment by rpeacoc** [comment]
It seems to be unrelated to the actual detector input.  CEdit is failing reading and trying to output the current conditions for room 54 at t=900 s.  For a currently unknown reason, the input line read by CEdit from the .status file is incomplete even though it looks complete in the .status file when viewed in a text editor.

As a workaround, the test case you sent runs fine from the command line.  We'll continue to investigate.
