### ISSUE TITLE
CFAST thermal properties errors - HELP, please!!!

### ISSUE THREAD

**Issue by PedroP-blip** [firemodels/cfast#2134]
Hi guys

I'm using CFast to model a small enclosure. To do this, I've added this simple material and specified the lengths below for the enclosure. Modeling a door to the outside.

But I can't open the "view" window, and it returns this error:

Log: ***Error exit from CFAST, error 1 from routine read_matl

Log: Error on line 8 of the input file: &MATL ID = 'CON' MATERIAL = 'Concrete',

https://ibb.co/Yjd0Btz

https://ibb.co/5xfvN1h

https://ibb.co/51VjjDf

https://ibb.co/89Fs1Cp

![1](https://github.com/user-attachments/assets/2e71fc73-c61b-45b6-948e-30e7b2f5fb53)
![2](https://github.com/user-attachments/assets/ae0acfba-d869-496a-80ec-39ea75dc12eb)
![3](https://github.com/user-attachments/assets/abd65bf1-6148-40dd-8989-bb666935467c)
![4](https://github.com/user-attachments/assets/bf34f152-c35e-4852-9e6c-c4169e541366)

**Comment by preneke** [comment]
I don't completely understand. Did you put the material into the input file by hand or did you do it through CEdit? The error you are reporting indicates that the &MATL input namelist has an error in the input file. One way of finding the error is to add each item in the namelist one at a time. If you post the actual .in file we can take a look.

**Comment by rpeacoc** [comment]
Check the material thickness. It looks like the floor thickness is zeroSent from my iPadOn Sep 20, 2024, at 8:39 AM, preneke ***@***.***> wrote:﻿
I don't completely understand. Did you put the material into the input file by hand or did you do it through CEdit? The error you are reporting indicates that the &MATL input namelist has an error in the input file. One way of finding the error is to add each item in the namelist one at a time. If you post the actual .in file we can take a look.

**Comment by PedroP-blip** [comment]
I'm trying to do what you said, but it seems that there are still errors in the ID and MATERIAL.
For now, to try to understand the error, I just tried to insert the reinforced concrete with the following data:
ID: CON
MATERIAL: Concrete
Thermal Conductivity: 0.00175
Specific Heat: 1.0
Density: 2400
Thinckness: 0.15
Emissivity: 0.9

But it seems that the software does not save the material if it does not work...

https://drive.google.com/drive/folders/144LcT7DdiWNjCge31IyJRBrLDxg6d3_m?usp=drive_link

PS: Sorry for the delay, I was only able to attach the Google Drive link because the chat here does not support files of this type.

**Comment by PedroP-blip** [comment]
About the thickness of the material and the floor/wall/ceiling:

I just created a room with the dimensions provided, so I thought that the geometry would not include thickness. But I tested even zero thickness and it seems that it does not work.

**Comment by PedroP-blip** [comment]
I would like to thank you in advance for your help, as my end-of-course research depends on this software.

**Comment by preneke** [comment]
When my software does a virus check it blocks me from downloading example.in. I am not allowed to over ride the software. Just paste the MATL namelist block in the comments.

**Comment by mcgratta** [comment]
I can download it
![image](https://github.com/user-attachments/assets/ca234457-124a-4393-825b-19f3b4c7083f)

**Comment by preneke** [comment]
Thanks Kevin. I wonder what my virus checker was choking on. Anyway, there should be a textfile that you are loading. Images of CEdit don't allow me to change anything. Include the text input file and hopefully I can find the problem quickly.

**Comment by preneke** [comment]
Just for completeness I was able to download test.in but there really isn't anything in that file. A compartment and some initial values but no &MATL for me to look at.

**Comment by preneke** [comment]
Actually, I am sorry. I got some kind of tunnel vision about what you were asking. When I check test.in again it appears to be using the European numbers, i.e., a comma instead of a point for that fractional part of the number. CFAST doesn't work in the an operating system using European numbers. It only works with the American format. 

Am I still missing the issue or did I finally understand.

**Comment by PedroP-blip** [comment]
I'm sorry if the file was sent empty. From what I've researched, CEdit only saves the thermal properties data of the materials if the simulation goes well. Otherwise, if there is an error, it doesn't save it...

**Comment by rpeacoc** [comment]
CEdit should save thermal properties of all materials used in the simulation. It does this before CFAST is even run. Looks like the problem is the use of non-US numeric format. CFAST and CEdit only work with the US numeric format where the whole number and fractional part are separated by a period, not a comma. Other users have created a separated user profile with the numeric format set to US English.Sent from my iPhoneOn Sep 23, 2024, at 5:23 PM, PedroP-blip ***@***.***> wrote:﻿
I'm sorry if the file was sent empty. From what I've researched, CEdit only saves the thermal properties data of the materials if the simulation goes well. Otherwise, if there is an error, it doesn't save it...

**Comment by PedroP-blip** [comment]
Finally, I'm using "period" instead of "comma", but it seems that when I try to use a comma, the software resets the result.

I confess that I am somewhat desperate because I depend on the software to complete my engineering course. Therefore, I thank you and ask again for help in using it.

Also, if you will allow me, I intend to describe the process of using the software:

1) I run the "CEdit" executable and, in the "Simulation" panel, I do not change anything.

2) In the "Termal Properties" panel, I click on "add" and do not change anything. This way, the settings remain as suggested:
Material: New Material 1
ID: NM 1
Thermal Conductivity: 0.00016
Specific Heat: 0.9
Density: 790
Default Thickness: 0.016
Emissivity: 0.9
3) I click on "Save".

4) In the "Compartments" panel, I click on "Add" and describe the following:
All position (x, y, z) = 0
Width (x): 4
Depth (y): 4
Height (z): 3

**Comment by PedroP-blip** [comment]
5) In "Ceiling", "Wall" and "Floor" Materials, I select New Material 1.
6) For the thickness of each one, I select the same value adopted in "Thermal Properties": 0.016.
7) I click "Save".
8) I do not change any other settings in this panel.
9) In the "Wall Vents" panel, I click "Add" and write "Door" in the "ID" input.
First Compartment: Apart (described previously)
Second Compartment: Outside
Botton: 0
Height: 2
Width: 0
Vent Offset: 1
Face: Front

**Comment by PedroP-blip** [comment]
After that, I didn't change any other values ​​or panels. I clicked "Save" again and then clicked "View".
Two prompt boxes (black screen) opened and closed immediately, not allowing me to check what happened.
Then, when I clicked on "Simulation" there is the record below:

-------------------- Input File Syntax Check 23 (test_2)
Fatal: Wall vent 1. Width is less than 0 or greater than compartment dimensions.
Log: ***Error exit from CFAST, error 1 from routine read_matl Log: Error on line 8 of the input file: &MATL ID = 'NM 1' MATERIAL = 'New Material 1', Log: Log: Compilation Date: Thu 01/19/2023 11:24 AM Log: Revision Date: Fri Jan 13 15:42:10 2023 -0500 Log: Revision: CFAST7.7. 4-0-g6b52d0c3 Log: Release Version: CFAST 7.7.3 Log: Log: CFAST Log:

**Comment by PedroP-blip** [comment]
I believe I am making some serious mistake, but I am unable to detect it...

**Comment by PedroP-blip** [comment]
[test_2.log](https://github.com/user-attachments/files/17104861/test_2.log)

**Comment by PedroP-blip** [comment]
**Guys, you can close this post!**

I was only able to understand your first instruction now.

I went to my computer's "Control Panel", then to "Clock and Region" and changed it to "English (United States)".

Then CEdit not only stopped returning the error but also started running the simulation.

I will be eternally grateful to all of you, especially for your patience.

**Comment by rpeacoc** [comment]
Glad we were able to help.
