### ISSUE TITLE
Problem with conduction mechanics.

### ISSUE THREAD

**Issue by Eldon-Nav** [firemodels/cfast#2140]
Hello
I am working on a university project and I am having an issue or don't  quite understand the effects of different wall materials in Cfast. So I did test run where I placed two rooms side by side with no connecting windows and started a fire in one of them. After running there was no temperature change in the second room. As if there was no conduction of heat through the compartment boundaries. I selected metal as the room material and I made sure that the fire run in high heat for a long time. Is there a problem in my example or the program cannot calculate conduction when there is no gas movement between rooms?
Thanks in advance for your help. I would greatly appreciate any insights.

**Comment by drjfloyd** [comment]
Did you define the heat transfer connection in your input using the Surface Connections tab in Cedit?

**Comment by preneke** [comment]
If you are using CEdit go to the tab for "Surface Connections" and you get some guidance from the CFAST users guide chapter 8.

**Comment by Eldon-Nav** [comment]
Okay, thank you.
