### ISSUE TITLE
CFAST needs an uninstall script

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#245]
Before we release CFAST version 7, the user should be able to uninstall CFAST.  I assume this would be a direct corollary to the script used for FDS-SMV.

**Comment by gforney** [comment]
anything else to do besides unassociating .smv from smokeview, remove path entries and remove files? anything to do with cedit?

**Comment by rpeacoc** [comment]
Only the cedit file association (and check to see if FDS is installed). 

Should be a direct corollary of the FDS ONE, I assume

**Comment by gforney** [comment]
looks like I did write an uninstall script for cfast - it was not built
correctly though.  I'll check it out.

On Tue, Oct 27, 2015 at 2:05 PM, Richard Peacock <notifications@github.com>
wrote:

> Only the cedit file association (and check to see if FDS is installed).
>
> Should be a direct corollary of the FDS ONE, I assume
>
> Sent from my iPhone
>
> > On Oct 27, 2015, at 12:19 PM, Glenn Forney <notifications@github.com>
> wrote:
> >
> > anything else to do besides unassociating .smv from smokeview, remove
> path entries and remove files? anything to do with cedit?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/245#issuecomment-151589844>.
>



-- 
Glenn Forney

**Comment by gforney** [comment]
update your repo - uninstaller should be working now. Note just like the FDS uninstaller, this uninstaller should only uninstall smokeview if FDS IS NOT installed

I had a script named wrapup_cfast_install_new.bat which should have been used but was not.  I copied it into wrapup_cfast_install.bat (made a backup first).  If you made changes to the originalcopy the lines you changed from wrapup_cfast_install_OLD.bat

**Comment by rpeacoc** [comment]
I notice that the wrap-up script includes deleting the FDS6 path entry (am I right?):

call "%CFASTBINDIR%\set_path.exe" -s -m -b -r "firemodels\FDS6" >Nul 

Should this be in the CFAST script?

**Comment by mcgratta** [comment]
I tested the uninstall of the latest install, and it appears to work.
