### ISSUE TITLE
build faild with numerics.f90

### ISSUE THREAD

**Issue by fishioon** [firemodels/cfast#249]
Got many errors when build cfast. How to deal with errors!

errors:
../Source/numerics.f90(1337): error #6378: SUBROUTINE must be present on the end
-subroutine-stmt of an internal or module subroutine
    end
^
../Source/numerics.f90(4768): error #6377: FUNCTION must be present on the end-f
unction-stmt of an internal or module function
    end
^
../Source/numerics.f90(4839): error #6377: FUNCTION must be present on the end-f
unction-stmt of an internal or module function

**Comment by gforney** [comment]
What compiler and what platform are you building on?

**Comment by rpeacoc** [comment]
I don't think this should cause an error message, but I've added subroutine and function names where they were missing in numeric.f90.  This should be fixed in b76bdcec

**Comment by drjfloyd** [comment]
The Fortran 2003 standard requires the use of END SUBROUTINE or END FUNCTION for a subroutine or function contained within a module:

C1249 (R1233) SUBROUTINE shall appear in the end-subroutine-stmt of an internal or module sub-
4 routine.

**Comment by rpeacoc** [comment]
I stand corrected. I wonder which compiler they are using since neither Intel nor gnu flag it as an error.

**Comment by gforney** [comment]
here are the options we are using to build 64 bit windows cfast

intel_win_64 : FFLAGS = /O2 /Qsave /Qinit:zero /fp:strict /fp:except /traceback /stand:f08  $(GITINFO)

so assuming /stand:f08 is correct and the 2008 standard regarding SUBROUTINE is same as the 2003 standard, Intel should have warned us about it

**Comment by rpeacoc** [comment]
This should work now.  If not, create anew issue with additional details.
