### ISSUE TITLE
Fire objects with heat flux and temperature ignition conditions do not ignite when conditions are met.

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#255]
As per the title, fire objects in a CFAST 7 simulation do not appear to respect the heat flux and temperature ignition conditions.

To reproduce, run the following input file, and note that the bunsen fire never ignites, despite the coincident target showing it has surpassed the heat flux condition to ignite. A similar exercise can be repeated for temperature ignition conditions.

This issue was encountered using the gnu_linux compilation of CFAST.

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,-50,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
MATL,METHANE,0.07,1090,930,0.0127,0.04,"Methane, a transparent gas (CH4)"
!!
!!Compartment keywords
!!
COMPA,Compartment 1,3.6,2.4,2.4,0,0,0,GYPSUM,OFF,GYPSUM
!!
!!Vent keywords
!!
HVENT,1,2,1,0.91,2.1,0,1,1,0,1,1
!!
!!Fire keywords
!!
GLOBA,10,393.15
!!sofatriangle
FIRE,1,1.8,1.2,1,1,1,0,0,0,1,sofatriangle
CHEMI,1,4,0,0,0,0.3,5E+07,METHANE
TIME,0,200,400
HRR,0,3000000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,1,0.1
HEIGH,0,0,0
!!bunsen
FIRE,1,0.5,1,1,1,3,15000,0,0,1,bunsen
CHEMI,1,4,0,0,0,0.33,5E+07,METHANE
TIME,0,60,120,180,240,300,360,420,480,540,1800
HRR,0,100000,150000,200000,150000,125000,100000,90000,80000,75000,75000
SOOT,0,0,0,0,0,0,0,0,0,0,0
CO,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221
TRACE,0,0,0,0,0,0,0,0,0,0,0
AREA,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
HEIGH,0,0,0,0,0,0,0,0,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,0.5,1,1,0,0,1,GYPSUM,IMPLICIT,PDE,0.5

**Comment by mcgratta** [comment]
Thanks, we'll take a look at it.

**Comment by mcgratta** [comment]
When I run the case on my Windows 7 machine, I see the bunsen fire ignite. Or let's say that I see two fires in the Smokeview rendering.

**Comment by andersonad** [comment]
Having now built CFAST 7  on my Windows 7 machine using the gnu_windows script and run the simulation, it is still not showing secondary ignition of the bunsen fire.

I am compiling all of this using the gfortran compiler. Was your CFAST instance built using the intel compilers?

**Comment by mcgratta** [comment]
Yes. I am cloning the CFAST repository on my linux machine now. I'll see if I can replicate the problem with the gnu compiler. We normally compile with Intel Fortran. We are at version 15 or 16; that is, fairly recent.

**Comment by rpeacoc** [comment]
I've run things on both OS X and Linux with GNU and at least the sample test case shows an ignited fire. We can check more examples.

**Comment by andersonad** [comment]
I am using the default gnu fortran compiler for Ubuntu 14.04 in this instance, which is gfortran 4.8.4. What version of gfortran are you using when compiling? I might just be too far out of date.

**Comment by rpeacoc** [comment]
I'm using the same default Ubuntu installation. I'll take a more careful look tomorrow morning

**Comment by andersonad** [comment]
Running this test case on Mac OS X 10.11.1 (El Capitan) compiled using gfortran 5.2.0 also failed to produce a secondary ignition from the bunsen fire.

At this juncture I have reproduced this issue on Windows 7, Mac OS X, and Ubuntu 14.04 using gfortran 4.6.3 (windows cygwin default), 4.8.4 (ubuntu 14.04 default), and 5.2.0 (Mac OS X most recent available) respectively.

To restate what you are looking for, the !!bunsen fire object should ignite secondary to the main !!sofatriangle fire at 15 kw/m^2 incident heat flux. Presently I am confirming this condition by opening the _n.csv and examining whether the bunsen fire ever has a non-zero HRR. You can also examine the _w.csv target 1's total heat flux to confirm that the condition is indeed met. Target 1 is coincident with the bunsen fire, so if it ignites, you will likely start seeing NaN for its heat flux.

**Comment by rpeacoc** [comment]
I"ve reproduced the problem with a test case that fails on windows and should also fail with gnu. Once I resolve the error on windows, I'll verify it works on gnu.

I should note that you do need to update the input file with the new version of CFAST since it no longer creates automatic targets for fires.  Fires are now just linked to a user specified target.

**Comment by rpeacoc** [comment]
With the latest source code, 56e8f45, objects do ignite in the windows intel compiler version but does die with the gnu compiler.  The submitted data file is in an older format and needs to be updated for the release version of CFAST.  I've attached an updated file (that I just opened in the GUI and saved the file to update it). We'll look and see why it's failing with the gnu compiler.

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,50,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
MATL,METHANE,0.07,1090,930,0.0127,0.04,"Methane, a transparent gas (CH4)"
!!
!!Compartment keywords
!!
COMPA,Compartment 1,3.6,2.4,2.4,0,0,0,GYPSUM,OFF,GYPSUM,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,0.91,2.1,0,1,1,1
!!
!!Fire keywords
!!
!!sofatriangle
FIRE,1,1.8,1.2,1,1,TIME,0,0,0,0,sofatriangle
CHEMI,1,4,0,0,0,0.3,5E+07
TIME,0,200,400
HRR,0,3000000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,1,0.1
HEIGH,0,0,0
!!bunsen
FIRE,1,0.5,1,1,1,FLUX,15000,Ign_bunsen,0,0,bunsen
CHEMI,1,4,0,0,0,0.33,5E+07
TIME,0,60,120,180,240,300,360,420,480,540,1800
HRR,0,100000,150000,200000,150000,125000,100000,90000,80000,75000,75000
SOOT,0,0,0,0,0,0,0,0,0,0,0
CO,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221,0.001047221
TRACE,0,0,0,0,0,0,0,0,0,0,0
AREA,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
HEIGH,0,0,0,0,0,0,0,0,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,0.5,1,1,0,0,1,GYPSUM,EXPLICIT,PDE,0.5,Targ 1
TARGET,1,0.5,1,1,0,0,1,METHANE,EXPLICIT,PDE,0.5,Ign_bunsen

**Comment by rpeacoc** [comment]
I've updated the compiler options for gnu fortran and the object ignition seems to work correctly for a correct version 7 input file in 5756bd6.  Here's a file that has three fires, two ignited by heat flux or temperature by the initial fire.  See if it works and let us know.

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Material Properties
!!
MATL,SOFTWOOD,0.12,1380,510,0.019,0.9,"Wood, Softwoods (fir, pine) (3/4 in)"
!!
!!Compartment keywords
!!
COMPA,Comp 1,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,1,2,0,2.5,1,1
!!
!!Fire keywords
!!
!!Main FIre
FIRE,1,2.5,2.5,0,1,TIME,0,0,0,0,Main FIre
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,1000,3600,3610
HRR,0,1000000,1000000,0
SOOT,0.05,0.05,0.05,0.05
CO,0.0195,0.0195,0.0195,0.0195
TRACE,0,0,0,0
AREA,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0
!!Fire by Temp
FIRE,1,2.5,3.5,0.5,1,TEMP,523.15,Fire 2 Targ,0,0,Fire by Temp
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,1,999,1000
HRR,0,100000,100000,0
SOOT,0.05,0.05,0.05,0.05
CO,0.01954722,0.01954722,0.01954722,0.01954722
TRACE,0,0,0,0
AREA,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0
!!Fire by Flux
FIRE,1,2.5,2.5,0.5,1,FLUX,6000,Fire 2 Targ,0,0,Fire by Flux
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,1,999,1000
HRR,0,100000,100000,0
SOOT,0.05,0.05,0.05,0.05
CO,0.01954722,0.01954722,0.01954722,0.01954722
TRACE,0,0,0,0
AREA,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,2.5,3.5,0.5,0,0,1,SOFTWOOD,EXPLICIT,PDE,0.5,Fire 2 Targ
TARGET,1,2.5,1.5,0.5,0,0,1,SOFTWOOD,EXPLICIT,PDE,0.5,Fire 3 Targ

**Comment by rpeacoc** [comment]
Here's the log file from the test case in the proviso comment, run with gnu fortran on OS X 


 CFAST

 Version          : CFAST 7.0.0
 Revision         : Gitv7-59-g5756bd6-dirty
 Revision Date    : Fri Nov 6 11:03:52 2015 -0500
 Compilation Date : Nov 06, 2015  11:04:36

Object #3 (Fire by Flux) ignited at    345.157 seconds
Object #2 (Fire by Temp) ignited at    399.426 seconds
Total execution time =   2.82     seconds
Total time steps =      40028
Normal exit from CFAST

**Comment by andersonad** [comment]
Confirmed on all three OSes, the updated code works with the newly specified input file and produces the expected secondary ignitions.

I am closing this issue now.

**Comment by mcgratta** [comment]
Great, thanks for your help.

**Comment by rpeacoc** [comment]
We'll add a note to the release notes on the need to check igniting fires to make sure target information is correctly included.
