### ISSUE TITLE
.in filenames beginning with an i character will not run, but only initialize

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#256]
I noticed that filenames that begin with an i only initialize in CFAST 7, rather than running.

To reproduce, rename any validation case .in filename to "i.in" and try to run it from the command line.

This bug or undocumented feature was found using the gnu_linux build of CFAST 7.

**Comment by mcgratta** [comment]
Weird. I ran your test case from the previous post as i.in from the command line in Windows and it seemed to work fine. It ran the case. I'll ask Rick to take a look.

**Comment by andersonad** [comment]
I went ahead and also checked for this bug with the gnu_windows CFAST I compiled it. It is not present there either. This appears to be a linux specific bug.

**Comment by mcgratta** [comment]
So you see the bug when you compile CFAST with Gnu on a Linux machine?

**Comment by mcgratta** [comment]
I need to upgrade my Gnu compiler. Then I'll check for the bug. At the moment, there are some Fortran 2008 conventions that the older Gnu compiler does not understand.

**Comment by andersonad** [comment]
Ok, further testing on the linux machine reveals that this particular behavior only arises when trying to run CFAST from within a Screen instance. Strange, but probably more user error than not. I am going to close this issue.

**Comment by mcgratta** [comment]
Is a "screen instance" a Gnu utility? If so, maybe that is the problem. However, I will try to compile CFAST with the latest Gnu compiler and see if things are OK. Sometimes compilers other than Intel reveal non-standard features we are using, or other minor bugs.

Thanks

**Comment by andersonad** [comment]
Screen is indeed a GNU utility used for running virtual terminals. I am not sure how running CFAST from a virtual terminal would cause the issue mentioned above, but I am quite sure that determining the root cause and fixing it is far more trouble than it is worth.

**Comment by mcgratta** [comment]
We often find minor compiling bugs by running in different ways. It might be worth trying the latest CFAST source code to see if the issue is resolved. Rick did find some bugs that appeared on all platforms.
