### ISSUE TITLE
Heat Flux to Ambient Temperature and Floor Targets for compartments is no longer provided in _n.csv output

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#257]
The _n.csv output no longer provides "Ambient Temp Target Flux" or "Floor Temp Target Flux" for compartments in CFAST 7 for GNU builds, compared against CFAST 6.3.0.1445 (an old google code nightly build) for windows.

This issue has been reproduced in CFAST 7 built on Windows 7, Mac OS X 10.11.1, and Ubuntu 14.04 using gfortran 4.6.3, 5.2.0, and 4.8.4 respectively.

This issue may be related to issue #255 if the floor target is what is tested against for heat flux/temperature ignition conditions.

This may be intended behavior, in which case please close this issue.

**Comment by rpeacoc** [comment]
This is intended in CFAST 7.  All targets are user created in the new version.  Floor targets, ambient targets and user-created targets all used different calculations and produced different results, causing confusion for some users.  We eliminated floor and ambient targets, but a target can be placed at floor level in the center of the room.

Automatic targets for each fire are also no longer included.
