### ISSUE TITLE
Presence of non-ignited fires causes "corrector failed to converge" error

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#259]
I encountered this issue in a larger simulation but pared it down to a single compartment that displays the issue.

Running this case on CFAST 7 built with the gfortran compilers results in a "corrector failed to converge" error. If you remove Fire1, Fire2, and Fire4 (which do not ignite), the error disappears.

I tested this issue on my windows and linux machines with CFAST 7 built using gfortran 4.6.3 and 4.8.4 respectively.

I believe the input file should be correct, but am unable to build a copy of cedit to ensure everything is proper. You may be able to reproduce this more succinctly.

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,900,50,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
MATL,METHANE,0.07,1090,930,0.0127,0.04,"Methane, a transparent gas (CH4)"
!!
!!Compartment keywords
!!
COMPA,Comp 1,3.66,3.05,2.4,0,0,0,GYPSUM,OFF,GYPSUM
!!
!!Vent keywords
!!
HVENT,1,2,1,0.915,1.8,0.6,1,0.915,0,1,1
HVENT,1,2,2,0.91,2.1,0,1,2.75,0,3,1
!!
!!Fire keywords
!!
!!Fire1
FIRE,1,1.22,1.02,1,1,FLUX,15000,comp1target1,0,1,Fire1
CHEMI,1,4,0,0,0,0.3,5E+07,METHANE
TIME,0,171,342
HRR,0,100000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,0.1,0.1
HEIGH,0,0,0
!!Fire2
FIRE,1,1.22,2.04,1,1,FLUX,15000,comp1target2,0,1,Fire2
CHEMI,1,4,0,0,0,0.3,5E+07,METHANE
TIME,0,171,342
HRR,0,100000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,0.1,0.1
HEIGH,0,0,0
!!mainfire
FIRE,1,2.44,1.02,1,1,TIME,0,0,0,0,mainfire
CHEMI,1,4,0,0,0,0.3,5E+07,METHANE
TIME,0,171,342
HRR,0,100000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,0.1,0.1
HEIGH,0,0,0
!!Fire4
FIRE,1,2.44,2.04,1,1,FLUX,15000,comp1target4,0,1,Fire4
CHEMI,1,4,0,0,0,0.3,5E+07,METHANE
TIME,0,171,342
HRR,0,100000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.1,0.1,0.1
HEIGH,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,1.22,1.02,1,0,0,1,GYPSUM,EXPLICIT,PDE,0.5,comp1target1
TARGET,1,1.22,2.04,1,0,0,1,GYPSUM,EXPLICIT,PDE,0.5,comp1target2
TARGET,1,2.44,2.04,1,0,0,1,GYPSUM,EXPLICIT,PDE,0.5,comp1target4

**Comment by andersonad** [comment]
A copy of the accompanying log file:
 CFAST

 Version          : CFAST 7.0.0
 Revision         : Gitv7-59-g5756bd6-dirty
 Revision Date    : Fri Nov 6 11:03:52 2015 -0500
 Compilation Date : Nov 06, 2015  12:09:39

***Error: at t (=r1) and stepsize h (=r2) the corrector failed to converge repeatedly or with abs(h)=hmin
ierror,r1,r2 =  650    0.2698D+01    0.2577D-08
***Warning:  Solution component with the greatest error is
***Warning:  pressure in room  1
***Error, dassl - idid = -7
***Error exit from CFAST code = -7

**Comment by rpeacoc** [comment]
Thanks. This is an error from the numeric solver we use.  We see it every once in a while and usually a small change in the input file resolves the issue.  I'll take a look at this one and see if it gives us any insight into the underlying problem.

**Comment by rpeacoc** [comment]
This should be fixed in f77953f. Gnu fortran needed local variables initialized to zero to be consistent with intel options. Test and see if it works for you.

**Comment by andersonad** [comment]
Yes, the convergence errors are no longer present in the test case presented. I am closing this issue now.
