### ISSUE TITLE
Initialize only flag /i can be detected inside .in filepaths on Linux systems

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#262]
I am encountering the initialization only issue again observed in #256, but with some more searching in the documentation it seems this may be due to the manner in which the initialization only flag is called for CFAST 7.

This issue seems to appear for me when the .in file is nested in a filepath where one of the directories begins with an "i". This results in a case like the following:

testunit@sshplace: /directory/to/cfast/cfast7_gnu_linux [space here] /location/of/inpufiles/testcase.in

note the /location/of __/i__ nputfiles/testcase.in present in the filepath. 

If you can reproduce the issue using a filepath to an input file that includes a __/i__ in it, then that should be the source. Otherwise I will remain watchful for a cause. I don't expect this issue to be present on windows systems, due to the differences in the filepath structure.

**Comment by rpeacoc** [comment]
I'm sure we'll reproduce this. The file path parser is built into the Intel fortran but not for gnu. For UNIX, we need to add code to use the UNIX standard "-" for options.

**Comment by rpeacoc** [comment]
This should work in b85f5c1 . We've switched to the unix method for command line options where - is used instead of /.  For options, a space followed by a - indicates and command line option.

**Comment by andersonad** [comment]
Sorry for the delay in evaluation. I can confirm the issue is no longer present. Additionally I can confirm the new input files for linux are now called using the -(option) syntax.

I am closing this issue now.
