### ISSUE TITLE
Add section to tech ref on the solution method.

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#264]
The tech ref does not include any discussion of the solution of equations by CFAST.  First draft is in  21d2ee1.

**Comment by rpeacoc** [comment]
Needs discussion of the link between conduction PDEs and the DASSL solution of compartment surface temperatures.

**Comment by gforney** [comment]
I'll take a look at it

**Comment by mcgratta** [comment]
In `solve.f90`, there are two calls to `ddassl`. One of these calls performs a backward integration after a detector activates. Is this necessary? How big are the time steps that we would need to do this?
Secondly, what exactly are the components of `p` and `pprime` in the `ddassl` argument list? We need to spell out in the Tech Guide exactly what ODE is being solved.

**Comment by gforney** [comment]
in general the solver can take large time steps especially when the
solution is near steady state .  We could avoid this backward integration
by forcing the solver to take small time steps but integrating backwards
has not been a source of problems in the past.

The solver array is documented in section 2.2 .  The description could be
clearer though.  Rick and I are working on that.

On Thu, Dec 3, 2015 at 9:36 AM, Kevin McGrattan <notifications@github.com>
wrote:

> In solve.f90, there are two calls to ddassl. One of these calls performs
> a backward integration after a detector activates. Is this necessary? How
> big are the time steps that we would need to do this?
> Secondly, what exactly are the components of p and pprime in the ddassl
> argument list? We need to spell out in the Tech Guide exactly what ODE is
> being solved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/264#issuecomment-161657815>.
>



-- 
Glenn Forney
