### ISSUE TITLE
Add an obscuration criteria for smoke detectors

### ISSUE THREAD

**Issue by mcgratta** [firemodels/cfast#265]
A report by the Fire Protection Research Foundation suggests that at an obscuration of 8%/ft, 80% of detectors activated. Can we add an obscuration criteria along with a temperature criteria for smoke detectors. No need for a lag time model --  just the exterior smoke obscuration as a trigger for activation.

**Comment by rpeacoc** [comment]
This should be working in a1511b1. GUI support's been added with a default value of 8 %/ft.  Simple test case seems to indicate similar timing to temperature criterion (depending on appropriate soot yield input, of course). We'll run V&V to compare.

**Comment by rpeacoc** [comment]
Need to update mapping of detectors to correct experimental measurements in NIST smoke alarm tests now that we are not longer sorting detectors by room

**Comment by rpeacoc** [comment]
This should be implemented completely in 760e4d7.
