### ISSUE TITLE
CEdit changes vent offset

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#266]
Input file has a given set of values for vent offset for several horizontal vents.  When opened in CEdit, the offsets for the first three vents change to 12.6.

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,3600,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board 
!!
!!Compartment keywords
!!
COMPA,Fire Compartment,27,27,4,0,0,0,GYPSUM,OFF,GYPSUM,50,50,50
COMPA,Compartment 2,27,27,4,27,0,0,GYPSUM,OFF,GYPSUM,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,1.8,0.0083,0,7.8,2,1
HVENT,1,2,2,1.8,1.9917,0.0083,7.8,2,0
HVENT,1,2,3,1.8,2,1.9917,7.8,2,1
HVENT,3,1,1,27,0.9,0,0,4,1
HVENT,3,2,1,27,0.89,0,0,2,1
!!
!!Fire keywords
!!
!!5MW Fire
FIRE,1,13.5,13.5,0.5,1,TIME,0,0,0,0,5MW Fire
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,33,66,99,132,165,198,231,264,297,330,4330,4331,4332,4333,4334,4335,4336,4337,4338,4339,4340,4350
HRR,0,50000,200000,450000,800000,1250000,1800000,2450000,3200000,4050000,5000000,5000000,4050000,3200000,2450000,1800000,1250000,800000,450000,200000,50000,0,0
SOOT,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,27,13.5,0,-1,0,0,GYPSUM,EXPLICIT,PDE,0.5,Targ 1
!!
!!Heat flow keywords
!!
HHEAT,1,1,2,1
HHEAT,0,1,1,1
HHEAT,2,1,0,1
!!

**Comment by DUDDY8465** [comment]
Hi, please can you advise how I implement the fix for the vent offsets, I am also having this trouble on the a number of vents. Thanks

**Comment by rpeacoc** [comment]
We'll be releasing a new version shortly that will include this and other fixes. While it's possible to compile things yourself, it would require some additional commercial software libraries

**Comment by DUDDY8465** [comment]
Hi, Thank you for  the prompt response. But can you put an approximation on shortly if you can? Just as if it is longer than a week, I may be best going back to version six for my specific project. Thanks.

**Comment by rpeacoc** [comment]
We can post a pre-release version first thing next week if that works for you

**Comment by rpeacoc** [comment]
I've posted a beta version of CFAST 7.0.1 here: 

https://drive.google.com/open?id=0B73eIKf_h-9-fkZzM0pEUUx6Mm1aRkYyb1RtZ21FVDhYMEtqeEwzeDIzM01XdXdrUFpfcGs

In addition to the fix for vent offsets, it includes a fix for an issue where ignition criteria were being reset for secondary fires under some conditions, and an issue where unrealistic temperatures were reported for targets very close to newly ignited secondary fires.
