### ISSUE TITLE
Compiling CFAST on OSX with gnu - error in radiation.f90

### ISSUE THREAD

**Issue by gjaeger** [firemodels/cfast#267]
I get this message after I start "bash make_cfast.sh" in CFAST/gnu_osx:

../Source/radiation.f90:882.50:

    real(eb), dimension(co2xsize,co2ysize) :: eco2 = &
                                                  1
Error: Incompatible ranks 2 and 1 in assignment at (1)
../Source/radiation.f90:920.50:

    real(eb), dimension(h2oxsize,h2oysize) :: eh2o = &
                                                  1
Error: Incompatible ranks 2 and 1 in assignment at (1)
../Source/radiation.f90:962.58:

        call linterp(co2xsize, co2ysize, tco2, plco2, eco2, tglog, cplg, aco2, 
                                                          1
Error: Symbol 'eco2' at (1) has no IMPLICIT type
../Source/radiation.f90:976.58:

        call linterp(h2oxsize, h2oysize, th2o, plh2o, eh2o, tglog, cplg, ah2o, 
                                                          1
Error: Symbol 'eh2o' at (1) has no IMPLICIT type
make: *** [radiation.o] Error 1

**Comment by rpeacoc** [comment]
This was fixed on October 30 in82ec0128885fcfa66f15b5597bd1e12b60d7f5b8.  Do you have an older version of the repository? You may need to update to the latest version of the repository. 

I've just compiled and run the code in both release and debug mode on gnu OSX without errors.  We have gfortran 5.2 for OSX, but 4.8 also works on Linux.

**Comment by gjaeger** [comment]
I use: https://github.com/firemodels/cfast/archive/Gitv7.zip

With gfortran 4.8.5 in CFAST/gnu_osx and >bash make_cfast.sh, I get: 

gfortran -c -O2 -finit-local-zero -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -fbacktrace -cpp -DGITHASH_PP=\"Gitv7-94-g37ee850\" -DGITDATE_PP=\""Fri Nov 20 15:55:39 2015 -0500\"" -DBUILDDATE_PP=\""Nov 23, 2015  15:55:44\"" ../Source/prec.f90
gfortran: error: unrecognized command line option '-ffpe-summary=none'
make: *** [prec.o] Error 1

**Comment by gjaeger** [comment]
I get this message with the latest commit 37ee850.

**Comment by rpeacoc** [comment]
This new error comes from using different version of gfortran.  I think if you use gnu_linux rather than gnu_osx, it may work since the linux assumes version 4.8 of gfortran.

**Comment by rpeacoc** [comment]
You can also edit the makefile in the CFAST folder to remove this option for older fortrans

**Comment by gjaeger** [comment]
Without '-ffpe-summary=none' it works for gfortran 4.8.5:

 CFAST

 Version          : CFAST 7.0.1
 Revision         : Gitv7-94-g37ee850-dirty
 Revision Date    : Fri Nov 20 15:55:39 2015 -0500
 Compilation Date : Nov 23, 2015  16:23:06

**Comment by rpeacoc** [comment]
Yep. That option was added for the newer gfortran to eliminate a warning at the end of a run about floating point errors that don't effect the results. However, the option isn't available for older gfortran versions.

**Comment by gjaeger** [comment]
Thanks. 

Can you specify the required version in the wiki? It would help maybe others.
