### ISSUE TITLE
CFAST 7 - installation problems

### ISSUE THREAD

**Issue by MatijaBalant** [firemodels/cfast#328]
Hi.
My system is not able to find path specified for CFAST and I am not able to run "standard.in." When I try to do this nothing happens… In previous version I didn’t have such problems… I use Windows 7 operating system and in the administrator user account. I did as follows:

- Downloaded CFAST file from your site »http://firemodels.github.io/cfast/downloads.html« and receive file »cfast_7.0.0-SMV_6.3.1_win64«. 
- Then I created file called »CFAST« in the directory »C:\Program Files\CFAST«. 
- Then I extracted content of the »cfast_7.0.0-SMV_6.3.1_win64« into »C:\Program Files\CFAST«. 

Then I tried to run wrapup_cfast_install... I get:

"the system cannot find path specified"
"set_path.exe is not recognized as an internal or external command, operable program or batch file"

In adding document shortcuts so the Start menu "Access is denied".

How can I tell CFAST where the specified paths are?
Thank you for your help in advance…
Cheers 
Matija Balant

**Comment by rpeacoc** [comment]
The normal installation path for CFAST is c:\Program Files\firemodels\cfast7.  The installer places cfast files in this folder and places smokeview files in c:\Program Files\SMV6.  This is done so that smokeview can be used by both FDS and CFAST and so that if a newer version of FDS or CFAST is installed, the newer version of smokeview will be available to both programs.  It looks to me like the installer (which is just a self extracting ZIP file) is confused by the selection of a different installation location. 

We'll look at the installation scripts.  As a workaround, you can try installing to the default folder suggested by the installer.

**Comment by rpeacoc** [comment]
Oops, I meant the the smokeview files are placed in c:\Program Files\firemodels\SMV6

**Comment by rpeacoc** [comment]
Is your Windows 7 machine 32 bit or 64 bit? CFAST 7 will only run on a 64 bit machine.  You can check by going to the Control Panel and select "System and Security" and "System."  The "System type" should say "64-bit Operating System."

**Comment by MatijaBalant** [comment]
Thank you for your mail. My Windows 7 machine is 64 bit.

Cheers

Matija

**Comment by rpeacoc** [comment]
I'm not sure what you mean by

"Then I created file called »CFAST« in the directory »C:\Program Files\CFAST«."

You should not have to create and files.  The installation software should create appropriate folders and populate them with the CFAST software in c:\Program Files\firemodels\cfast7 and the smoke view files in c:\Program Files\firemodels\SMV6.

**Comment by MatijaBalant** [comment]
Yes I wrote the past mail in a little bit confusing way...


First I did as you mentioned. I did auto extract files into directory:”
c:\Program Files\firemodels\cfast7” as administrator. Then I tried to run
CFAST, but without success (tried to run standard.in file with double click
- no success; tried to run standard.in from CFAST’s GUI - no success). Then
I was trying to resolve the problem by reading the User guide for CFAST in
which it is stated that “The most important part of the installation is the
creation of a folder (C:\Program Files\CFAST by default) in which the CFAST
executable files and supplemental data files are installed.” Because of
that I also created this folder and try to run CFAST from it. But without
success. I still receiving messages that the paths specified can't be
found....


Cheers


Matija

**Comment by gforney** [comment]
Why aren't you using the installer? Try running the installer. It self
extracts the files, sets the path, makes file associations. Let us know if
you have problems with this.

**Comment by MatijaBalant** [comment]
I want to inform you that I did resolve the issue with the CFAST 7
installation. The problem is not in your CFAST 7 installation program and
not in the Windows 7 64 bit operating system. The problem was my extremely
good antivirus program which was trying to help me as much as it could, but
instead of that it did prevent CFAST to install. After this discovering I
did put down my antivirus program as fast as I could and then tried to
install CFAST again. With this magic trick now the CFAST 7 is running like
a charm… I would like to apologize to bother you with such problem…


Thank you all for your help and quick reply,


Matija Balant

**Comment by gforney** [comment]
no need to apologize.

any idea what your antivirus program was objecting to?

On Wed, Dec 9, 2015 at 5:25 PM, MatijaBalant <notifications@github.com>
wrote:

> I want to inform you that I did resolve the issue with the CFAST 7
> installation. The problem is not in your CFAST 7 installation program and
> not in the Windows 7 64 bit operating system. The problem was my extremely
> good antivirus program which was trying to help me as much as it could, but
> instead of that it did prevent CFAST to install. After this discovering I
> did put down my antivirus program as fast as I could and then tried to
> install CFAST again. With this magic trick now the CFAST 7 is running like
> a charm… I would like to apologize to bother you with such problem…
>
>
> Thank you all for your help and quick reply,
>
>
> Matija Balant
>
> On 9 December 2015 at 12:22, Glenn Forney <notifications@github.com>
> wrote:
>
> > Why aren't you using the installer? Try running the installer. It self
> > extracts the files, sets the path, makes file associations. Let us know
> if
> > you have problems with this.
> >
> > On Dec 9, 2015 2:01 AM, "MatijaBalant" <notifications@github.com> wrote:
> >
> > > Yes I wrote the past mail in a little bit confusing way...
> > >
> > >
> > > First I did as you mentioned. I did auto extract files into directory:”
> > > c:\Program Files\firemodels\cfast7” as administrator. Then I tried to
> run
> > > CFAST, but without success (tried to run standard.in file with double
> > > click
> > > - no success; tried to run standard.in from CFAST’s GUI - no success).
> > > Then
> > > I was trying to resolve the problem by reading the User guide for CFAST
> > in
> > > which it is stated that “The most important part of the installation is
> > the
> > > creation of a folder (C:\Program Files\CFAST by default) in which the
> > CFAST
> > > executable files and supplemental data files are installed.” Because of
> > > that I also created this folder and try to run CFAST from it. But
> without
> > > success. I still receiving messages that the paths specified can't be
> > > found....
> > >
> > >
> > > Cheers
> > >
> > >
> > > Matija
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/firemodels/cfast/issues/328#issuecomment-163135637
> >.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/firemodels/cfast/issues/328#issuecomment-163192775>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/328#issuecomment-163419613>.
>



-- 
Glenn Forney

**Comment by MatijaBalant** [comment]
I think something was relating to User Account Control.
I read the article about

**Comment by MatijaBalant** [comment]
I think something was related to *User Account Control*.



I read the article about one of the most common error we get, when we try
to install any application on Windows 8 or Windows 7. In this article it is
stated that there are a few reasons why we may get to see this error
message and one of them is also antivirus software… At scenario 3 it is
stated »If it does not help, you may next try to *disable your security
software – *because this software can be very tricky sometimes. It may
restrict access to a specific path or specific registry location.
Unfortunately, there is no easy way to find it out. So it’s better to
disable the security software completely and then try to install the
software. Again, do remember to re-enable your security software, once your
installation completes successfully.«



Article: *Author: *ShyamS@TWC
<http://www.thewindowsclub.com/author/shyamstwc>;
http://www.thewindowsclub.com/access-is-denied-software-installation-windows;
12.11.2015 at 08:05

**Comment by rpeacoc** [comment]
Glad it's resolved for you.  We'll close this issue for now.  If you have additional problems, feel free to open another issue.
