### ISSUE TITLE
CFAST crashes if a spreadsheet output file is open in Excel

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#331]
Rather than a graceful exit with an error message, CFAST just crashes if one of the spreadsheet output files is open in Excel when the program starts:

```
forrtl: severe (46): inconsistent OPEN/CLOSE parameters, unit 14, file
C:\Users\gforney\cases\Vents\unit_cube_zone.csv
Image              PC                Routine            Line        Source             
cfast7_win_64.exe  000000013F71068B  Unknown               Unknown  Unknown
cfast7_win_64.exe  000000013F6F5F74  Unknown               Unknown  Unknown
cfast7_win_64.exe  000000013F690023  OUTPUT_ROUTINES_m        1484  output.f90
cfast7_win_64.exe  000000013F6C3F20  INPUT_ROUTINES_mp        1998  input.f90
cfast7_win_64.exe  000000013F6C55FA  MAIN__                     59  fast.f90
cfast7_win_64.exe  000000013F7687FE  Unknown               Unknown  Unknown
cfast7_win_64.exe  000000013F76913C  Unknown               Unknown  Unknown
kernel32.dll       00000000771059DD  Unknown               Unknown  Unknown
ntdll.dll          000000007733A631  Unknown               Unknown  Unknown
```

**Comment by gforney** [comment]
fyi:  fds blows up in the same way if a spread sheet file is open ie when
you find a solution lets also put it into fds

On Fri, Dec 11, 2015 at 9:56 AM, Richard Peacock <notifications@github.com>
wrote:

> Rather than a graceful exit with an error message, CFAST just crashes if
> one of the spreadsheet output files is open in Excel when the program
> starts:
>
> forrtl: severe (46): inconsistent OPEN/CLOSE parameters, unit 14, file
> C:\Users\gforney\cases\Vents\unit_cube_zonecsv
> Image              PC                Routine            Line        Source
> cfast7_win_64exe  000000013F71068B  Unknown               Unknown  Unknown
> cfast7_win_64exe  000000013F6F5F74  Unknown               Unknown  Unknown
> cfast7_win_64exe  000000013F690023  OUTPUT_ROUTINES_m        1484  outputf90
> cfast7_win_64exe  000000013F6C3F20  INPUT_ROUTINES_mp        1998  inputf90
> cfast7_win_64exe  000000013F6C55FA  MAIN__                     59  fastf90
> cfast7_win_64exe  000000013F7687FE  Unknown               Unknown  Unknown
> cfast7_win_64exe  000000013F76913C  Unknown               Unknown  Unknown
> kernel32dll       00000000771059DD  Unknown               Unknown  Unknown
> ntdlldll          000000007733A631  Unknown               Unknown  Unknown
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/331>.
>



-- 
Glenn Forney

**Comment by rpeacoc** [comment]
Just pushed a fix that seems to work for CFAST ... just a check to see if
file exists and if I can't delete it print an error message and stop.
