### ISSUE TITLE
Write log file messages to standard output

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/cfast#346]
I tried to run the attached CFAST 6 input file using CFAST 7 from the command line.  The input file is apparently missing thermal properties for the CONCLITE material, per the .log output.  But nothing is displayed to the screen to indicate an error occurred.  As a command line user I am supposed to know to look in the log output.  I suggest some kind of message be added to the std output.  Either give exactly the .log message or at least say "Error: see log file for details".

[FirstTry.in.txt](https://github.com/firemodels/cfast/files/99541/FirstTry.in.txt)

**Comment by rpeacoc** [comment]
Should be resolved in revision c215c06
