### ISSUE TITLE
Add support for heat flux and temperature to EVENT

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#348]
From the user's guide, section A.7 EVENT:

"The intent is to allow these events to be triggered by time, temperature, or flux as is done with detectors. However, at the moment, time is the only option."

I understand this feature may not be high priority on the development cycle, but I would like to emphasize functionality of this sort in CFAST would increase scenario modeling capabilities strongly, and would allow users to use CFAST modeling instead of coarse FDS modeling when ventilation condition dependence on temperature or heat flux conditions is necessary.

Consider this my vote to add this feature sooner rather than later.

**Comment by rpeacoc** [comment]
We are working on a more generalized version of these events that would allow an arbitrary change over time analogous to a RAMP in FDS.  We should be able to add temperature and flux as the triggering option.

**Comment by andersonad** [comment]
If you include temperature and heat flux as the triggering option, would it be easiest to be able to tie the EVENT, (or upcoming RAMP) functionality to a room target, as is already done with fires? 

Could you point out which files would contain the relevant functions for obtaining this capability? If the implementation process for such a feature is fairly straightforward, I might be able to take a crack at implementing it in my spare time.

**Comment by rpeacoc** [comment]
Do you see flux or temperature as a trigger for a single event (like fully opening or closing a vent, for example)?  I think this would be easier than a generic change as a function of heat flux or temperature (as the RAMP keyword is intended for time)? For fire ignition, we simply tie the ignition to triggering of target value. Doing something similar for vents would be doable.  Still, it doable now with two model runs: one to determine a trigger time and a second to change the vent at that time.

**Comment by andersonad** [comment]
You are correct, I see the flux/temperature as a trigger for a single event (fully open/close a vent). As an example, my "really naive glassbreak model" is to fully open the vents in a given compartment when its floor target receives 15 kW/m^2 heat flux.

I want to avoid packaging this process in two model runs if possible because for my application I am running large ensembles of models, and doubling the amount of runs results in a non-negligible additional computational overhead. Additionally, with multiple connected compartments with vents in them, it would likely require more than two runs as it would need to be iterative, opening a given vent at a certain time, then re-running to see what the status of the other vents looks like, then re-running etc. until convergence.

**Comment by rpeacoc** [comment]
Here's a possible implementation for vertical flow vents, attached.  If the criterion is Time, you can put in as many time, fraction pairs as you like.  If it's flow or temperature, you put in an initial fraction and a final fraction at the trigger value of temperature or heat flux.  Thoughts?
![vvents](https://cloud.githubusercontent.com/assets/12814856/18062673/d1e4835c-6df5-11e6-8a22-b88059853f1d.jpg)

**Comment by andersonad** [comment]
That implementation sounds like what I would be after, yes! Is this implemented in the source code now? I don't expect to build the GUI but if you could outline what the input line looks like for, say, a target and heat flux condition I can build it and test it out.

**Comment by rpeacoc** [comment]
Part of it is implemented, but I still need to add code to CFAST for the actual triggering.  I'll work on that rather than the GUI.  Shouldn't take too long.

**Comment by rpeacoc** [comment]
You should be able to trigger vent open/close by time, temperature, or heat flux in the latest repo version. An excerpt from an updated User's Guide is attached for you to try.  HVENT, MVENT, and VVENT all support the new format with the older EVENT being superfluous now for vent openings.  The GUI's not there yet and you may not be able to view in smokeview yet, but the model itself should work. Let me know what you think.

Here's a sample input file:

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration
!!
TIMES,900,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
!!
!!Compartments
!!
COMPA,Comp 1,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
!!
!!Vents
!!
HVENT,1,2,1,1,2,0,2.5,0,1,TIME,,,0,1,0,1
VVENT,2,1,1,0.5,2,TEMP,473.15,Targ1,,0,,1,3,3
MVENT,2,1,1,V,1,0.25,V,1,0.25,0.02,200,300,FLUX,6,Targ1,,0,,1,2,2
!!
!!Fires
!!
!!Fire
FIRE,1,2.5,2.5,0,1,TIME,0,0,0,0,Fire
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,30,60,90,120,150,180,210,240,270,300,600,630,660,690,720,750,780,810,840,870,900,910
HRR,0,10540,42160,94860,168640,263500,379440,516460,674560,853740,1054000,1054000,853740,674560,516460,379440,263500,168640,94860,42160,10540,0,0
SOOT,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
!!
!!Targets and detectors
!!
TARGET,1,2.5,2.5,4.95,0,0,-1,GYPSUM,EXPLICIT,PDE,0.5,Targ1

[Users_Guide Excerpt.pdf](https://github.com/firemodels/cfast/files/450634/Users_Guide.Excerpt.pdf)

**Comment by andersonad** [comment]
In the updated user's guide I don't understand what "INITIAL_TIME" and "FINAL_TIME" refer to for a horizontal vent. For example, for the present test file, with the width of the vent increased to 3 to exacerbate its effect, if I wanted to open a vent at 300 seconds from initial opening fraction 0 to 1, what does that look like now?

original input (built using windows 7.1.1 release):
HVENT,1,2,1,3,2,0,1,1,0
EVENT,H,1,2,1,300,1,1

new (my conjecture but doesn't result in the same output):
HVENT,1,2,1,3,2,0,2.5,0,1,TIME,300,,,0,,1 (?)

Is that second setup the right syntax? I can't reproduce the same results as the first example.

Additionally, if possible, could you insert vent activations into the .log file in addition to fire object ignitions? This would make debugging easier especially while there's no smokeview visualization to inspect vent behavior qualitatively.

Presently, a fire object looks like:
Object #{fire number} (name of fire) ignited at {ignition time} seconds

Perhaps a vent object could be:
Vent #{vent number} (first 3 vent values, e.g. 1,2,1) activated at {activation time} seconds, fraction changed from {initial fraction} to {final fraction}.

let me know if I should put the second request into a separate issue, but I feel it's appropriate here as part of the feature.

**Comment by rpeacoc** [comment]
In the old EVENT, you specified the time of the change (300 s in your example) from the initial value and a decay time (1 s in your example) over which the vent transitioned from its initial value to its final value. in the new formation, the equivalent would be an initial opening time of 300 s at a fraction of 0 and a final opening time of 301 s at a fraction of 1.  If you think of the initial opening time as the time the vent begins its transition and the final opening time as the time it completes the transition, you'll get the appropriate values.

For times less than the initial opening time, the vent is at its initial opening fraction. At times greater than the final opening time, the vent is at its final opening fraction.

I will add a notification of the activation in the output file and in the log file, consistent with the ones done for detectors and fires.

**Comment by rpeacoc** [comment]
For vents triggered by heat flux or temperature, the times are ignored. Just the initial and final fractions are important.  For the numerics, we do transition from the initial to the final fraction in these cases over a time period of 1 s.

**Comment by andersonad** [comment]
confirmed everything is working compared against the older windows build.

Once the vent activation notifications are implemented in the output file and log file I think we can close this issue.

**Comment by andersonad** [comment]
Everything looks right in the logfile regarding activations. We can close this issue now! Thank you for implementing this feature.

**Comment by andersonad** [comment]
Although this issue is closed, one final question for clarification for the new HVENT specification.
What does FIRST_COMPARTMENT_OFFSET and SECOND_COMPARTMENT_OFFSET do compared against the original OFFSET specification?

In the original specification it seemed that really just the FACING and OFFSET parameters were necessary to fix the visualization of the vent. Is this new specification present to aid visualizations where, say, a duct is connecting two compartments at potentially different locations within the compartments?

**Comment by rpeacoc** [comment]
We actually ignore the second offset.  It's actually a holdover from an earlier hallway flow algorithm where you needed an offset in the "to" room. It will probably disappear in a future update.

The offset is just for visualization in Smokeview. If you noticed, we also added an X and Y offset to the vertical and mechanical vents in this update. This is also just for visualization. None of this impacts the model's calculated results.

**Comment by rpeacoc** [comment]
I'll update the User's Guide so that it doesn't show the second offset.  The spacing in the input line is actually there only to maintain compatibility with the older format that had two offsets.  We don't read or write that field in CEdit or CFAST. So you can just put an empty field or a zero in for that argument. Sorry about the confusion.
