### ISSUE TITLE
Use input target names for _w.csv file output

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#349]
_w.csv file output labels targets in order of their appearance in the input file. This can make parsing the output cumbersome when many targets in different compartments are involved.

Would it be possible to change the labels from Target 1, Target 2, ... , Target N to simply match the name of the target from the input file?

**Comment by gforney** [comment]
smokeview parses some of the .csv files so we need to be careful making changes.  Can you post an input file to provide a concrete example of what you are referring to

**Comment by andersonad** [comment]
Ah I see, consider for example the following input file:

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,2400,50,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
MATL,SOFTWOOD,0.12,1380,510,0.019,0.9,"Wood, Softwoods (fir, pine) (3/4 in)"
!!
!!Compartment keywords
!!
COMPA,compartment1,3.66,3.05,2.4,0,0,0,GYPSUM,OFF,GYPSUM,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,0.91,2.1,0,1.875,3,1
!!
!!Fire keywords
!!
!!compartment1fire1
FIRE,1,1.22,1.02,1,1,TIME,0,0,0,0,compartment1fire1
CHEMI,1,4,0,0,0,0.3,5E+07
TIME,0,171,342
HRR,0,200000,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.01,0.1,0.01
HEIGH,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,1.22,1.02,0,0,0,1,SOFTWOOD,EXPLICIT,PDE,0.5,compartment1target1

Here we can see that the TARGET present is named "compartment1target1."

if I examine the _w.csv output of this simulation then I observe that the outputs relevant to "compartment1target1" (e.g. Target Surface Temperature, Target Total Flux)  are named instead "Target 1". This convention is obviously fine for a single target scenario, but can get confusing when examining measurements from multiple targets across different compartments (noting also that floor and fire object targets are no longer generated by default)

The desired behavior would be for the _w.csv output to use "compartment1target1" instead of "Target 1" on the second row of its output where targets are named.

**Comment by rpeacoc** [comment]
This is certainly doable, but will have ramifications for other output files (i.e., Smokeview files) and any V&V cases that include targets since these are currently referenced by the current naming convention.  I agree it can get confusing.  I usually used the printed output (testcase.out, for example) to see the list of targets with names and numbers.  That's at least a workaround until we are able to address this in a future release.

**Comment by rpeacoc** [comment]
Target spreadsheet output should use the target names now.  See if this is what you intended and close the comment as appropriate.

**Comment by andersonad** [comment]
This matches the functionality I envisioned, so I am closing this issue. Thank you for implementing this!
