### ISSUE TITLE
Unstated upper limit of 2001 input lines in an input file contradicts user documentation on software limits.

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#350]
The user documentation indicates that the software should be able to handle up to 200 fires in a single test case, along with up to 1000 targets.

The following test case, [candlelitroom.in](http://pastebin.com/JCrRJSBg), consists of 200 very small fires placed inside a compartment, with 200 floor targets, 1 for each fire.

However, attempting to execute this input file throws the following error in the log file:
 CFAST

 Version          : CFAST 7.0.1
 Revision         : Gitv7-324-g819e8d7
 Revision Date    : Wed Dec 9 09:57:15 2015 -0500
 Compilation Date : Wed 12/09/2015  01:11 PM

***Error: Too many rows or columns in input file, r,c = 2001 14

removing 8 targets from the test case places the number of inputs at 2000, allowing execution of the file.

This unstated limitation on input file rows forces the user to adhere to trade-offs in their simulation that are not mentioned in the actual user guide software limitations, and it is not clear to me why it is necessary from a technical standpoint.

I do understand that the simulation is somewhat ridiculous. This issue is primarily aimed at ensuring the documentation matches the user capability, even if they want to make a 100 compartment facility with 200 fires and 1000 targets for some reason.

**Comment by rpeacoc** [comment]
This should be fixed in ad7715e.
