### ISSUE TITLE
CFAST GUI: user guide states a single test case can handle 200 fires, the gui enforces an upper limit of 100 fires.

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#351]
A spinoff issue from test case in issue #350 is that the GUI only allows a maximum of 100 fires to be added, despite the user's guide stating that 200 fires is the upper software limit.

While I cannot fathom the tedium of someone individually adding over 100 fires to a CFAST test case using the GUI, I figured I would point this issue out regardless for sake of somebody someday encountering it.

**Comment by rpeacoc** [comment]
This should be fixed in c2db295.
