### ISSUE TITLE
output f.90 compile error

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#352]
Compile error experienced on both gnu_linux and gnu_windows that seems to be recent (as of past week).

cpp -DGITHASH_PP=\"Gitv7.0.1-125-g861f82a\" -DGITDATE_PP=\""Fri Jan 29 14:45:26 2016 -0500\"" -DBUILDDATE_PP=\""Jan 29, 2016  15:02:17\"" ../Source/output.f90
../Source/output.f90:1020.132:

                          Obscuration   Temperature   RTI           Spray D
                                                                           1
Error: Unexpected end of format string in format string at (1)
../Source/output.f90:1021.10:

         ,'                                         (m)      (m)      (m)
          1
Error: Invalid character in name at (1)
../Source/output.f90:1022.10:

         ,127('-'))
          1
Error: Invalid character in name at (1)
../Source/output.f90:1017.35:

    if(ndtect/=0) write(iofilo,5000)
                                   1
Error: FORMAT label 5000 at (1) not defined

**Comment by gforney** [comment]
it is working for me.  what version of gfortran are you using?

On Fri, Jan 29, 2016 at 4:08 PM, andersonad <notifications@github.com>
wrote:

> Compile error experienced on both gnu_linux and gnu_windows that seems to
> be recent (as of past week)
>
> cpp -DGITHASH_PP=\"Gitv701-125-g861f82a\" -DGITDATE_PP=\""Fri Jan 29
> 14:45:26 2016 -0500\"" -DBUILDDATE_PP=\""Jan 29, 2016 15:02:17\""
> /Source/outputf90
> /Source/outputf90:1020132:
>
>                       Obscuration   Temperature   RTI           Spray D
>                                                                        1
>
> Error: Unexpected end of format string in format string at (1)
> /Source/outputf90:102110:
>
>      ,'                                         (m)      (m)      (m)
>       1
>
> Error: Invalid character in name at (1)
> /Source/outputf90:102210:
>
>      ,127('-'))
>       1
>
> Error: Invalid character in name at (1)
> /Source/outputf90:101735:
>
> if(ndtect/=0) write(iofilo,5000)
>                                1
>
> Error: FORMAT label 5000 at (1) not defined
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/352>.
>



-- 
Glenn Forney

**Comment by andersonad** [comment]
gfortran versions 4.6.3 (cygwin windows default) and 4.8.4 (Ubuntu 14.04 default)

**Comment by andersonad** [comment]
This error first appears for me in commit 949f1a4 

commit f6d5cd1 compiled fine on all systems.

**Comment by rpeacoc** [comment]
I get it too.  Sorry about that.  I'l fix it in a few minutes.

**Comment by rpeacoc** [comment]
Should be fixed in 6e811ac.  Works in GNU Fortran on OS X. Give it a try and close the issue if it works for you.

**Comment by andersonad** [comment]
Fix confirmed, thank you.

I am closing this issue now.
