### ISSUE TITLE
duplicate column names in _f.csv file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/cfast#353]
For a simple case with a single compartment venting to Outside the _f.csv file ends up with 2 column headers with the same name (HVENT Net Inflow).  This is tough to process with scripts like Matlab and Python, which have routines to reader header column names.  Duplicates means I have to do extra work to reader the next row.  I suggest the column headers be unique.

**Comment by rpeacoc** [comment]
1) They are supposed to be unique ... I'll see what's wrong.

2) There's a special output option (-V) to put the spreadsheet output in a form more amenable to automated processing.  It shortens all the headings and makes them a single "word" without spaces. This is what we use in the bots for matlab.

**Comment by rmcdermo** [comment]
You seem to have to look at the second line to make it unique.  That requires extra work (possibly quite a bit, but I'm not an expert) in Python.

**Comment by rpeacoc** [comment]
They are unique, but with the long output, there are 3 header lines like this:

HVENT Net Inflow          HVENT Net Inflow
Vent # 1 1>Outside	       Vent # 1 Outside>1
kg/s	                               kg/s

One column is flow from 1 to the outside, the other is flow from the outside into 1.  Perhaps we could reformat it something like this to make is unique in the first line:

HVent # 1 1>Outside	HVent # 1 Outside>1
HVENT Net Inflow          HVENT Net Inflow
kg/s	                               kg/s

With the -V option on the command line (selectable in the GUI on the Output Tab as "Validation Output"), these headers are only two lines like this:

H_1>Outside_#1	H_Outside>1_#1
kg/s	                        kg/s

This output should be easier for automated processing.

Thoughts?

**Comment by rmcdermo** [comment]
Let me try -V and get back to you.

**Comment by rmcdermo** [comment]
I like the -V for being simple for the _n and _s files.  But Python is complaining about the _f headers.  In general, I think using fancy symbols for headers (< and #) is asking for trouble.  All these different packages parse things differently and we want to be as portable as possible.  Let's come up with a different scheme that only uses underscore or dash, which are reasonably safe.

For example, change

H_1>Outside_#1 to H_1-Outside_1

I understand Glenn will have to tweak bot scripts.

What do you think?

**Comment by rmcdermo** [comment]
Actually, Python does not even like the dash.  Nor does it like a space.  For dashes it eliminates the dash on read, so H_1-Outside_1 becomes H_1Outside_1.  And for spaces it inserts an underscore.  So, H 1 would become H_1 on read (using genfromtext).  But in both these cases, it reads without complaint.

**Comment by rpeacoc** [comment]
There shouldn't be any spaces in the -V output.  I can certainly replace
the > / - with _ though it does make it a bit more cryptic, but perhaps
critic is OK for the -V option since the full output is available for those
so inclined.

**Comment by rmcdermo** [comment]
My vote would be to do what Python wants, which is H_1Outside_1 (no dash even).  The flow from Outside to 1 would be H_Outside1_1.  The important thing is that we can easily process the file.  We can always add documentation elsewhere to decrypt.

**Comment by rpeacoc** [comment]
Latest repo should have revised headers.  See what you think.

**Comment by rmcdermo** [comment]
Rick,

Here is what I get with latest code and -V option

Time,H_1_Outside_1,H_Outside_1_1,
Time,HVENT Net Inflow,HVENT Net Inflow,
,Vent  1 from 1 to Outside,Vent  1 from Outside to 1,
s,kg/s,kg/s,
 0.000000000000E+00, 0.000000000000E+00, 0.000000000000E+00,
 0.100000000000E+02, 0.441523770980E-01,-0.441523770980E-01,

There are two Time headers + the verbose HVENT stuff, which I expected
would not be there with -V

**Comment by rmcdermo** [comment]
This is also the case for _n and _s files.

**Comment by rpeacoc** [comment]
I think that's what I expected. I tried to combine the short output format (first row) with the more explanatory long format(rows 2 and 3). You should be able to use the first row for things like Python and Matlab and still have a more understandable output.

Thoughts?

**Comment by rmcdermo** [comment]
I'd say it's fine if you plan to get rid of -V option.  Else, I would use
one or the other of the header rows.

**Comment by gforney** [comment]
this will break smokeview .  we need to keep the csvsile format the same as
what is used in FDS if smokeview is to be used to read them in (2 header
lines at top not 3)

On Tue, Feb 2, 2016 at 6:51 PM, Richard Peacock <notifications@github.com>
wrote:

> I think that's what I expected. I tried to combine the short output format
> (first row) with the more explanatory long format(rows 2 and 3). You should
> be able to use the first row for things like Python and Matlab and still
> have a more understandable output.
>
> Thoughts?
>
> Sent from my iPhone
>
> > On Feb 2, 2016, at 6:06 PM, Randy McDermott <notifications@github.com>
> wrote:
> >
> > This is also the case for _n and _s files.
> >
> > On Tue, Feb 2, 2016 at 6:05 PM, Randy McDermott <
> randy.mcdermott@gmail.com>
> > wrote:
> >
> > > Rick,
> > >
> > > Here is what I get with latest code and -V option
> > >
> > > Time,H_1_Outside_1,H_Outside_1_1,
> > > Time,HVENT Net Inflow,HVENT Net Inflow,
> > > ,Vent 1 from 1 to Outside,Vent 1 from Outside to 1,
> > > s,kg/s,kg/s,
> > > 0.000000000000E+00, 0.000000000000E+00, 0.000000000000E+00,
> > > 0.100000000000E+02, 0.441523770980E-01,-0.441523770980E-01,
> > >
> > > There are two Time headers + the verbose HVENT stuff, which I expected
> > > would not be there with -V
> > >
> > > On Tue, Feb 2, 2016 at 3:13 PM, Richard Peacock <
> notifications@github.com>
> > > wrote:
> > >
> > >> Latest repo should have revised headers. See what you think.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> https://github.com/firemodels/cfast/issues/353#issuecomment-178797263>.
> > >>
> > >
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/353#issuecomment-178893054>.
>



-- 
Glenn Forney

**Comment by rmcdermo** [comment]
Perhaps we should revert all this and let me work on a solution from the
Python end.

As Rick pointed out, I'm probably the only person on the planet who cares.

**Comment by rpeacoc** [comment]
That was my plan to get rid of -V. Talking to you made me realize it was yet another hidden feature someone shouldn't have to discover.

**Comment by rpeacoc** [comment]
This won't break smokeview at all. I didn't touch the smokeview files. They're not meant for human hands anyway.

**Comment by gforney** [comment]
thought this was a file smokeview was reading now.  Is this a file we might want smokeview to look at in the future to visualize data?  if so, then we can still have 3 lines in the header - smokeview would just need to be told there is an extra lline in the header

**Comment by rpeacoc** [comment]
We put everything smokeview needs into the _zone.csv file, so it has its own file

**Comment by rpeacoc** [comment]
I'll close this for now.  New single spreadsheet output file includes both a short and long name format so it should be readable by automated processing.  Works for the bots.
