### ISSUE TITLE
Horizontal Vent not displaying in smokeview

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#354]
When I open smokeview with a test case no vent is displayed when there should be one. Trying to load the zone fire file results in the following error:

*** Error: number of horizontal flow vents specified in the smv file (0) not consistent with the number specified in the data file (1).

This issue first appears for me in commit cbb0c5a.

This error appears when compiling on gnu fortran 4.6.3 on windows 7. Here is the test case used to generate this error:

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration Keywords
!!
TIMES,2400,50,10,10
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
MATL,SOFTWOOD,0.12,1380,510,0.019,0.9,"Wood, Softwoods (fir, pine) (3/4 in)"
!!
!!Compartment keywords
!!
COMPA,bdrm2,3.66,3.05,2.4,0,0,0,GYPSUM,OFF,GYPSUM,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,0.91,2.1,0,1.875,3,1
!!
!!Fire keywords
!!
!!bdrm2fire1
FIRE,1,1.521,1.119,1,1,TIME,0,0,0,0,bdrm2fire1
CHEMI,1,4,0,0,0,0.3,5E+07
TIME,0,171,342
HRR,0,100,0
SOOT,0,0,0
CO,0,0,0
TRACE,0,0,0
AREA,0.01,0.1,0.01
HEIGH,0,0,0
!!
!!Target and detector keywords
!!
TARGET,1,1.521,1.119,0,0,0,1,SOFTWOOD,EXPLICIT,PDE,0.5,bdrm2target1

Additional Notes:
Smokeview version is 6.3.2 - Nov 8 2015
Smokeview hash is Git-r3-1-g22e7f5a
I believe this is the smokeview version that ships with version 7.0.1 December 9th 2015 CFAST release.

**Comment by rpeacoc** [comment]
This issue is caused by an out of date version of smokeview.  The code (that I assume you created an executable of CFAST from) is not a production version, but rather the development version of the code.  We've added the ability to visualize all types of vents, but this is a work in progress that results in an error with some older versions of smokeview.  We'll have an updated smokeview shortly that works with the development version of the CFAST.

**Comment by gforney** [comment]
try the test smokeview located here

https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

this installer assume you have fds (not cfast) and smokeview already installed.  just copy the smokeview installed to the location where your cfast distribution expects it

**Comment by andersonad** [comment]
The test smokeview works. In the future I'll pull down a copy of fds-smokeview and compile it before going on a wild goose chase. Thanks!

I am closing this issue now.

**Comment by gforney** [comment]
its fine to ask like you did.  We're doing a lot of work with cfast and
smokeview to improve the visualization of zone fire modeling data so
smokeview is a moving target.  Generally speaking the smokeview located on
the FDS web site is more recent than what is distributed with cfast. I
usually put up a new release up about once a month.  I put up test
smokeview's at the at the link I sent you somewhat randomly when I'm
working with someone fixing a bug or developing a new feature.  Source code
is not always the best option - I try to only commit smokeview code that
works but this is not always the case (hence our constant testing).



On Tue, Feb 2, 2016 at 4:57 PM, andersonad <notifications@github.com> wrote:

> The test smokeview works. In the future I'll pull down a copy of
> fds-smokeview and compile it before going on a wild goose chase. Thanks!
>
> I am closing this issue now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firemodels/cfast/issues/354#issuecomment-178847993>.
>



-- 
Glenn Forney
