### ISSUE TITLE
CFAST7.0 - Target internal temperature at specified depth

### ISSUE THREAD

**Issue by BurkhardF** [firemodels/cfast#355]
Using CFAST 7.0 I checked the influence of the user-specified depth on the target temperature.

When the user specified value for “internal temperature at” is changed (e.g. the default 0.5 to 0.05), there is no influence on the results of the “Target Center Temperature” in the _w.csv -file

In the _w.csv only the target center temperatures are given.
Any change in the input does only result to changes in the .out file, even though the target-temperatures are indicated as "center temperatures" there. 

I propose that the spreadsheet output should be sensitive to the user defined target depth.
 
Kind regards
Burkhard

**Comment by rpeacoc** [comment]
Thanks for pointing this out.  There is an inconsistency in how we present the internal temperature for plate targets.  It should work for cylindrical targets, but for plate targets, it only does the center temperature in the spreadsheet.  We'll make it consistent in all cases.

**Comment by rpeacoc** [comment]
This should be resolved in 104b9a6.  Spreadsheet and printed output now just call a single routine to obtain target results.  New release pending.
