### ISSUE TITLE
CFAST7.0 - Vent Flows written in project_f.csv are wrong

### ISSUE THREAD

**Issue by BurkhardF** [firemodels/cfast#356]
It seems that the vents flows written in the spreadsheet output project_f.csv are wrong. 
They are not consistent with the text output.
In the example below of a 6 MW fire in a compartment with an A = 2m2 door the text output confirms the Kawagoe eq., whereas the project_f.csv gives very small numbers.

Kind regards
Burkhard 

Input:
VERSN,7,Concrete
!!
!!Scenario Configuration Keywords
!!
TIMES,3000,120,10,30
EAMB,293.15,101300,0
TAMB,293.15,101300,0,50
!!
!!Material Properties
!!
MATL,CONCRETE,1.75,1000,2200,0.15,0.94,"Concrete, Normal Weight (6 in)"
!!
!!Compartment keywords
!!
COMPA,Compartment 1,6,6,3,0,0,0,CONCRETE,CONCRETE,CONCRETE,50,50,50
!!
!!Vent keywords
!!
HVENT,1,2,1,1,2,0,3,1,1
!!
!!Fire keywords
!!
!!6-MW
FIRE,1,3,3,0,1,TIME,0,0,0,0,6-MW
CHEMI,1,4,0,0,0,0.3,5E+07
TIME,0,3,6,9,12,15,18,21,24,27,30,3030,3030.3,3030.6,3030.9,3031.2,3031.5,3031.8,3032.1,3032.4,3032.7,3033,3043
HRR,0,60000,240000,540000,960000,1500000,2160000,2940000,3840000,4860000,6000000,6000000,4859825,3839688,2940274,2160117,1500000,959921.9,539882.8,240078.1,60019.54,0,0
SOOT,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
!!
!!Misc. stuff
!!
STPMAX,0.1

**Comment by rpeacoc** [comment]
We'll take a look.  What version of CFAST are you using?

**Comment by BurkhardF** [comment]
I use CFAST 7.0.1


Am 09.02.2016 um 15:06 schrieb Richard Peacock:
>
> We'll take a look. What version of CFAST are you using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/firemodels/cfast/issues/356#issuecomment-181876691>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by rpeacoc** [comment]
When I run your test case, I get an upper layer outflow of 1.495 kg/s and a lower layer inflow of 1.371 kg/s in the printed output. The spreadsheet output (which only has the net flow) is 0.123 kg/s which is about the difference between the two.  Am I missing something?

**Comment by BurkhardF** [comment]
Thank you for your prompt answer!

I think the gross flows which were printed by the old  job_f.csv were 
very helpful.

Is there any spreadsheet output which gives the gross vent flows?

There is plenty of information in the job_zone.csv (maybe also the 
flows?) but unfortunately the job_zone.csv is not explained in the User 
Guide.

Kind regards
Burkhard



Am 09.02.2016 um 20:41 schrieb Richard Peacock:
>
> When I run your test case, I get an upper layer outflow of 1.495 kg/s 
> and a lower layer inflow of 1.371 kg/s in the printed output. The 
> spreadsheet output (which only has the net flow) is 0.123 kg/s which 
> is about the difference between the two. Am I missing something?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/firemodels/cfast/issues/356#issuecomment-182025861>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by rpeacoc** [comment]
It's certainly doable to have all the flows in the output file.  The problem is that there are lot of possible combinations of flow in each direction (U1-->U2 L1-->L2, L1-->U2, U1-->L2, L1-->U1 plus the same in the other direction which leads you to 12 columns for every vent.

The _zone file does have lots of vent flow details, including everything that the model is actually calculating for vent flow (temperature and mass flow for up to 10 slabs per vent in each direction).  It's only intended for use by smokeview and is subject to change as smokeview is updated.

We are working on a more general output specification for the user to allow you to pick the outputs you actually want rather than having all of them all the time.  That's a bit in the future.  We'll keep this issue open so we know there is interest in the more detail flow outputs.
