### ISSUE TITLE
CFAST fails interpolating layer absorbtivity

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#488]
With the attached test case, a vent opens at 200 s.  Once the vent opens, the linear interpolation fails with a subscript error in the layer absorbtivity calculation when x>xdim.  Interpolation should devolve into a 2d interpolation in this case.  Same is likely true of y>ydim

**Comment by rpeacoc** [comment]
VERSN,7,CFAST Simulation
!!
!!Scenario Configuration
!!
TIMES,1200,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Compartments
!!
COMPA,Comp 1,4,4,4,0,0,0,OFF,OFF,OFF,50,50,50
COMPA,Comp 2,4,4,4,4,0,0,OFF,OFF,OFF,50,50,50
!!
!!Vents
!!
HVENT,1,2,1,1,2,0,1.5,2,0
EVENT,H,1,2,1,200,1,1
!!
!!Fires
!!
!!New Fire
FIRE,1,2,2,0,1,TIME,0,0,0,0,New Fire
CHEMI,1,4,0,0,0,0,5E+07
TIME,0,1,10,11
HRR,0,100000,100000,0
SOOT,0,0,0,0
CO,0,0,0,0
TRACE,0,0,0,0
AREA,0.09,0.09,0.09,0.09
HEIGH,0,0,0,0

**Comment by preneke** [comment]
Latest version of CFAST fixes bug
