### ISSUE TITLE
Mechanical Ventilation is centered wrong

### ISSUE THREAD

**Issue by giesser3** [firemodels/cfast#503]
The mechanical ventilation position is supposed to center over the ceiling area, however it appears that the code has the calculation switched for its coordinates where the center of the ventilation would be located at (0.5Y,0.5X) instead of (0.5X,0.5Y). Therefore for a long room the ventilation will fall outside of the rooms dimensions.

**Comment by drjfloyd** [comment]
Are you reporting a bug with the pyrosim interface?  If that is the case send it to Thunderhead Engineering. We do not provide support for their software.

If this is an error with FDS processing the fds input file, please post the simplest version of your file that replicates the error.

**Comment by drjfloyd** [comment]
Ignore my prior comment that I deleted. I wasn't paying close enough attention and thought I was responding to an fds issue rather than a cfast one.

**Comment by rpeacoc** [comment]
This doesn't effect the results of the calculation (which just depend on the height of the vent), only the visualization. We'll take a look and fix as appropriate in the next release

**Comment by rpeacoc** [comment]
Fixed in the code.  Maintenance release of CFAST coming soon will include it.
