### ISSUE TITLE
Add command-line support for controlling which output files are written.

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#515]
Would it be possible to add support for designating which output files a user wants written from a given CFAST simulation to the command-line options?

I am finding some use cases where I need, for example, only the _w.csv or _n.csv files for a particular analysis, but from a large number of cfast scenarios. This can result in non-negligible amounts of disk space being used for files that will be deleted after the fact (e.g. .out, .smv, and _zone.csv files).

**Comment by gforney** [comment]
rick will look at this when he gets back

**Comment by rpeacoc** [comment]
Support added in 204ee5a.
