### ISSUE TITLE
Enhance smokeview to place vents at user-specified locations

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#551]
Here's two set of smokeview files that specify the location of all vent types as xl, xu, yl, yu, zl, zu rather than the older vent-type specific format.  The first set (Test2.smv) includes two vents in the locations originally placed in default locations.  The second (Test.smv) includes two vertical vents that are placed offset from the center of the compartment so they should show up as two separate vents.
[Tests.zip](https://github.com/firemodels/cfast/files/450282/Tests.zip)

**Comment by gforney** [comment]
I don't see any attachments.  Is this the right issue?

**Comment by rpeacoc** [comment]
See Tests.xip in the original post

**Comment by gforney** [comment]
I"m looking at issue 551.  I don't see any attachments.  should I be looking somewhere else?

**Comment by gforney** [comment]
is smokeview ok now with respect to this issue
