### ISSUE TITLE
Log file does not report fire activations that occur during the same timestep

### ISSUE THREAD

**Issue by andersonad** [firemodels/cfast#568]
After doing some additional testing from issue #348, it appears that if multiple fires reference the same target with the same ignition conditions, only one is triggered (usually the last one listed). Strangely this bug does not extend to vents.

See a modified input file from #348 

VERSN,7,CFAST Simulation
!!
!!Scenario Configuration
!!
TIMES,900,50,10,10
EAMB,293.15,101325,0
TAMB,293.15,101325,0,50
!!
!!Material Properties
!!
MATL,GYPSUM,0.16,900,790,0.016,0.9,Gypsum Board (5/8 in)
!!
!!Compartments
!!
COMPA,Comp 1,5,5,5,0,0,0,OFF,OFF,OFF,50,50,50
!!
!!Vents
!!
HVENT,1,2,1,1,2,0,2.5,0,1,TIME,,,0,1,0,1
VVENT,2,1,1,0.5,2,TEMP,473.15,Targ1,,0,,1,3,3
MVENT,2,1,1,V,1,0.25,V,1,0.25,0.02,200,300,FLUX,6,Targ1,,0,,1,2,2
HVENT,1,2,1,1,2,0,2.5,0,1,FLUX,15000,Targ1,0,0,0,1
HVENT,1,2,1,1,2,0,2.5,0,1,FLUX,15000,Targ1,0,0,0,1

!!
!!Fires
!!
!!Fire
FIRE,1,2.5,2.5,0,1,TIME,0,0,0,0,Fire
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,30,60,90,120,150,180,210,240,270,300,600,630,660,690,720,750,780,810,840,870,900,910
HRR,0,10540,42160,94860,168640,263500,379440,516460,674560,853740,1054000,1054000,853740,674560,516460,379440,263500,168640,94860,42160,10540,0,0
SOOT,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

FIRE,1,2.5,2.5,0,1,FLUX,15000,Targ1,0,0,Fire2
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,30,60,90,120,150,180,210,240,270,300,600,630,660,690,720,750,780,810,840,870,900,910
HRR,0,10540,42160,94860,168640,263500,379440,516460,674560,853740,1054000,1054000,853740,674560,516460,379440,263500,168640,94860,42160,10540,0,0
SOOT,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

FIRE,1,2.5,2.5,0,1,FLUX,15000,Targ1,0,0,Fire3
CHEMI,1,4,0,0,0,0.35,5E+07
TIME,0,30,60,90,120,150,180,210,240,270,300,600,630,660,690,720,750,780,810,840,870,900,910
HRR,0,10540,42160,94860,168640,263500,379440,516460,674560,853740,1054000,1054000,853740,674560,516460,379440,263500,168640,94860,42160,10540,0,0
SOOT,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
CO,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
TRACE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
AREA,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
HEIGH,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
!!
!!Targets and detectors
!!
TARGET,1,2.5,2.5,4.95,0,0,-1,GYPSUM,EXPLICIT,PDE,0.5,Targ1

Both wall vents activate. However Fire2 fails to activate despite having the same ignition conditions as Fire3.

**Comment by andersonad** [comment]
Exploring this bug a bit more, it seems to occur when multiple fires would activate during the same time-step, so I think it may be related to how the state of activation is changed on a given time-step.

For example, changing the activation heat flux on "Fire2" in the above input to 15001 W/m^2 will suddenly cause it to begin activating. While such a small edit is a convenient workaround, I am hoping it is not too much trouble to edit the fire activation routine slightly so multiple fires can be activated on the same time-step, commensurate with how the vent activation presently behaves.

**Comment by rpeacoc** [comment]
That would explain it.  We do only look at the first triggering event in a tilmestep.  That was originally coded to prevent more than one sprinkler going off (since we don't really model the interaction of the water with the layer gases).  I'll take a look and see how we can allow them all to activate.

**Comment by andersonad** [comment]
What I thought was a simple workaround (change the activation criterion slightly) is in fact not so simple because I don't have prior knowledge regarding how fast heat flux or temperature is changing versus whatever the present time-step is. Thus determining a reasonable activation offset also ends up becoming a somewhat iterative procedure, which is not inconsequential for ensemble CFAST runs.

**Comment by rpeacoc** [comment]
Check the fire output in the output file for your test case.  With my test case, the fires do ignite, but only the last one is actually reported as begin ignited.  I see why that is in the code and can fix it if easily if that's the actual problem.

**Comment by rpeacoc** [comment]
I ran your test case (above) and it does actually ignited fire 3 (see printed output excerpt, attached).  It looks like to me that it's just not reporting the ignition.

[BothFiresIgnite.txt](https://github.com/firemodels/cfast/files/480211/BothFiresIgnite.txt)

**Comment by andersonad** [comment]
My output file agrees with yours, I had not checked it. my apologies! Let me change the title of this issue.

**Comment by rpeacoc** [comment]
This should be fixed in f4936c3.  All fire ignitions should be reported in both the log and output files now.

**Comment by andersonad** [comment]
Sorry about the delay. I have confirmed that this issue is indeed fixed. I am closing this issue now. Thank you!
