### ISSUE TITLE
Smokeview should be able to show closed vents

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#600]
The attached smokeview files include a number of vents that open or close at various times.  It would be nice to be able to quickly see which vents are open and which are closed.

**Comment by rpeacoc** [comment]
[Test.zip](https://github.com/firemodels/cfast/files/509339/Test.zip)

**Comment by gforney** [comment]
how about drawing an "x" in vents that are closed ie draw the rectangle as before and also draw two diagonals

**Comment by rpeacoc** [comment]
That works. Whatever works for you is fine with me.

**Comment by gforney** [comment]
am now drawing an x through the vent when the vent is closed .  Links to test smokeviews are on the smokeview release notes page

https://github.com/firemodels/fds/wiki/Smokeview-Release-Notes

**Comment by rpeacoc** [comment]
This works. CFAST seems to show all vents closed until you load the zone fire file, but works fine on load.
