### ISSUE TITLE
Removal of LOI

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/cfast#622]
The ability to specify a 0 % LOI has been removed from CFAST 7. This is a major issue for FPRA work.  When doing plant wide screening calculations we like to set the LOI to 0 % to realize as much of the energy as possible from ignition sources and cables in the room (following guidance in RACHELLE-FIRE and CHRISTI-FIRE) without having to provided additional ventilation.  If compartments screen at this level, then we can avoid the effort of having to delve into the details of exactly what openings and ventilation is present.  Can this be added back to CFAST?

**Comment by drjfloyd** [comment]
Edit - I see this can be done via hand editing of the text file and adding GLOBA.  Can this be put back in the GUI which is an easier interface for QA review of an input file?

**Comment by drjfloyd** [comment]
2nd Edit - it appears using GLOBA in an input is ignored with an obsolete warning and 15 % is used.  Back to the initial request of adding this back.

**Comment by rpeacoc** [comment]
I assume you saw GLOBA in the appendix of CFAST inputs.  That needs updating.  I can pretty easily add back in a global LIMO2 command that only has a single input of the LOI.  Does a global LOI rather than a per fire one work for what you need?

**Comment by drjfloyd** [comment]
A global input is fine. I think in general if one is trying to do something like this it would be on a global basis.

**Comment by rpeacoc** [comment]
LIMO2 should work in 0c300db. At the moment, it's only supported in the model, not in the GUI.

**Comment by rpeacoc** [comment]
LIMO2 has a single argument, the LOI expressed as a fraction.

**Comment by rpeacoc** [comment]
Do you need an executable to test or can you build that yourself?

**Comment by drjfloyd** [comment]
I don't currently have a fork of the CFAST repo to do a build. If you can easily share an executable that would be great and I'll pass it along to my coworkers who were trying to use the LOI to test.

**Comment by rpeacoc** [comment]
You should be able to download cfast7_win_64.exe here:

https://drive.google.com/open?id=0B8Fy6sZiv000dFZPOWFpd1FFRXc

It's only the model; no supporting GUI yet.

**Comment by rpeacoc** [comment]
GUI support should be working in a09dce2. It's on the environment tab since it's a global value.

**Comment by drjfloyd** [comment]
The exe fix is working.

**Comment by rpeacoc** [comment]
Cool.  We'll release it officially as part of 7.2.0 which should be out next week (pending a new smokeview build).
