### ISSUE TITLE
Compilation problem gnu_linux_64

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#633]
../../../Source/CFAST/output.f90:767:132:

 5040 format (//,'Vertical Natural Flow Connections (Ceiling, ...)',//,'Top            Bottom         Vent    Shape     Area      ', &
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
../../../Source/CFAST/output.f90:767:132:

 5040 format (//,'Vertical Natural Flow Connections (Ceiling, ...)',//,'Top            Bottom         Vent    Shape     Area      ', &
                                                                                                                                    1
Error: Unexpected end of format string in format string at (1)
../../../Source/CFAST/output.f90:768:9:

         'Open/Close  Trigger                 Initial     Initial     Final       Final',/, &
         1
Error: Invalid character in name at (1)
../../../Source/CFAST/output.f90:728:26:

         write (iofilo,5040)
                          1
Error: FORMAT label 5040 at (1) not defined
f951: some warnings being treated as errors
../makefile:65: command for object 'output.o' not successful
make: *** [output.o] Error 1

**Comment by rpeacoc** [comment]
This should work in 67add132600a16f0ef436944f075612c3c90ab4e
