### ISSUE TITLE
CFAST/Smokeview - Number vents in the smv file not consistent with the data file

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#635]
Problem with displaying the data in smokeview. Smokeview version 6.3.6 and 6.3.12.

*** Error: number of horizontal flow vents specified in the smv file (0)
    not consistent with the number specified in the data file (65)
*** Error: number of vertical flow vents specified in the smv file (0)
    not consistent with the number specified in the data file (28)

[config.txt](https://github.com/firemodels/cfast/files/593267/config.txt)

**Comment by rpeacoc** [comment]
This should be fixed in Smokeview 6.4.2, available for download at https://pages.nist.gov/fds-smv/

**Comment by akrasuski** [comment]
It still doesn't work in version 6.4.2 of smv.  Should I place an issue on smv?

**Comment by rpeacoc** [comment]
Can you post your input file? I'll take a look.

**Comment by rpeacoc** [comment]
Oops, I see the input file now. I'll check it out and see if it's a CFAST or Smokeview problem.

**Comment by rpeacoc** [comment]
Your input file has errors and I think that's what's causing the smoke view problem.  Coordinates for compartment positions in CFAST have to be greater than or equal to zero. A number of your compartments have negative positions.  I'd suggest you fix this and try again.  If it's still a problem, we'll look a little deeper.

**Comment by akrasuski** [comment]
I think, that this is not caused by negative coordinates. Please find below the file with proper coordinates. The problem remains. 
[cfast.txt](https://github.com/firemodels/cfast/files/666702/cfast.txt)

**Comment by rpeacoc** [comment]
Great, thanks.  I'll look further

**Comment by rpeacoc** [comment]
I still get fatal errors noted in CEdit for all the vents. The vent positions the first  9 vents are all greater than 150 m for the sill and soffit while the ceiling height is 3 m for all compartments. Since all the compartments are at an elevation of 0 m, it's not that these are absolute heights (positions are relative to the compartment floors). Am I missing something here?

HVENT,7,18,1,2.13,187.19,184.69,3.44,,1,TIME,,,0,0,0,0,0,0
HVENT,7,18,2,2.29,184.07,181.57,0.32,,1,TIME,,,0,0,0,0,0,0
HVENT,8,18,1,2.65,178.02,175.52,0.37,,1,TIME,,,0,0,0,0,0,0
HVENT,9,18,1,1.68,175.31,172.81,3.76,,1,TIME,,,0,1,0,1,0,0
HVENT,9,18,2,1.74,172.35,169.85,0.8,,1,TIME,,,0,0,0,0,0,0
HVENT,10,18,1,1.85,168.94,166.44,3.56,,1,TIME,,,0,0,0,0,0,0
HVENT,10,18,2,1.83,165.96,163.46,0.58,,1,TIME,,,0,0,0,0,0,0
HVENT,11,18,1,1.76,159.9,157.4,0.81,,1,TIME,,,0,0,0,0,0,0
HVENT,12,18,1,1.71,162.81,160.31,0.52,,1,TIME,,,0,1,0,1,0,0

**Comment by akrasuski** [comment]
I don't use CEdit. Please launch the file on cfast without CEdit. As far as I understand CEdiit has changed the value of the file I've sent you.  The original one should be as follows (please see the headers):
!!DOORS , from , to , id , width , soffit , sill , offset , face , open
  2 HVENT   , 1    , 2  , 1  , 1.25  , 2.0    , 0    , 0.22   , 4    , 0
  3 HVENT   , 1    , 4  , 2  , 0.99  , 2.0    , 0    , 0.41   , 2    , 1
  4 HVENT   , 1    , 7  , 3  , 1.02  , 2.0    , 0    , 2.11   , 1    , 0
  5 HVENT   , 1    , 18 , 4  , 0.88  , 2.0    , 0    , 2.98   , 3    , 0
  6 HVENT   , 2    , 5  , 1  , 0.94  , 2.0    , 0    , 0.38   , 4    , 0
  7 HVENT   , 2    , 8  , 2  , 1.02  , 2.0    , 0    , 25.87  , 1    , 1
  8 HVENT   , 2    , 9  , 3  , 1.03  , 2.0    , 0    , 19.74  , 1    , 1
  9 HVENT   , 2    , 10 , 4  , 1.0   , 2.0    , 0    , 13.74  , 1    , 1
 10 HVENT   , 2    , 13 , 5  , 1.1   , 2.0    , 0    , 6.96   , 1    , 1
 11 HVENT   , 2    , 14 , 6  , 1.3   , 2.0    , 0    , 0.34   , 1    , 0
 12 HVENT   , 3    , 5  , 1  , 1.59  , 2.0    , 0    , 0.17   , 2    , 0
 13 HVENT   , 3    , 6  , 2  , 1.47  , 2.0    , 0    , 0.26   , 4    , 1
 14 HVENT   , 3    , 15 , 3  , 1.8   , 2.0    , 0    , 23.09  , 1    , 0
 15 HVENT   , 3    , 16 , 4  , 1.5   , 2.0    , 0    , 9.39   , 1    , 1
 16 HVENT   , 3    , 17 , 5  , 1.51  , 2.0    , 0    , 2.19   , 1    , 1
 17 HVENT   , 4    , 18 , 1  , 0.92  , 2.0    , 0    , 6.57   , 3    , 0
 18 HVENT   , 7    , 8  , 1  , 0.97  , 2.0    , 0    , 0.68   , 4    , 0
 19 HVENT   , 8    , 9  , 1  , 0.94  , 2.0    , 0    , 0.69   , 4    , 1
 20 HVENT   , 10   , 12 , 1  , 1.03  , 2.0    , 0    , 0.67   , 4    , 0

It is worth mention that if I launch this file on cfast 7.0.1 the output is displayed properly on SMV. The same file on launched on cfast 7.2 generates the problem in question.

**Comment by rpeacoc** [comment]
This isn't the same as CFAST.txt you sent in a previous comment. It has ridiculous values for sill and soffit. I'll need the actual working file to test things. The vent formats did change in 7.2 so there may be an issue when we read it in. Either way I'll need the correct file.

**Comment by rpeacoc** [comment]
Take a look at the windows and see if you think they are correct

**Comment by rpeacoc** [comment]
Your doors look fine. It's the windows that seem screwy to me.  I'm not suggesting CEdit for running (since it just spawns CFAST in a hidden command windows anyway) but I was using it to verify the file.

**Comment by rpeacoc** [comment]
While you're looking at your data files, I'd suggest your heat of combustion is off by three orders of magnitude. In the file you sent, the heat of combustion for the fire is 19448 kJ/kg.  Typical heats of combustion range from about 10000 MJ/kg to about 50000 MJ/kg.  Also, the yield value for trace species is set to 0.5 which means that 1/2 of the mass of the fuel goes to trace species.  This would be disatorous for the overall mass balance since we assume that the trace species is negligible compared to the overall pyrolysis rate and recommend a value no larger than 0.001 kg/kg.

**Comment by mcgratta** [comment]
19448 kJ/kg is OK. Some would write this as 19.4 MJ/kg.

**Comment by rpeacoc** [comment]
Oops, you're correct Kevin.  Sorry for my confusion.

**Comment by rpeacoc** [comment]
Oops.  When you read the test file into CEdit, the Heat of Combustion comes up as 19.448 kJ/kg, not 19448 kJ/kg 0r 0.019 MJ/kg , hence things are off by 1000. Sorry for the continuing confusion.

We've updated the Appendix in the User's Guide to better and more completely document the input commands which should be useful if you are developing input files outside the GUI. It should be available here: https://drive.google.com/open?id=0B73eIKf_h-9-VVBrMHl2Mnc2djQ

**Comment by rpeacoc** [comment]
I updated my previous comment to fix my own units conversion errors.

**Comment by akrasuski** [comment]
Please find attached a very simple test.in file with 3 compartment 2 doors and 2 leakages. The problem is manifested as follows:

*** Error: number of horizontal flow vents specified in the smv file (0)
    not consistent with the number specified in the data file (4)

I also included my smv file where the error is displayed. 

[test.txt](https://github.com/firemodels/cfast/files/669782/test.txt)
[test_smv.txt](https://github.com/firemodels/cfast/files/669783/test_smv.txt)

Below you can see diff between smv file from CFAST 7.0.1 (correct) and CFAST 7.2:

< HVENTGEOM
<    1   2   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E+01
< HVENTGEOM
<    1   2   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E-01
< HVENTGEOM
<    2   3   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E+01
< HVENTGEOM
<    2   3   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E-01
< VENTGEOM
<    1   2   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E+01
< VENTGEOM
<    1   2   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E-01
< VENTGEOM
<    2   3   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E+01
< VENTGEOM
<    2   3   2  0.9000E+00  0.0000E+00  0.0000E+00  0.2000E-01
---
> HVENTPOS
>    1   2  0.5000E+01  0.5000E+01  0.0000E+00  0.9000E+00  0.2000E+01  0.0000E+00
> HVENTPOS
>    1   2  0.5000E+01  0.5000E+01  0.0000E+00  0.9000E+00  0.2000E-01  0.0000E+00
> HVENTPOS
>    2   3  0.1000E+02  0.1000E+02  0.0000E+00  0.9000E+00  0.2000E+01  0.0000E+00
> HVENTPOS
>    2   3  0.1000E+02  0.1000E+02  0.0000E+00  0.9000E+00  0.2000E-01  0.0000E+00

It seems that smv prefers VENTGEOM instead of HVENTPOS.

**Comment by rpeacoc** [comment]
The vent input format did change going to 7.2, but this is what we needed to at least begin to check things out.  Problem is, your file works fine for me with CFAST 7.2.1 and Smokeview 6.4.2 (Though I'm still concerned with the heat of combustion input; units for input are J/kg).  Are these the versions of the model you are using?

I still wondering if we're not interpreting your vent inputs correctly in CFAST 7.2.1.  I do have four vents showing in 7.2.1, but they are all closed over time.  How do you think your vents should look over time for this test case?

**Comment by akrasuski** [comment]
Ok, I found the problem. The problem was that smv update script doesn't work properly in my case. It writes out that updating was successful however it wasn't in fact. I thought that I work on version 6.4.2 but I'm still working on smv 6.3.12. I'm sorry for this misleading information. I'll try to solve this problem on smv forum. 

Regarding the input parameters for CFAST. Thank you for the mentioning about heat of combustion. Yes, it is an error, the values are in kJ/kg and should be in J/kg. The bug was created when we rewrote our software to python. 

As I mentioned in other mail the parameters for CFAST are generated by the Monte Carlo engine. The heat of combustion is draw from uniform distribution min = 16400 kJ/kg max = 27 000 kJ/kg. The Monte Carlo also justifies the closed vents, you asked. So for this specific situation the Monte Carlo created the scenario with doors closed. And it won't change over time. In other scenario they will be open. It is easer for me to regulate this by the opening fraction than removing or adding the vents. Therefore there are closed vents in my file.

**Comment by rpeacoc** [comment]
For now, I'll assume this is a smokeview issue.  If you have additional problems, feel free to reopen the issue or create a new one.

I've added a check in CFAST to ensure wall vents are fully within the compartment.  The check was in CEdit, but slipped by CFAST sometime in antiquity.  Check implemented in bedc72eb48eb2500278b5cde8a9eb6814b98a1df
