### ISSUE TITLE
Relationship between the number of data points for fire definition and the calculation speed

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#637]
Does the number of points for a single fire definition have an impact on calculations speed or other behaviour of CFAST.  I mean, is it better to use maximum length (199) of this vector or better to keep is small?

**Comment by rpeacoc** [comment]
It might have a tiny impact on the calculation time, but regardless of the number of data points, CFAST simple interpolates between time points to determine fire input values as a function of time. It's not something I would focus on to increase execution speed.
