### ISSUE TITLE
Some 3D SLCF files have stopped updating with the simulation 

### ISSUE THREAD

**Issue by KateLM** [firemodels/cfast#642]
Hi, I'm running a fairly large model with a lot of slice files. The simulation is still running (at 12900secs), but I've noticed that some of the output slice files in the directory have stopped updating (at 10900secs). I've instructed output SL3D files to be dumped every 100secs. The largest file is 5.3GB but there are 33MB SLCF files not updating as well. I have 16GB of RAM on my computer and the files are being run off a 2TB external hard drive. Can anyone suggest what is happening here and how to fix it (without starting again)?

Thanks in advance!
Kate

**Comment by mcgratta** [comment]
This is just too much output.

**Comment by KateLM** [comment]
Sorry, I mean to post this thread under FDS. But I'm not sure I understand why this is too much output? As I mentioned most of the SLCF files are still running. And I have the space and memory on my computer. ?

**Comment by KateLM** [comment]
And is there no way to rectify this without starting the model all over again?

**Comment by gforney** [comment]
if fds is showing output past 10900 s in your casename.out file then don't think it is problem with fds (not outputting info to slice files past 10900 s).  try copying your case to another directory, this may force whatever OS you are using to flush buffers (if that was the problem)

**Comment by KateLM** [comment]
Yes, the Output file goes to 12900secs. I have tried copying to another directory on the main computer with no luck.  If I wanted to use 2D slice files instead of the 3D file which is so large, would I have to start the simulation again with the new dump line in the code? Or seeing as I have the data for that volume already, can I add the dump line and start from the last restart file?

**Comment by gforney** [comment]
since your 3d slice files are too large to look at, I was suggesting that you place 2d slice files at locations of interest.  you would have to restart your run.

**Comment by KateLM** [comment]
I thought as much. I don't think there's anything else I can do but restart.  Thank-you for the assistance.
