### ISSUE TITLE
Introducing names for vents

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#652]
Is it possible to extend the vents description in .in file to names of the vents? Just as in the case of COMPA. Then use this names in out_f.csv file for columns' header. 
The motivation is automatic parsing of csv files having same name convention for column's headers across the output files.

**Comment by rpeacoc** [comment]
Vents and most other things have names now in a new input file format.  CFAST works for this. More work to do for CEdit to support it. Initial working version of CFAST in 58627cc

**Comment by akrasuski** [comment]
Thank you very much.
