### ISSUE TITLE
Increasing the number of compartments 

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#654]
I would like to place in feature-requests the increase the number of compartments above 100.

**Comment by rpeacoc** [comment]
Are you using the NIST-supplied Windows executables or compiling the code yourself on another platform?  If compiling yourself, you can just change the parameters mxrooms at line 10 of cfast_parameters.f90 in the CFAST source folder in the repo (Source/CFAST) to your chosen value.  Add 1 to your maximum to allow for the outdoors.

**Comment by akrasuski** [comment]
Great, thank you very much! I'm using Linux compiler. However, I think, I can manage it.

**Comment by akrasuski** [comment]
That solves my problem, thanks.
