### ISSUE TITLE
Thanks for your great sofware

### ISSUE THREAD

**Issue by mimooh** [firemodels/cfast#655]
I would like to very much thank to all the developers of CFAST! A couple of months ago we started work on a probabilistic simulator and we have put a lot of effor in it already. I am part of the team along with @akrasuski, who reports issues here. We are pretty much motivated to continue our work, which has gone well this far. Hopefully within a year or two we will present our results. CFAST is the base of our project and it serves to choose interesting scenarios for further FDS analysis, among other purposes. So once again thanks for developing CFAST and for quick fixing of the issues our team reports!

Regards,
Karol Krenski

**Comment by rpeacoc** [comment]
Thanks so much for you kind words.  We do try to respond to all user requests.  It's nice to be recognized for it.
