### ISSUE TITLE
Correction and unification of names and shortcuts in project_m.csv and project_s.csv

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#656]
1. ULN2 and LLN2 should have "_" between parameter shortcut and id of the COMPA, consistently with other parameters. 
2. I guess that it should be NO2 or NOX instead of N2 
3. There is no description in documentation what N2 is. 
4. There is in documentation parameter: CT - concentration time dose is mentioned, however there is no such parameter in csv file.

**Comment by rpeacoc** [comment]
1. That looks like an error. I'll check it out and fix as appropriate.
2.  It is just molecular nitrogen. i.e., N_2 in the atmosphere as a volume fraction.
3. I'll fix the documentation.
4. Ct is an outdated assessment of toxicity and no longer in the code. I'll fix the documentation.

**Comment by rpeacoc** [comment]
Latest commits should resolve issue.  Reopen if additional issues are found
