### ISSUE TITLE
Sprinklers and detectors definition inconsistency

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#662]
I noticed some inconsistency in devices definition in cfast .in file. For sprinklers and heat detectors activation temperature is defined in Kelvins. However it seems that, for smoke detectors temperature is defined in Celsius. Here is attached cfast.in file generated by CEdit 
[cfast.txt](https://github.com/firemodels/cfast/files/752842/cfast.txt). Does it mean, that if I create .in file manually I should follow this convention?

**Comment by rpeacoc** [comment]
I'm confused.  Smoke detectors should have an associated temperature in the input anymore.  The smoke detector input beginning with version 7.1.  The trigger for smoke detectors is smoke obscuration, not temperature

**Comment by akrasuski** [comment]
Thank you for the explanation and sorry for the problem. I should read the manual more carefully.

**Comment by rpeacoc** [comment]
No problem.  You can still simulate smoke alarms via temperature by selecting a heat detector with a low RTI and near-ambient trigger temperature.
