### ISSUE TITLE
Max HRR per m^3

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#663]
When HRR per m^3 exceeds some limits there is an error manifested in log file:  
***Error: Object medium position set to   6.210  3.080  1.250; Maximum HRR per m^3 =  9.092E+06 exceeds physical limits.

In my case, HRR as well as area are drawn from distributions. I would like to implement this constrains at the time when the values are generated, not when I launch CFAST. Could you please point me out where can I find in documentation the equations or constrains which control this parameter?

**Comment by mcgratta** [comment]
Could you post your input file.

**Comment by akrasuski** [comment]
Thank you very much for your help. For example this one: 
[cfast1.txt](https://github.com/firemodels/cfast/files/757982/cfast1.txt)

**Comment by mcgratta** [comment]
You missed an important part of the error message:
```
Log: Typically, this is caused by too small fire area inputs. Check HRR and fire area inputs
```
You have a 2400 kW fire originating from a circular base with diameter equal to 25 cm in a room that is 3 m in height, if I am interpreting this input correctly. This fire would be similar to a jet flame, and it is far beyond the physical validity limits of CFAST. I'll have to look to see what the limits are for this constraint.

**Comment by mcgratta** [comment]
The limit of the HRR per unit volume is 2e6 W/m^3. This is calculated by dividing the max HRR by the volume of a cylinder with a base equal to the fire area and height equal to the flame height as calculated by Heskestad's formula: H=0.235 Q^0.4 - 1.02*D

**Comment by mcgratta** [comment]
Rick P -- in input.f90, I see this
```
hrrpm3 = max_hrr/(pio4*fireptr%characteristic_length**2*(fireptr%characteristic_length+flamelength))
```
I assume that you are dividing the max hrr (in W) by the volume of a cylinder with base area equal to pi*(D/2)^2 and height equal to flamelength. Why do we add characteristic_length to flamelength?

**Comment by akrasuski** [comment]
Thank you very much, this is very helpful. 
As I mentioned I develop a stochastic simulator which is based on CFAST. All the parameter that are uncertain or could variate are represented in a form of probability distributions. In fact, what I really need is conditional probability of area given HRR or HRR given area. Have you hear about papers concerning this topic?

**Comment by mcgratta** [comment]
I suggest you limit Q* between, say 0.5 and 2. Or choose a reasonable range. HRR and area should not vary independently. They are related via Q*.

**Comment by akrasuski** [comment]
Thank you very much. I'll draw Q* from uniform distribution min=0.5 max=2 and HRR from specific distribution related to a building type. Then I'll calculate the area or D via Q*. Does it make sens to you?

**Comment by mcgratta** [comment]
Yes, but there is nothing special about 0.5 and 2. Choose whatever values you think are appropriate.
