### ISSUE TITLE
CEDIT/CFAST 7 won't run

### ISSUE THREAD

**Issue by sreese87** [firemodels/cfast#668]
I am new to this software and am wondering if there is maybe a setting that needs to be changed or if it is possible a glitch in the software but when I attemt to "run" my model, after saving and attempting to run the geometry, the run screen opens but appears to be frozen?  The progress bar does not advance and I do not get any readings of any sort.  I thought that it may be missing information but the box at the bottom shows "no errors."  Any help or input would be greatly appreciated!

**Comment by mcgratta** [comment]
Post your input file. Add the 'txt' suffix so that it can be posted here in this thread.

**Comment by rpeacoc** [comment]
Typically, this indicates something fatally wrong with the input file.  If you run to case from a command prompt, there will be an error that caused the model to die before the GUI was able to check the status of the model run.  If you post your input file, we can look at it in detail.

**Comment by sreese87** [comment]
VERSN,7,Users Guide Example Case !! !!Scenario Configuration !! TIMES,3600,50,50,50 EAMB,293.15,101325,0 TAMB,293.15,101325,0,50 !! !!Material Properties !! MATL,CONCRETE,1.75,1000,2200,0.15,0.94,"Concrete, Normal Weight (6 in)" !! !!Compartments !! COMPA,Comp 1,5,5,3,0,0,0,CONCRETE,CONCRETE,CONCRETE,50,50,50 COMPA,Comp 2,5,5,3,5,0,0,CONCRETE,CONCRETE,CONCRETE,50,50,50 COMPA,Comp 3,5,5,3,5,0,3,CONCRETE,CONCRETE,CONCRETE,50,50,50 !! !!Vents !! HVENT,1,4,1,1,2,0,2,,1,TIME,,,0,1,0,1,0,0 HVENT,1,2,1,1,2,0,0.5,,2,TIME,,,0,1,0,1,0,0 HVENT,3,4,1,1,2,1,0.5,,2,TIME,,,0,1,0,1,0,0 VVENT,3,2,1,1,1,TIME,,,0,0,100,0.5,2.5,1 MVENT,4,1,1,V,2.75,0.25,V,2.75,0.25,0.02,200,300,TIME,,,0,1,0,1,0,4 MVENT,2,4,2,V,2.75,0.25,V,2.75,0.25,0.02,200,300,TIME,,,0,1,0,1,5,4 RAMP,V,3,2,1,3,0,0,100,0.5,500,1 !! !!Fires !! LIMO2,0.1 !!Cushion FIRE,1,2.5,2.5,0,1,TIME,0,0,0,0,Cushion CHEMI,9,6,2,2,0,0.33,5E+07 TIME,0,60,120,180,240,300,360,420,480,540,1800 HRR,0,100000,150000,200000,150000,125000,100000,90000,80000,75000,75000 SOOT,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227,0.227 CO,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557,0.0845557 TRACE,0,0,0,0,0,0,0,0,0,0,0 AREA,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1 HEIGH,0,0,0,0,0,0,0,0,0,0,0 !!Wood_Wall FIRE,2,2.5,5,0,1,TIME,0,0,0,0,Wood_Wall CHEMI,6,10,5,0,0,0.33,1.81E+07 TIME,0,8000
HRR,0,1000000 SOOT,0.015,0.015 CO,0.006171682,0.006171682 TRACE,0,0 AREA,0.05,9 HEIGH,0,3 !! !!Targets and detectors !! DETECT,SPRINKLER,1,347.0389,3,3,2.97,100,1,7E-05 DETECT,SMOKE,1,23.93346,2,2,2.97,404,0,7E-05 DETECT,HEAT,1,303.15,2,2,2.97,5,0,7E-05 TARGET,1,2.2,1.88,2.34,0,0,1,CONCRETE,EXPLICIT,PDE,0.5,Targ 1 !! !!Intercompartment heat transfer !! VHEAT,3,2 !! !!Visualizations !! SLCF,2-D,X,2.5 SLCF,2-D,Y,2.5 SLCF,2-D,Z,2.95

**Comment by gforney** [comment]
as kevin said in an earlier comment, you need to post your input file by adding .txt extension (not include it with the body of the comment)
> Post your input file. Add the 'txt' suffix so that it can be posted here in this thread.

**Comment by sreese87** [comment]
I don't know how to do that.  I converted it over to a notepad which I thought was txt.  copied and pasted it,not sure how to get it where you want it

**Comment by rpeacoc** [comment]
You should be able to just rename your .in file to .txt and attach it by dragging and dropping it

**Comment by sreese87** [comment]
[inputfile.txt](https://github.com/firemodels/cfast/files/821594/inputfile.txt)

**Comment by sreese87** [comment]
this is the current example listed for the program,  I am using it to try to get a model to run then will create my own once I get it running right

**Comment by rpeacoc** [comment]
So your just trying to run the default sample program?  If it doesn't run, it could be that your local machine is not set up to use U.S. English numeric units.  CEdit and CFAST expect the separator between the integer and fractional parts of a number for numeric units to be a period rather than a comma.  See 

https://www.nist.gov/el/fire-research-division-73300/cfast-faqs#Q6

for instructions to fix this.

**Comment by sreese87** [comment]
this was the current setting on my computer, when I try to run it will not give any values and does not give me an option to view an output file of any sort

**Comment by rpeacoc** [comment]
Let's try a little diagnosing of the problem with the following steps.

1. create a folder named Test on your desktop and copy the example file to that folder (this way you avoid issues if you don't have write access to the location in Program Files where we place the file by default).
2. Open a Windows command prompt and cd to that directory (a command something like 

`cd c:\Users\<youraccountname>\Desktop\Test`

3. run CFAST from the command prompt with the command

`C:\Users\admin\Desktop\Test>"\Program Files\firemodels\cfast7\CFAST.exe" Users_Guide_Example.in`

Be sure to include the double quotes (") or it won't run. 

If things run, after a bit, you should see something like the following:

`Total execution time =   3.14     seconds
Total time steps =       3903
Normal exit from CFAST`

The time may be different depending on your machine.  If you get an error, post it and we'll go from there.  If it seems to work, look in the folder and there should be a number of data files produced by CFAST.

**Comment by sreese87** [comment]
tried that and its not running

**Comment by rpeacoc** [comment]
Is ANYTHING printed out in the command windows when it doesn't run?  Without any information, we can't make any progress to figure out what's wrong.
