### ISSUE TITLE
Error: at t (=r1) and stepsize h...

### ISSUE THREAD

**Issue by akrasuski** [firemodels/cfast#669]
I have encountered such a problem running CFAST. Below .in and .log files: 

[cfast_log.txt](https://github.com/firemodels/cfast/files/836871/cfast_log.txt)
[cfast_in.txt](https://github.com/firemodels/cfast/files/836870/cfast_in.txt)

**Comment by rpeacoc** [comment]
This error happens every once in a while. The messages us saying that the model is having a difficult time solving the equations and has given up after numerous tries. Typically, small changes in the inputs will make the problem go away. Often you will see the layer height stuck at the top or bottom of a vent so small changes in the vent dimensions fixes the problem. We've seen this in CFAST for decades and have not been able to trace it to a single issue. Wish I had a better answer.

**Comment by akrasuski** [comment]
Thank you very much for the fast reply. The exit status from CFAST (Linux) was normal. I'm thinking whether error code in this case won't be better. Otherwise parsing the log file will be necessary to spot such a problem.

**Comment by rpeacoc** [comment]
I'll have to check about the exit code. We certainly should set an error flag on this, but the info in the log file would work.

**Comment by rpeacoc** [comment]
Try latest repo 9773334 and see if it fixes the issue for you.  You test case works for me now.

**Comment by akrasuski** [comment]
Thank you very much for your help. So far is ok.

**Comment by KathMich93** [comment]
[16052023.txt](https://github.com/firemodels/cfast/files/11515422/16052023.txt)
 I get the same error message with that code. But why? I already mentioned here:[ ](https://github.com/firemodels/cfast/issues/2047) Do you maybe have an idea how to solve this?
Thank you very much.
