### ISSUE TITLE
Cfast disappear "save view run"

### ISSUE THREAD

**Issue by JonasCheng09** [firemodels/cfast#670]
![issue](https://cloud.githubusercontent.com/assets/26460808/23997249/8551e312-0a8b-11e7-8a42-2143436593f0.jpg)
Under the Cfast, i can't see "save view run" these three button.
How can i solve it?

**Comment by rmcdermo** [comment]
Did you try to increase the resolution of your screen?

**Comment by preneke** [comment]
You do not appear to be running the most current version of CFAST. I would suggest downloading and installing that first and see if that doesn't fix your problem.

**Comment by JonasCheng09** [comment]
@rmcdermo yes. the resolution is 1920x1080 already.
@preneke i use CFAST6 and i try to re-download and install before. This problem is still here...sad:(

**Comment by preneke** [comment]
I am not sure I understand. Have you tried CFAST 7.2 and you still have the problem or did you reinstall CFAST 6?

**Comment by JonasCheng09** [comment]
@preneke have not try to CFAST 7.2 and just re-install CFAST6.

**Comment by preneke** [comment]
I would strongly urge you to install CFAST 7.2. I am not sure of any other solution to your problem.

**Comment by JonasCheng09** [comment]
@preneke fix it when i use the CFAST7 now. Deeply thanks, dude

**Comment by preneke** [comment]
Glad I could help.
