### ISSUE TITLE
problems with ceilings vents

### ISSUE THREAD

**Issue by BurkhardF** [firemodels/cfast#676]
Using CFAST 7.2.1 the simulation does not start with a (very) large number of ceiling vents
The following error message occurred:

Log: ***Error exit from CFAST code = -3
Log: ***Error, dassl - idid = -3
Log: ***Warning:  pressure in room  1
Log: ***Warning:  Solution component with the greatest error is
Log: ierror,r1 =  630    0.9881-323
Log: ***Error: at t (=r1) some element of wt has become <= 0.0
Log: 
Log: Compilation Date : Tue 11/29/2016  02:42 PM
Log: Revision Date    : Tue Nov 29 14:36:41 2016 -0500
Log: Revision         : CFAST7.2.1-1-g6fe9f82
Log: Release Version  : CFAST 7.2.1
Log: 
Log: CFAST
Log: 

The input file is attached (~.in -> ~.txt). The file will run with less ceiling vents.

Kind regards
Burkhard

**Comment by rmcdermo** [comment]
Paul,
Can you please have a look?  Thanks.

**Comment by rpeacoc** [comment]
I don't see an attached .txt file.  Am I missing something?

**Comment by BurkhardF** [comment]
[2400m2_F3_120vents_will-run-with-less-ceiling-vents.in.txt](https://github.com/firemodels/cfast/files/935612/2400m2_F3_120vents_will-run-with-less-ceiling-vents.in.txt)

**Comment by preneke** [comment]
This is a know issue and was fixed in Issue #669.  A maintenance release of CFAST with the fix is forthcoming.

**Comment by KathMich93** [comment]
I also have the question: What to wt and r1 in this error message stand for? What do they mean?
