### ISSUE TITLE
running standard.in with 7.2.1 gives an error

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/cfast#682]
The sample file standard.in for version 7.2.1 gives the error:

***Error: Bad FIRE input. Fire specification is outdated and must include target for ignition

This occurs either with the GUI or running CFAST from a prompt.

**Comment by preneke** [comment]
Jason, are you running the distributed version CFAST 7.2.1 or are you running a compiled version of 7.2.2?

**Comment by drjfloyd** [comment]
Distributed version.

**Comment by preneke** [comment]
We haven't been distributing standard.in for a while. The current test file is Users_Guide_Example.in. Standard.in is just out of date and to get it to run you would have to go into CEdit and associate a target with your fire or set the fire to start at a set time.

**Comment by drjfloyd** [comment]
We will try that file. 

We ran standard.in as the installation test procedure in the User's Guide included with cfast_7.2.1_SMV_6.4.2_win64.exe says to run the file standard.in:

![standard in](https://cloud.githubusercontent.com/assets/12799217/25541120/80f14be4-2c1b-11e7-85ba-cb66601124f9.png)

**Comment by preneke** [comment]
We need to fix that. I will leave this open till we do. Thanks.

**Comment by rpeacoc** [comment]
7.2.2 should be released next week. I'll see that it's fixed for the release.

**Comment by rpeacoc** [comment]
Manual is fixed in 7.2.2 release.  Reopen if you still have issues.
