### ISSUE TITLE
Move manuals to Releases

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/cfast#683]
In an effort to (1) wean ourselves from Drive because those links are fragile and (2) make the GitHub project more self-contained, we moved the manuals from Drive to Release for FDS.  Let's do the same for CFAST.

**Comment by drjfloyd** [comment]
Is this for the nightly builds?

**Comment by rmcdermo** [comment]
No.  For nightly we still use Drive.  We want to put the released manuals in the same place as the bundles under Releases.  Look at FDS as an example:

https://github.com/firemodels/fds/releases

**Comment by drjfloyd** [comment]
Gotcha. I think this is a good plan.

**Comment by gforney** [comment]
manuals are now on github for the latest release
