### ISSUE TITLE
cfastbot fails to run (at least) with -installed option

### ISSUE THREAD

**Issue by rpeacoc** [firemodels/cfast#714]
It doesn’t seem able to run any CFAST cases.  Rather, the error file for all CFAST cases is the following

```
background 1.1.1(unknown) - Jun 20 2017

Version          : 1.1.1
Revision         : unknown
Revision Date    : unknown
Compilation Date : Jun 20 2017 09:54:13
SHA1 hash        : 6c14119ac429bf69d573c13e398c5410e24ad574
Platform         : WIN64  (Intel C/C++)
```

where it should have some CFAST execution information … and none of the CFAST results exist which then tumbles into no matlab plots and no guides, …

I’m using the following command to run cfastbot: 

`runcfastbot -installed -nomatlab -official`

so it’s using my existing copy of background from smokeview 6.5.2.

**Comment by gforney** [comment]
could be my recent changes for cfastbot without the -installed option messed up the -installed option.  I'll take a look
