### ISSUE TITLE
Version 6.2.0

### ISSUE THREAD

**Issue by rdavis4** [firemodels/cfast#729]
I am trying to download this version from [here](https://www.nist.gov/el/fire-research-division-73300/cfast-archive), which attempts to install version[ 6.2.1](http://www2.bfrl.nist.gov/util/register.asp?type=software&CH=15), which then gives me a 404 [error](https://www.nist.gov/el/fire_research/upload/setup_621.exe). Any assistance on downloading version 6.2.0 of CFAST would be appreciated. Thank you,

**Comment by mcgratta** [comment]
Download the latest version from  [here](https://pages.nist.gov/cfast/downloads.html)

**Comment by rdavis4** [comment]
Thanks, I am able to download the latest version but I need to download version 6.2.0. Is that possible?

**Comment by mcgratta** [comment]
Why? We support the latest version, and it's an extra effort for us to maintain the downloads and installation packages of the older versions. Do you have a special reason for using a version of CFAST with known bugs and less experimental validation?

**Comment by rdavis4** [comment]
I am continuing a project that was started using version 6.2.0, and to continue to work on and complete the project I would need that version, knowing that in our report we would need to include extra justification and validation for that version.

**Comment by mcgratta** [comment]
Given that CFAST takes a few seconds to run, why not re-run everything with the latest version? If you find that your results do not change, great. If you find that they do change, then I would argue that the latest results are more reliable than the older.
