### ISSUE TITLE
Output file has no useful data

### ISSUE THREAD

**Issue by DeanT2016** [firemodels/cfast#734]
I am using CFAST V 7.2.2. I copied the example case to another folder. When I run the example case, it goes to completion. However, when I try to view the CFAST Output File, I get a screen with a BIG RED X on the first page and subsequent pages. It says there is 174 pages associated with this file. How can I fix this output file so I can see the actual output? It seems that the output file is corrupted or the run was not successful. Please help!

**Comment by rpeacoc** [comment]
Are you trying to view the file directly in CEdit or using another program to view. I find that notepad works better than the built in viewer.

**Comment by DeanT2016** [comment]
rpeacoc Thanks! I couldn't open the output through the View feature because I did not have a word processor program like Word since this is a new computer. However, once I installed the word processor, I could view the output file.

**Comment by DeanT2016** [comment]
Thank you!

Dean

**Comment by DeanT2016** [comment]
Richard,

Attached is an example of a room that I have compartmentalized. Each
compartment is given a number (1,2, 3A, 3B1, 3B3 & 4). Compartment 1 is a
metal box that shares its walls, floor and ceiling with the other
compartments. Chapter 10 (Surface Connections) in the User's Guide (Version
7) requires a fraction, f, to be specified for  the vertical surface area
of the first compartment that connects the first and second compartment
pair. For the wall in Compartment 1 that is shared between Compartments 1
and 2, is the fraction given by

f12 = A12/A1 = 1.0   since A1 = A12

where
A1 = the surface area of the left wall of Compartment 1
A12 = the surface area common between Compartments 1 and 2

Likewise,

f21 = A21/A2< 1.0

A2 = the surface area of the right wall of Compartment 2
A21 = the surface area common between Compartments 2 and1

If this is so, then f12 + f21 > 1 and will create an error.

If this is not the correct interpretation, please provide explanation.
Thanks,

Dean Tolete

**Comment by rpeacoc** [comment]
I don't see a file attached, but if I follow your logic, I don't think you have it right.  Consider two compartments that share a single wall.  Both compartments are 1 m x 1 m x 1 m in size. The resulting horizontal heat transfer connections would be 0.25 for both compartments sinner they share 1 m^2 of a total wall surface of 4 m^2.  

If the compartments are of different size, then the fraction would be different for the two directions. For example, if compartment 1 is 1 m x 1 m x 1 m and compartment 2 is 2 m x 2 m x 2 m, then the connection from 1>2 is 0.25 and the connection from 2>1 is 0.125.

**Comment by DeanT2016** [comment]
Richard,

That makes a lot of sense. I could not get that from the user's guide. Can
you get your example included in the next update of the user's guide.

Thanks,

Dean Tolete
