### ISSUE TITLE
No Smokeview

### ISSUE THREAD

**Issue by DeanT2016** [firemodels/cfast#738]
After running the example case, I tried to initiate Smokeview but the program stopped responding and the only image I got was that of the compartments with no smoke simulation. How can I fix this?

**Comment by gforney** [comment]
Did you try right clicking the mouse and selecting a load/unload menu ?

**Comment by DeanT2016** [comment]
What should I choose from the load/unload menu?

**Comment by DeanT2016** [comment]
gforney, it works. Thanks.

**Comment by gforney** [comment]
your welcome.
