### ISSUE TITLE
MVENT orientation

### ISSUE THREAD

**Issue by andytamhk168** [firemodels/cfast#739]
In subroutine Input, both orientations (1 and 2) are storing at orientation(1). It looks to me that associated value for lcarray(7) should be stored at orientation(2). Please advise.

***********************************************************
                if (lcarray(4)=='V') then
                    ventptr%orientation(1) = 1
                else
                    ventptr%orientation(1) = 2
                end if
                ventptr%height(1) = lrarray(5)
                ventptr%diffuser_area(1) = lrarray(6)

                if (lcarray(7)=='V') then
                    ventptr%orientation(1) = 1
                else
                    ventptr%orientation(1) = 2
                end if
**************************************************************

**Comment by rpeacoc** [comment]
Complete in 90833fd2cb03fb4388c591b38aee4b6b626063cb
