### ISSUE TITLE
Circular Vent Function

### ISSUE THREAD

**Issue by ffarzana** [firemodels/cfast#745]
CFAST is providing identical data for square and circular vents.

**Comment by mcgratta** [comment]
Rick, try this case, with a round and square ceiling vent:
```
VERSN,7,Test_10
!!
!!Scenario Configuration
!!
TIMES,6068,1,1,1
EAMB,293.15,101325,0
TAMB,291.15,101325,0,50
!!
!!Material Properties
!!
MATL,Gypboard,0.16,1000,480,0.015875,0.9,Gypsum Board
!!
!!Compartments
!!
COMPA,Comp 1,1.1938,1.2192,0.587375,0,0,0,Gypboard,Gypboard,Gypboard,50,50,50
COMPA,Comp 2,1.1938,1.2192,0.6096,0,0,0.587375,Gypboard,Gypboard,Gypboard,50,50,50
!!
!!Vents
!!
HVENT,1,3,1,0.2,0.3222244,0.022225,0.47244,,1,TIME,,,0,1,0,1,0,0
HVENT,2,3,1,0.09999999,0.4032001,0.2032,0.5469,,1,TIME,,,0,1,0,1,0,0
HVENT,2,3,2,0.1,0.4032001,0.2032,0.7366,,4,TIME,,,0,1,0,1,0,0
HVENT,2,3,3,0.1,0.4032001,0.2032,0.7366,,2,TIME,,,0,1,0,1,0,0
VVENT,2,1,1,0.04,1,TIME,,,1850,0.8,2000,0.5,0.8438007,0.8692006
RAMP,V,2,1,1,3,0,1,3600,1,6068,1
!!
!!Fires
!!
!!New Fire
FIRE,1,0.3048,0.3048,0.0508,1,TIME,0,0,0,0,New Fire
CHEMI,3,8,0,0,0,0.3,4.63E+07
TIME,0,60,6000,6060
HRR,2500,2500,2500,0
SOOT,0.015,0.015,0.015,0.015
CO,0,0,0,0
TRACE,0,0,0,0
AREA,0.01,0.01,0.01,0.01
HEIGH,0,0,0,0
!!
!!Intercompartment heat transfer
!!
VHEAT,2,1
```

**Comment by andytamhk168** [comment]
Trying to get involved in the discussion and learn. I have not looked into the vent models in detailed yet.

If the vvent model does not account for flow characteristics (i.e. the associated mass flow rate through the opening due to different shapes), I believe heat transfer parameters such as concentration of the species, energy being added (for this case), or etc should be the same because the value of the area (either square or circular) is the same.

This would be my guess.

**Comment by gforney** [comment]
Wasn't the ceiling vent model changed to a simpler form? Think the original
algorithm had slightly different form for circular vs sq ceiling vents.
More importantly, is this still the case.

**Comment by andytamhk168** [comment]
I took back my comments.

The algorithms for different shapes of vvent are different. Should be gone into the code before making comments.

**Comment by rpeacoc** [comment]
If you look at lines 297-304 of flow vertical.f90, it's only the unstable bidirectional flow that's effected by the shape of the vent with its coefficients taking values of 0.754 or 0.942 depending on the shape.  The underlying unidirectional flow is always a flow coefficient of 0.68. We should take a look at the original source material for the correlation to see if we have it right.

**Comment by andytamhk168** [comment]
I gave it a shot to run the case with vents being in two different shapes. Results generated from the two cases (square and circular vent) are not completely the same. Though the difference on some of the outputs (i.e. flow rate through the ceiling vent) between the two cases is quite small (in the order of 0.001).Also, the density and and pressure differences are small.
I see that the correlation being used for the ceiling vents depends on the size of the opening and the pressure and density differences between the upper layer of the lower compartment and the lower layer of the upper compartment. While the values associated to these parameters are small, I am not sure if we can see significant difference on the flow rate for different vent shape. Horizontal vents on both compartments are opened as well.
I made two similar runs with bigger ceiling vent opening (0.5m2). Comparing the results, a slightly larger difference appears.
Nevertheless, I will need to look into the code/paper and make a few more numerical experiments to make more constructive comments. 

    On Wednesday, July 26, 2017 8:09 PM, Richard Peacock <notifications@github.com> wrote:
 

 If you look at lines 297-304 of flow vertical.f90, it's only the unstable bidirectional flow that's effected by the shape of the vent with its coefficients taking values of 0.754 or 0.942 depending on the shape. The underlying unidirectional flow is always a flow coefficient of 0.68. We should take a look at the original source material for the correlation to see if we have it right.—

**Comment by mcgratta** [comment]
There are some experiments where we have no windows open on the second level, thus causing a two-way flow. 

Fateema -- Take a look at those cases to see the circle makes a difference.

**Comment by ffarzana** [comment]
I used circular vent function and ran CFAST\Validation\NIST_Vent_Study\Test_9.in where all windows were closed at first and CFAST\Validation\NIST_Vent_Study\Test_15.in where windows were closed all the time, and the results for upper and lower layer temperature are exactly the same as they are for square vent function.

**Comment by andytamhk168** [comment]
I have just ran Test_15.in with ceiling vent to be circular shape and square shape. 

What I have found is that; when I open the smokeview files for both cases, it appears that the ceiling vents are all with shape in square regardless if I choose vent shape to be circular or square. 

So, this raises a flag to me. I am trying to look into the code now and see if CFAST is taking the shape correctly.

**Comment by mcgratta** [comment]
Glenn just hasn't had a chance to add that feature. The question to ask is this -- if you run Test_15 with a rectangular vent, and then run Test_15b with a circular vent, and then "diff" the output files, do you see any difference at all? I assume in this case that there is a time interval during which the vent is open between floor 1 and 2, but nothing is open on floor 2. If this is true, we should have 2 way flow through the vent, and the algorithm should distinguish between circle and rectangle.

**Comment by rpeacoc** [comment]
If you look at the spreadsheet output for the two cases, the flow is not identical, but the differences are very small (ranging from 2 x 10^-8 % to 0.3 %). Since only the exchange flow, which is a small fraction of the total flow, depends on the round/square shape, we should only expect small differences..
