### ISSUE TITLE
visualize circular/square ceiling vent as specified in cedit

### ISSUE THREAD

**Issue by gforney** [firemodels/cfast#747]
you can specify a ceiling vent as being either circular or square.  smokeview only displays ceiling vents as rectangles.  also, cedit lets you specify x,y offsets for ceiling vent locations.  smokeview displays ceiling vents in the center of the room.

update smokeview to display ceiling vents as specified in cedit.

**Comment by gforney** [comment]
change .txt to .in to run cases.

The case ceiling_squarecircle.in is non-physical, it has a square and circular ceiling vent located in the same case (wonder if cedit should check for that).  Both vents have the same area, so this case tests visually whether smokeview is computing the correct radius.


[ceiling_circle.txt](https://github.com/firemodels/cfast/files/1181518/ceiling_circle.txt)
[ceiling_square.txt](https://github.com/firemodels/cfast/files/1181519/ceiling_square.txt)
[ceiling_squarecircle.txt](https://github.com/firemodels/cfast/files/1181517/ceiling_squarecircle.txt)

**Comment by gforney** [comment]
try smokeview located here.  you'll also need to update your cfast repo and rebuild cfast (the updated cfast gives smokeview the info it needs to draw ceiling vents as specified in cedit)

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
note to myself - check vent area fractions and vent color

**Comment by andytamhk168** [comment]
Thanks Glenn. Will look into it. 

    On Thursday, July 27, 2017 7:36 PM, Glenn Forney <notifications@github.com> wrote:
 

 try smokeview located here. you'll also need to update your cfast repo and rebuild cfast (the updated cfast gives smokeview the info it needs to draw ceiling vents as specified in cedit)https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing—
