### ISSUE TITLE
Plume temperature / HRR truncation

### ISSUE THREAD

**Issue by juahime** [firemodels/cfast#749]
Hi,

I have identified that when CFAST (v7.2.2) is run as a two-zone model, there is no truncation of temperature as noted in Eq. 3.20 in the Technical Reference Guide (noted below). Therefore, the compartment can reach temperatures beyond 900C as shown in the example attached (PT_2zone_bug.zip with temperatures >2000C).

![image](https://user-images.githubusercontent.com/13573528/28852789-304832e4-776f-11e7-9796-a6660f4c3e7c.png)

If the model is run as a single-zone model, there is a truncation of temperature as noted in Eq. 3.20 as shown in the example attached (PT_1zone_bug.zip with temperatures around 900C).

I was wondering if this is a bug in the coding of the last version, where Equation 3.20 is not satisfied for the two-zone model.

Regards,
Juan Hidalgo

Attachments:
[PT_1zone_nobug.zip](https://github.com/firemodels/cfast/files/1192296/PT_1zone_nobug.zip)
[PT_2zone_bug.zip](https://github.com/firemodels/cfast/files/1192295/PT_2zone_bug.zip)

**Comment by rpeacoc** [comment]
Eq 3.20 only applies to the temperature of the local plume temperature and is not an overall limit of the layer temperatures. Typically very high temperatures are a result of extreme pressures in a compartment (since from the ideal gas law, an increase in pressure leads to a temperature increase). We'll take a look at your test case.

**Comment by rpeacoc** [comment]
With your test case, the only heat loss from the compartment is by flow out the vent.  Heat transfer through the surfaces is turned off resulting in adiabatic conditions.  With a huge fire in a relatively small compartment, plenty of ventilation, and no heat loss by conduction, extreme temperatures can be expected. 

When you run it as a single zone case, the oxygen concentration of the averaged layers gets low enough to restrict the heat release rate to about 1/2 of the two zone case where incoming oxygen to the lower layer keeps the lower layer oxygen high enough to allow complete burning of the full 3 MW fire.

It's not any "truncation of temperature" that's causing the different results. At the moment, I don't see a bug in the solution. I'd suggest you add appropriate thermal properties for the compartment surfaces and see how that changes your results.

**Comment by juahime** [comment]
I understand that the heat losses in the compartment may have an effect on the maximum temperatures in the gas-phase, especially with such high heat release rates in a small volume. 

However, extremely high temperatures are still achieved when conduction losses are included, larger than temperatures expected in real fires. I would expect that the heat release rate would be capped by the ventilation and apparently, it is not.

For instance, I see that the ventilation for both cases converges to the same inflow:
![image](https://user-images.githubusercontent.com/13573528/28898512-b33ed670-7829-11e7-89fe-1e7f5a6ed0bd.png)
But the HRR is not:
![image](https://user-images.githubusercontent.com/13573528/28898621-3e3614e6-782a-11e7-9338-9fb0dba4ce26.png)

And eventually, the temperatures are obviously extremely different, even with same inflow:
![image](https://user-images.githubusercontent.com/13573528/28898473-67dfee58-7829-11e7-8231-d5da79c57a56.png)
![image](https://user-images.githubusercontent.com/13573528/28898479-74166e54-7829-11e7-9c98-e2a63e3a727f.png)

Please, could you verify whether the issue is in the truncation of the HRR instead?

Thanks,
Juan Hidalgo

**Comment by andytamhk168** [comment]
From the figures you have shown in the attachment, I see that the fire you have set is sitting on the floor. For your run with the single zone compartment, smoke is completely filled. For your run with the two zone model, the smoke/soot is only accumulating on the upper layer; the lower layer seems to be with less/no soot.So, one thing you may like to be be careful of is that how well your fire can sustain/grow will depend on the availability of oxygen. As pointed out by Rick that without enough oxygen, the size of your fire in terms of HRR is greatly reduced. 



    On Wednesday, August 2, 2017 7:01 PM, Juan P. Hidalgo <notifications@github.com> wrote:
 

 I understand that the heat losses in the compartment may have an effect on the maximum temperatures in the gas-phase, especially with such high heat release rates in a small volume.However, extremely high temperatures are still achieved when conduction losses are included, larger than temperatures expected in real fires. I would expect that the heat release rate would be capped by the ventilation and apparently, it is not.For instance, I see that the ventilation for both cases converges to the same inflow:

But the HRR is not:
And eventually, the temperatures are obviously extremely different, even with same inflow:

Please, could you verify whether the issue is in the truncation of the HRR instead?Thanks,
Juan Hidalgo—

**Comment by rpeacoc** [comment]
The heat release is capped by the oxygen concentration.  I'd compare the oxygen concentration in the lower layer of the two layer case to the oxygen concentration in the single layer in the one zone case.  CFAST uses a simple cutoff for available oxygen, assuming that when the oxygen level in the entrained air is below a default value of 15 %, the combustion stops.  In reality, it's a much more complex chemistry problem that's beyond a simple two zone model.

**Comment by juahime** [comment]
I agree, @andytamhk168 . You are right regarding the availability of oxygen in different layers, and as result different HRR in both models.

The inflows in the plots above, extracted from _f.csv file seem not correct though. 3000 MW should correspond to an inflow of oxygen of 0.23 kg/s, which is approximately 1 kg/s of air. That flow seems to match more with the values of the output HSLABF in the _zone.csv file.

It would be interesting to see if the model could have a criterion to switch from two-zone to one-zone, as a two-zone model does not seem suitable to conditions such as these large HRR corresponding to under-ventilated fires; or to truncate maximum temperatures expected in fully-developed fires.

Cheers,
Juan

**Comment by andytamhk168** [comment]
Dear Juan,
Before even attempting to change the code, I would actually like to ask what you are trying to do with this existing problem. I am fairly new to this fire research community, so my knowledge could be limited. However, based on your problem set up, you are more like simulating an explosion in a compartment. So, I think you will need to take a step back and see what kind of physics is involved in your problem and the level of details on the "solution" that you are looking for. With that in mind, you will then need to understand the capabilities of the code and the assumptions being made in the code. 
Correct me if I am wrong, but I believe that accurate simulation a resulting phenomenon for problem with "explosion" would require more than just switching from a two zone model to a one zone model.
Kind regards,Andy

  

    On Wednesday, August 2, 2017 9:56 PM, Juan P. Hidalgo <notifications@github.com> wrote:
 

 I agree, @andytamhk168 . You are right regarding the availability of oxygen in different layers, and as result different HRR in both models.The inflows in the plots above, extracted from _f.csv file seem not correct though. 3000 MW should correspond to an inflow of oxygen of 0.23 kg/s, which is approximately 1 kg/s of air. That flow seems to match more with the values of the output HSLABF in the _zone.csv file.It would be interesting to see if the model could have a criterion to switch from two-zone to one-zone, as a two-zone model does not seem suitable to conditions such as these large HRR corresponding to under-ventilated fires; or to truncate maximum temperatures expected in fully-developed fires.Cheers,
Juan—

**Comment by juahime** [comment]
Dear @andytamhk168 and @rpeacoc ,

Thanks for your replies. I agree that the problem at that stage is a more complex chemistry, not even well solvable with CFD models. I also agree that the energy released will be capped by the amount of oxygen entrained in the compartment (just saw that the _f.csv filed does not provide the right mass inflow or outflow, I believe, which confused me calculating the HRR).

My suggestion is that to have a two-zone model once under-ventilated conditions are achieved seems not adequate. The HRR is not capped due to the well-ventilated conditions in the bottom layer, which eventually leads to very high temperatures. Obviously, this only matters if the LOL is >0%; as if it is equal to 0% the two-zone and the one-zone would give you same temperature results.

In the end, it is a matter of the user to understand the limitations of the model; and this scenario with a large HRR is a clear one.

To me (humbly), the interesting thing is whether you would still be able to "model" a fully-developed under-ventilated fire with sensible temperatures in the compartment (e.g. Thomas plot below), and being able to spill those hot gases to other compartments. I understand this is probably beyond the capabilities of the model, and perhaps a truncation is needed there (similarly to truncation of the plume temperature)?
![image](https://user-images.githubusercontent.com/13573528/28909260-0449d916-786b-11e7-85da-b278d014f3ac.png)

You have suggested that the issue is in the adiabatic boundaries; however, that does not completely solve the issue of very high temperatures.

Regards,
Juan

PS: I am definitely not trying to model an explosion or modify the model, but trying to understand what CFAST does when these conditions are reached :-)

**Comment by rpeacoc** [comment]
Once flashover is reached and all items in a compartment are burning, there are certainly a numbers of issues that are not taken into account. Perhaps most notably is the distributed nature of the burning and thus the local availability of oxygen. In what experimental data that exist, the combustion near the doorway looks like a well-ventilated fire, while away from the vent, conditions become dramatically under-ventilated. Overall, this would likely dramatically change the plume and its entrainment. 

There is some validation data in the CFAST guide with near or post flashover conditions (see the 1 room tests and the WTC tests in the V&V guide). The results are consistent with the overall accuracy of the model with careful definition of the entire scenario well beyond just defining a high HRR.

Still, I'm sure that the further beyond the onset of flashover you get, the more questionable a simple definition of a fire and its entrainment gets. For truly post flashover fires, the inputs for a fire would have to be adjusted by the user (though it's not clear that the literature would provide a lot of guidance on how to do this). The simple free-burning plume correlation and oxygen availability calculation would become less accurate.
