### ISSUE TITLE
Remove limit of 4 vent connections per compartment pair

### ISSUE THREAD

**Issue by GoogleCodeExporter** [firemodels/cfast#80]
```
Would it be possible to lift the constraint of 4 vent connections
between compartments? 


```

Original issue reported on code.google.com by `cfastdev@gmail.com` on 10 Jan 2012 at 7:42

**Comment by rpeacoc** [comment]
There's now just a limit on total number of vent connections which is currently set to 25 * maximum number of compartments (for a total of 2500 now)
